### ISSUE TITLE
子应用执行apply后不符合正常程序预期

### ISSUE THREAD

**Issue by Heath1998** [Tencent/wujie#102]
**描述bug**
子应用下使用如下代码，输出结果不合预期。结果为undefined，预期结果为'test'字符串

**如何复现**
``` 
<script>
    const object = {};
    window.addAttributeToObject = function () {
      this.a = "test";
    };
    window.addAttributeToObject.apply(object);
    console.log(object.a); // undefined
  </script>
```

**错误截图**
-

**最小复现仓库或者地址**
-

**Comment by yiludege** [comment]
这个问题是由于 window 被 proxy 引起的，目前的思路是在对 window 的 某个 propety 做 set 的时候，满足一定条件（必须是函数且满足getTargetValue内部的那个条件）时，给这个函数 设置一个 私有属性 __xxx、或者存入一个map当中，下次 get 的时候判断存在__xxx或者在map中，在 getTargetValue 中直接返回
