### ISSUE TITLE
没有编译的老旧项目加载会出问题

### ISSUE THREAD

**Issue by 18610509683** [Tencent/wujie#11]
相对路径会访问主应用服务器端的

**Comment by yiludege** [comment]
1、对于js沙箱，子应用的 iframe 会设置 base 标签，所以在里面跑的script和接口请求相对都能够正确修正
2、对于dom沙箱，框架劫持了img、a、source、link、script等元素的原型方法，当这些元素设置地址的时候会将相对地址改写成绝对地址
3、对于在css内部的比如background-image: url('./images/my-image.png')框架确实没有处理，可以[参考](https://wujie-micro.github.io/doc/question/#_6%E3%80%81css%E6%A0%B7%E5%BC%8F%E5%86%85%E9%83%A8%E7%9A%84%E7%9B%B8%E5%AF%B9%E5%9C%B0%E5%9D%80%E7%9B%B8%E5%AF%B9%E7%9A%84%E6%98%AF%E4%B8%BB%E5%BA%94%E7%94%A8%E7%9A%84%E5%9F%9F%E5%90%8D)

如果确实还有问题，可以采用[插件](https://wujie-micro.github.io/doc/guide/plugin.html)，其中html-loader、js-loader、css-loader可以将html、js和css在运行时做替换，比如正则匹配找出相对地址链接替换成绝对地址链接从而避免去改动子应用的代码

**Comment by 18610509683** [comment]
还有就是子应用的静态定位会出问题，定位到主应用里

**Comment by yiludege** [comment]
这个方便给个复现demo吗？我这边没有复现到具体问题

**Comment by yiludege** [comment]
> 3、对于在css内部的比如background-image: url('./images/my-image.png')框架确实没有处理
@18610509683 这个问题框架也已经处理了，详见 #35
