### ISSUE TITLE
在主应用页面下，刷新后直接跳转到子应用

### ISSUE THREAD

**Issue by lyanmm** [Tencent/wujie#114]
**描述bug**
在主应用页面下，刷新后直接跳转到子应用

**如何复现**
以下提及的项目均采用 vite2/3、react 17/18。
1. 主应用路由是 react-router-dom 6 的 BrowserRouter，其余子应用都是 HashRouter。
2. 开发环境下都能正常使用，刷新也没问题，就尝试将所有项目打包后放到 nginx 里。

**其他**
1. 猜测 nginx.conf 没有配置正确，以及各个项目的 vite.config 打包配置错误。
2. 希望能给一份nginx的配置参考一下，或者就线上 demo 的配置也行。（ https://wujie-micro.github.io/demo-main-vue/home ）
3. 或者类似micro-app那样的文档。（https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/deploy）

**Comment by yiludege** [comment]
> 在主应用页面下，刷新后直接跳转到子应用

这个是什么意思呢？主应用整体跳转到子应用了？demo是采用 github page 生产的，没有 ng 配置哦

**Comment by lyanmm** [comment]
问题已解决，子应用路径需要与主应用ng配的路径一致。
详见仓库的提交记录：https://github.com/lyanmm/wujie-demo/commit/23e979bf03e20a1a9209c020c0c1d33355c4222f
