### ISSUE TITLE
element-ui 弹框内使用select组件，弹出框位置异常

### ISSUE THREAD

**Issue by lp0124** [Tencent/wujie#123]
**如何复现**
1、clone下代码
2、根目录执行npm i
3、根目录执行npm run serve

**错误截图**
在wujie下运行的
<img width="783" alt="image" src="https://user-images.githubusercontent.com/22974194/188252005-a37d7872-4000-4863-9d39-f138d1cb99b9.png">

单独运行的
<img width="721" alt="image" src="https://user-images.githubusercontent.com/22974194/188252013-01722aa5-3d55-4098-b55d-88ad45382c4e.png">

**复现仓库地址**
https://github.com/lp0124/wujie-demo

**Comment by ErKeLost** [comment]
https://wujie-micro.github.io/doc/question/#_4%E3%80%81%E5%86%92%E6%B3%A1%E7%B3%BB%E5%88%97%E7%BB%84%E4%BB%B6%EF%BC%88%E6%AF%94%E5%A6%82%E4%B8%8B%E6%8B%89%E6%A1%86%EF%BC%89%E5%BC%B9%E5%87%BA%E4%BD%8D%E7%BD%AE%E4%B8%8D%E6%AD%A3%E7%A1%AE

**Comment by lp0124** [comment]
@ErKeLost 子应用已设置，仍未解决
<img width="816" alt="image" src="https://user-images.githubusercontent.com/22974194/188256750-54bb3423-4021-4e89-b234-68ab49fcad75.png">

**Comment by SericXu** [comment]
#74

**Comment by handoing** [comment]
尝试下给select组件设置:popper-append-to-body="false"

Ref: [#73](https://github.com/Tencent/wujie/issues/73#issuecomment-1235474525)

**Comment by lp0124** [comment]
@handoing 不插入到body下确实是可以解决位置异常的问题，但对体验是有影响的，弹框中有下拉菜单会出现滚动条
<img width="741" alt="image" src="https://user-images.githubusercontent.com/22974194/188544214-4f7abffe-f6b1-4c62-a65c-9c62f6a717c3.png">

**Comment by yiludege** [comment]
对于 element-ui@2.15.9 可以这样处理：
1、给select组件设置:popper-append-to-body="false"
2、将冒泡的组件的 position 设置为 absolute，本来对于element-ui@2.15.9 /lib/utils/popper.js 里面有一个forceAbsolute配置项，但是选择器没有提供出来，所以只能进行代码替换（生产模式可能存在代码压缩，需要找出压缩代码）：
```javascript
plugins: [
  {
    jsLoader: (code) => {
      return code.replace(
        "this.state.position = this._getPosition(this._popper, this._reference);",
        "this.state.position = 'absolute';"
      );
    },
  },
],
```
这样这个 demo 就OK了

<img width="631" alt="image" src="https://user-images.githubusercontent.com/19788268/189891029-cf14431b-90c8-4e3a-9bf4-8cb8f1ab6ebd.png">

**Comment by lp0124** [comment]
@yiludege 这个貌似 select 会一直从上面展开吧

**Comment by yiludege** [comment]
这个是由 popper.js来计算，因为不管是第一点还是第二点其实都是 popper.js 的配置项，不排除wujie的影响，popper.js代码看起来太费劲了

**Comment by squallliu** [comment]
这问题还是催 element-ui 升级 popper.js 吧，element-ui 2.x 把  popper.js 1.x 拷贝到内部了，其实升级到 popper.js 1.16.1 也就是 1.x 的最新版本就能解决。
这个分支就解决了 https://github.com/EOITek/element

**Comment by swmjj** [comment]
目前有个奇淫技巧，
可以在shadow-root外层，加一个padding，shadow-root内层的html，加一个负边距做抵消。

这个issues的复现仓库为例子https://github.com/lp0124/wujie-demo
在复现仓库里面，提了pr，可以拉下来看看。
父子应用是上下布局的话。
在父应用app.vue
```
<template>
  <div id="app">
    <div>主应用</div>
    <div>
      <WujieVue
        class="aaa"
        name="vue2"
        :plugins="plugins"
      ></WujieVue>
    </div>
  </div>
</template>

<script>
import HelloWorld from './components/HelloWorld.vue'
export default {
  name: 'App',
  components: {
    HelloWorld
  },
  data(){
    // 83px = 23 + 60,子应用距离浏览器视窗top距离
    return {
      plugins:[
      {
        cssBeforeLoaders: [
          { content: "html{padding-top: 83px;height:100%}" },
        ],
      },
      ]
    }
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
.aaa{
  width: 100vw;
  height: 100vh;
  margin-top: -83px;
}
</style>
```

同理，如果是父子应用是左右布局的话，可以padding-left + 负边距相抵消。具体的偏移的方向以及数值，可以根据子应用挂载的dom去计算获得。

目前在element-ui，antd，aroc，这3个ui框架简单测试了一下，可以正常显示。

**Comment by yiludege** [comment]
> 目前有个奇淫技巧， 可以在shadow-root外层，加一个padding，shadow-root内层的html，加一个负边距做抵消。

思路清奇，牛 👍

**Comment by quqingfei** [comment]
> 这问题还是催 element-ui 升级 popper.js 吧，element-ui 2.x 把 popper.js 1.x 拷贝到内部了，其实升级到 popper.js 1.16.1 也就是 1.x 的最新版本就能解决，我们公司就用的自己维护的版本，就没这个问题。 这个分支就解决了 https://github.com/EOITek/element

上面的回答是当前Element-UI最好的解决办法还是直接使用这个版本的element-ui是最完美的；
https://www.npmjs.com/package/element-ui-eoi
![image](https://user-images.githubusercontent.com/16645035/191689953-72745fcb-e1ab-4ce3-b3b3-550fa5a9e941.png)
![image](https://user-images.githubusercontent.com/16645035/191690009-fd37efcf-d845-45c5-827d-0cd2051b3305.png)
使用后，啥都不用改，直接就OK了, 亲测有效！

**Comment by yiludege** [comment]
可以试试这个方案，副作用不敢保证 

https://github.com/Tencent/wujie/pull/214#issuecomment-1277226699

**Comment by CSXxiaoxing** [comment]
朴素的代码往往只需要简单的修改：
https://blog.csdn.net/weixin_40968646/article/details/129306272

**Comment by zhou470259742** [comment]
> 朴素的代码往往只需要简单的修改： https://blog.csdn.net/weixin_40968646/article/details/129306272

楼上这个是正解，测试可用，调整也简单点

**Comment by ddm996947822** [comment]
> > 朴素的代码往往只需要简单的修改： https://blog.csdn.net/weixin_40968646/article/details/129306272
> 
> 楼上这个是正解，测试可用，调整也简单点

有效果

**Comment by quqingfei** [comment]
我这个帖子内回复了使用最小成本实现elemet-ui在popper.js内通过代替源码方式实现弹框偏移解决方案，你可以看看。
https://github.com/Tencent/wujie/issues/682#issuecomment-1696111047

**Comment by dengjuncong** [comment]
> > > 朴素的代码往往只需要简单的修改： https://blog.csdn.net/weixin_40968646/article/details/129306272
> > 
> > 
> > 楼上这个是正解，测试可用，调整也简单点
> 
> 有效果

有考虑边界情况吗，会不会根据位置自动改变弹出方向

**Comment by cereschen** [comment]
> 有考虑边界情况吗，会不会根据位置自动改变弹出方向

这个方式应该是对子应用侵入最小的 但是要注意一点 子应用 height不是 100% 而是 calc(100% + 83px) 如果有left边距 同理

**Comment by cereschen** [comment]
> 目前有个奇淫技巧， 可以在shadow-root外层，加一个padding，shadow-root内层的html，加一个负边距做抵消。
> 
> 这个issues的复现仓库为例子https://github.com/lp0124/wujie-demo 在复现仓库里面，提了pr，可以拉下来看看。 父子应用是上下布局的话。 在父应用app.vue
> 
> ```
> <template>
>   <div id="app">
>     <div>主应用</div>
>     <div>
>       <WujieVue
>         class="aaa"
>         name="vue2"
>         :plugins="plugins"
>       ></WujieVue>
>     </div>
>   </div>
> </template>
> 
> <script>
> import HelloWorld from './components/HelloWorld.vue'
> export default {
>   name: 'App',
>   components: {
>     HelloWorld
>   },
>   data(){
>     // 83px = 23 + 60,子应用距离浏览器视窗top距离
>     return {
>       plugins:[
>       {
>         cssBeforeLoaders: [
>           { content: "html{padding-top: 83px;height:100%}" },
>         ],
>       },
>       ]
>     }
>   }
> }
> </script>
> 
> <style>
> #app {
>   font-family: Avenir, Helvetica, Arial, sans-serif;
>   -webkit-font-smoothing: antialiased;
>   -moz-osx-font-smoothing: grayscale;
>   text-align: center;
>   color: #2c3e50;
>   margin-top: 60px;
> }
> .aaa{
>   width: 100vw;
>   height: 100vh;
>   margin-top: -83px;
> }
> </style>
> ```
> 
> 同理，如果是父子应用是左右布局的话，可以padding-left + 负边距相抵消。具体的偏移的方向以及数值，可以根据子应用挂载的dom去计算获得。
> 
> 目前在element-ui，antd，aroc，这3个ui框架简单测试了一下，可以正常显示。

这个方式应该是对子应用侵入最小的 但是要注意一点 子应用 height不是 100% 而是 calc(100% + 83px) 如果有left边距 同理

**Comment by Yang-yibu** [comment]
> 目前有个奇淫技巧， 可以在shadow-root外层，加一个padding，shadow-root内层的html，加一个负边距做抵消。
> 
> 这个issues的复现仓库为例子https://github.com/lp0124/wujie-demo 在复现仓库里面，提了pr，可以拉下来看看。 父子应用是上下布局的话。 在父应用app.vue
> 
> ```
> <template>
>   <div id="app">
>     <div>主应用</div>
>     <div>
>       <WujieVue
>         class="aaa"
>         name="vue2"
>         :plugins="plugins"
>       ></WujieVue>
>     </div>
>   </div>
> </template>
> 
> <script>
> import HelloWorld from './components/HelloWorld.vue'
> export default {
>   name: 'App',
>   components: {
>     HelloWorld
>   },
>   data(){
>     // 83px = 23 + 60,子应用距离浏览器视窗top距离
>     return {
>       plugins:[
>       {
>         cssBeforeLoaders: [
>           { content: "html{padding-top: 83px;height:100%}" },
>         ],
>       },
>       ]
>     }
>   }
> }
> </script>
> 
> <style>
> #app {
>   font-family: Avenir, Helvetica, Arial, sans-serif;
>   -webkit-font-smoothing: antialiased;
>   -moz-osx-font-smoothing: grayscale;
>   text-align: center;
>   color: #2c3e50;
>   margin-top: 60px;
> }
> .aaa{
>   width: 100vw;
>   height: 100vh;
>   margin-top: -83px;
> }
> </style>
> ```
> 
> 同理，如果是父子应用是左右布局的话，可以padding-left + 负边距相抵消。具体的偏移的方向以及数值，可以根据子应用挂载的dom去计算获得。
> 
> 目前在element-ui，antd，aroc，这3个ui框架简单测试了一下，可以正常显示。

这种方式需要 主应用中其他的元素都定位，并且 z-index 高吧，否则 heder 或侧边栏等不能点击了

**Comment by whateveryoudo** [comment]
感觉也不用抵消操作,大概推断是 计算临界位置 取到了主应用的 body， 目前解决办法：1.主应用全部采用fixed或者absolute(保证子应用实际是占满屏幕的，其实主应用大部分都只是壳子布局，全部用fixed absolute影响也不大) 2. 修改UI库框架源码 ，antd为例参照：[https://github.com/Tencent/wujie/issues/824](url) 。

**Comment by whateveryoudo** [comment]
无界 Polyfill  貌似提供了兼容处理   https://wujie-polyfill.github.io/doc/plugins/docElementRect.html  antd-vue  下正常了
