### ISSUE TITLE
请问下，主应用是旧的前后端不分离+jQuery项目，应该如何接入wujie

### ISSUE THREAD

**Issue by xuchao996** [Tencent/wujie#126]
rt

**Comment by gadzan** [comment]
可以参考 packages/wujie-react 的实现方式，容器 DOM 可以作为 startApp 方法下的 el 属性传入；

**Comment by yiludege** [comment]
原生应用的话直接采用 startApp 就可以了

![image](https://user-images.githubusercontent.com/19788268/191189920-c902cb66-8131-462b-ba26-ef78b0b45b1f.png)

**Comment by GreatAuk** [comment]
前后端不分离+jQuery项目做子应用还支持吗
