### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by 317329584** [Tencent/wujie#127]
9.2日的版本是不是有问题呀，我这边开发环境加载webpack vue3、vite vue3项目失败了，换了个旧版本的就好了

**Comment by yiludege** [comment]
有报什么错误吗

**Comment by 317329584** [comment]
提示跨域了

**Comment by yiludege** [comment]
跨域的问题应该不是框架的问题哈

**Comment by 317329584** [comment]
本地开发环境已经设置允许跨域了，我没有仔细去看wujie版本号，但是换了往前一个版本的就没有问题了，也可能是我的依赖包出问题了
