### ISSUE TITLE
vue主应用安装依赖失败Could not resolve dependency: npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.19

### ISSUE THREAD

**Issue by first236108** [Tencent/wujie#130]
**描述bug**
vue主应用安装依赖失败

**如何复现**
1、第一步 git clone https://github.com/Tencent/wujie.git
2、 第二步 cd wujie/examples/main-vue
3、第三步 npm install

**错误截图**
![微信截图_20220905142256](https://user-images.githubusercontent.com/24523802/188383607-6975f00a-ce82-42b0-bbe8-b5f6a68d6024.png)

**最小复现仓库或者地址**
无。

**My environment**
Win10
node: 14.15.0
npm: 8.16.0

**Comment by yiludege** [comment]
请按照文档安装哈
![image](https://user-images.githubusercontent.com/19788268/188384308-2c03e24b-c896-4d43-a7e6-273af97dad6e.png)
