### ISSUE TITLE
保活模式下多个子应用切换出现 sync 字段空指针问题

### ISSUE THREAD

**Issue by fychinesepjj** [Tencent/wujie#133]
**描述bug**
保活模式下配置了 `sync=true`和`alive=true`选项
多个子应用通过 router-link 进行切换是正常运行，但如果此时通过浏览器历史操作面板，如：
<img width="100" alt="image" src="https://user-images.githubusercontent.com/5492785/188615066-53a98bbb-8457-4e60-8bbc-e841d3dadb8d.png">
反复进行前进和后退操作则会出现 `sync` 空指针报错问题。

菜单点击顺序：`首页 => 关于 => A子应用 => B子应用`
历史操作顺序：`back => back => back => back => forward => forward => forward => forward =>back....`

**如何复现**
chrome：v93（异常） v104（正常）
应用：vue2 应用
版本：
* vue@2.7.10  
* wujie@1.0.0-rc.13 
* wujie-vue2@1.0.0-rc.13

**子应用配置**
主应用地址: http://localhost:8080
A子应用地址：http://localhost:8081/
B子应用地址：http://localhost:8082/

**路由配置**
``` javascript
  const routes = [
    {
       path: '/A',
       name: 'A',
       component: APage
    },
    {
       path: '/B',
       name: 'B',
       component: BPage
    }
]
```

**页面模版**
``` html
<!--导航-->
 <nav>
     <router-link to="/">首页</router-link>
     <router-link to="/about">关于</router-link>
   <router-link to="/A">A应用</router-link>
    <router-link to="/B">B应用</router-link>
</nav>

<!--APage页面模版-->
<WujieVue
 name="A"
 url="http://localhost:8081"
 :sync="true"
 :alive="true"
></WujieVue>

<!--BPage页面模版-->
<WujieVue
 name="B"
 url="http://localhost:8082"
 :sync="true"
 :alive="true"
></WujieVue>
```

**错误截图**
![image](https://user-images.githubusercontent.com/5492785/188618272-4fa56dda-be55-402c-98b7-b6e3b6c39283.png)

**Comment by fychinesepjj** [comment]
经测试，如果设置 `alive =false` 非保活模式则不会出现这个报错问题。

**Comment by yiludege** [comment]
这个地方方便将这个demo提交一个仓库贴上来吗，方便我来验证这个问题，我本地 demo 没有复现这个问题

**Comment by fychinesepjj** [comment]
> 这个地方方便将这个demo提交一个仓库贴上来吗，方便我来验证这个问题，我本地 demo 没有复现这个问题

@yiludege 你好，这是demo的仓库地址：https://github.com/fychinesepjj/wenjie-demo
该项目我重新搭建，暂时目前还没复现 sync 报错问题（有问题的项目在公司电脑中无法外传），如果复现了会随时同步你。

**不过有一个新的问题，不确定是不是bug，在这个 demo 中可以复现。**
具体现象：反复点击da导航栏 <A应用>和<B应用>跳转， url 中的 query 参数会丢失
应用配置：`sync=true, alive=true`

**菜单配置**
``` html
  <div id="app">
    <div id="nav">
      <router-link to="/">Home</router-link> |
      <router-link to="/about">About</router-link> |
      <router-link to="/app/A?A=%2Fabout">A应用</router-link> |
      <router-link to="/app/B?B=%2Fabout">B应用</router-link>
    </div>
    <router-view/>
  </div>
```

**正常显示**
第一次点击没问题
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/5492785/188853090-87ac31e1-e5de-4fc4-98be-071bbd6abaa5.png">

**异常显示**
多次反复A和B应用切换后出现问题
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/5492785/188853304-17daa050-bbee-443c-8bfc-d3b2a5702708.png">

**Comment by yiludege** [comment]
这个不是异常，没关系的

**Comment by fychinesepjj** [comment]
> 这个不是异常，没关系的

@yiludege 现在出现的这种现象实际不是我们期望的，因为和实际配置链接地址是有差异，并且是在切换过程中发生地址回写，这个能优化么？

**Comment by fychinesepjj** [comment]
@yiludege 昨天说的 `sync`报错问题我复现了，应该和浏览器兼容性问题相关，还是这个 demo ，运行在chrome 浏览器 **93.0.4577.63 （x86_64)** 版本， **macbook 环境**下可以稳定复现。
没问题的 chrome 版本是 v104

**Comment by fychinesepjj** [comment]
总结我的两个问题：
1. `sync` 报错问题，在 v93 版本 chrome 版本下会出现同步错误的情况。
2. 子应用之间反复切换，跳转地址被回写，希望能正常保留 query 参数。

**Comment by yiludege** [comment]
今天查看了一下demo，对于问题2应该是你这边理解有误：
只有子应用第一次渲染才会从 url 同步回来路由（对应于浏览器刷新或者url分享），其他时候都是将自己的路由同步到浏览器上，所以切换其他应用再切换回来参数就没有了

两个子应用都做了生命周期转换，对于单例模式，不要通过`  <router-link to="/app/A?A=%2Fabout">A应用</router-link> `这种方式跳转A应用到 about 路由上，而是通过 startApp 的 url 来实现跳转，url 是哪个路由，子应用就渲染哪个路由

**Comment by fychinesepjj** [comment]
> 今天查看了一下demo，对于问题2应该是你这边理解有误： 只有子应用第一次渲染才会从 url 同步回来路由（对应于浏览器刷新或者url分享），其他时候都是将自己的路由同步到浏览器上，所以切换其他应用再切换回来参数就没有了
> 
> 两个子应用都做了生命周期转换，对于单例模式，不要通过` <router-link to="/app/A?A=%2Fabout">A应用</router-link>`这种方式跳转A应用到 about 路由上，而是通过 startApp 的 url 来实现跳转，url 是哪个路由，子应用就渲染哪个路由

好的，收到，谢谢，第二个问题我改下使用方式，如果可以也麻烦更新下文档，把我们这些常见误用的情况统一说明下。

**Comment by yiludege** [comment]
第一个问题应该是浏览器的 bug，回退的时候，iframe 重新刷新了导致沙箱全部被毁了

**Comment by fychinesepjj** [comment]
针对第二个问题，我再补充下，这里其实我并不是想用单例模式，因为单例模式不能保活（需要设置 alive=false）。
需求背景是：
1. 在同一page下，通过路由参数区分，从接口获取子应用配置，能支持动态配置子应用能力。（子应用地址不会写死）
2. 在这个场景下，又希望子应用能支持保活（单例模式不支持）

目前看这两个需求是有冲突的～，不知道有没有好的建议

**Comment by fychinesepjj** [comment]
> 第一个问题应该是浏览器的 bug，回退的时候 iframe 重新刷新了导致沙箱全部被毁了，不清楚为什么回退动作导致 iframe 会刷新，正常情况是 iframe 是不应该刷新的 被刷新的沙箱： ![image](https://user-images.githubusercontent.com/19788268/189292963-ac3c6b76-a8ea-4d1e-809a-0859f269c872.png) 正常的沙箱： ![image](https://user-images.githubusercontent.com/19788268/189293040-8cc74b4c-97fd-4620-a3a7-ae990bd35243.png)

是的，head里的base节点也就没有了，和我本地现象一样。

**Comment by fychinesepjj** [comment]
这个或许要看下chrome v93版本后是否有更新，目前看最新版本chrome没有这个问题，不排除是chrome iframe的bug

**Comment by loser-or-no** [comment]
请问最后怎么解决的呢

**Comment by loser-or-no** [comment]
请问最后怎么解决的呢，两位大佬 @yiludege @fychinesepjj
