### ISSUE TITLE
[Bug report]  React子应用监听容器滚动事件失效

### ISSUE THREAD

**Issue by Mmear** [Tencent/wujie#143]
**描述bug**
React16 下的子应用无法使用 React 合成事件监听某容器滚动事件（onScroll)

**如何复现**
```jsx
// 子应用滚动事件测试
const Home = () => {
  const scrollConRef = React.useRef();
  React.useEffect(() => {
    // document绑定，未运行
    document.addEventListener("scroll", (e) => console.log("document capture", e.target.scrollTop), true);
    document.addEventListener("scroll", (e) => console.log("document bubble", e.target.scrollTop));
   // 原生事件绑定，正常运行
    scrollConRef.current.addEventListener(
      "scroll",
      (e) => console.log("scrollConRef capture", e.currentTarget.scrollTop),
      true
    );
    scrollConRef.current.addEventListener("scroll", (e) =>
      console.log("scrollConRef bubble", e.currentTarget.scrollTop)
    );
  }, []);


  return (
      <div
        ref={(r) => (scrollConRef.current = r)}
        onScrollCapture={(e) => {
         // 未运行
          console.log("react event capture", e.currentTarget.scrollTop);
        }}
        onScroll={(e) => {
         // 未运行
          console.log("react event bubble", e.currentTarget.scrollTop);
        }}
        style={{
          overflow: "auto",
          width: 200,
          height: 200,
        }}
      >
        <div
          style={{
            height: 10000,
            padding: 5,
            background: "#777",
          }}
        />
      </div>
  );
};

```

#### 独立访问子应用
原生事件和合成事件表现均正常：
<img width="670" alt="image" src="https://user-images.githubusercontent.com/23360556/189385987-2dcbe656-ef79-4b9e-840e-6a6f0ab5d08b.png">

#### 微应用形式访问
只有原生事件生效了，且执行了两次..?
<img width="652" alt="image" src="https://user-images.githubusercontent.com/23360556/189386099-7fd2e5f3-784d-4a5a-9407-0f1506ecd53e.png">

两种事件应该是不会有冲突的，测试了一下似乎只有滚动事件有这种问题...

**Comment by yiludege** [comment]
目前确实有这个问题，建议给定无界容器固定高度，然后html、body设置100%高度，这样滚动就在body上而不是容器上

**Comment by Mmear** [comment]
> 目前确实有这个问题，建议给定无界容器固定高度，然后html、body设置100%高度，这样滚动就在body上而不是容器上

<img width="481" alt="image" src="https://user-images.githubusercontent.com/23360556/189565917-520efb11-266d-4006-9de2-6e650213e6df.png">
不知道您说的无界容器是不是指 webcomponent 的父节点，我尝试了一下并没有生效。这个问题在子应用的任何子组件中的滚动容器上都会发生，目前看来是因为 react 把 scroll 监听绑定到了主应用（或者是 iframe）的 document 上导致的。所以不太理解你说的`滚动在 body 上而不在容器上` 是指什么意思，望赐教。谢谢~

**Comment by yiludege** [comment]
我的，刚没有看清楚问题，确实这个地方是框架的问题，我修改过来吧
<img width="599" alt="image" src="https://user-images.githubusercontent.com/19788268/189569183-73bc498d-785f-49da-a125-a0b610e63efd.png">
修改之后正常了
<img width="707" alt="image" src="https://user-images.githubusercontent.com/19788268/189569261-8752d7b6-33cc-4c20-a4f9-62b4a4744eb9.png">

**Comment by yiludege** [comment]
已发版
