### ISSUE TITLE
当react子应用路由为hash模式时报错，页面不显示

### ISSUE THREAD

**Issue by cyh5kf** [Tencent/wujie#151]
在官方examples中，主应用为main-react，子应用为react17，当把子应用react17中的路由改为hash路由时，页面报错，不显示，其他代码都没有动

**如何复现**
将此处的BrowserRouter改为HashRouter
![0f0e1fa44af99d1f02a644393222495](https://user-images.githubusercontent.com/12553354/190139581-739960e2-daa0-419d-897d-21543878a913.jpg)

**错误截图**
![e49136c7fc33b72969d1c63fee58749](https://user-images.githubusercontent.com/12553354/190139725-d3276b47-ae8d-46f4-9858-2498e4f201b6.jpg)

**最小复现仓库或者地址**
官方代码examples中的例子

**Comment by yiludege** [comment]
我在这里总结了一下我怎么查找这个问题，以及怎么解决这个问题的：

首先看到 Blocked a frame with origin xxx 这样的报错我就怀疑是子应用的 iframe 沙箱被擦除了
1、看一下iframe，果然如此，iframe已经变成了一个页面了：
<img alt="image" src="https://user-images.githubusercontent.com/19788268/190838974-0873ea50-46f2-4461-890b-b81506190266.png" width="600">
2、iframe沙箱被擦除原因很多，可能是请求 iframe 的 src 的时候被重定向或者子应用代码有让 iframe 沙箱跳转到其他地址
3、看网络请求，看是哪个代码让 iframe 重新跳转
<img src="https://user-images.githubusercontent.com/19788268/190839103-bb691619-2209-4597-9869-8a41c95551ca.png" alt="drawing" width="600"/>
4、发现是 replaceHashPath 这个函数
<img  alt="image" src="https://user-images.githubusercontent.com/19788268/190839219-75ea1427-e02b-422c-842a-7542927dd846.png" width="600"/>
5、这个函数具体如下：可以看到调用了location.replace，并且把路径补齐，而就是这个路径补齐出现了问题，window.location 是无界劫持的 proxyLocation ，其 location.href 返回的是子应用的 host，而 iframe 的 src 的 host 是 主应用的 host，这样就相当于 window.location.replace 了一个其他域名的地址导致 iframe 被重新刷走了
```javascript
function replaceHashPath(path) {
  window.location.replace(stripHash(window.location.href) + '#' + path);
}
```
6、解决办法：
将无界的 proxyLocation 的 replace 劫持并且将子应用的 host 重新替换为主应用的 host
```javascript
if (propKey === "replace") {
  return new Proxy(location[propKey], {
    apply(replace, _ctx, args) {
      return replace.call(location, args[0]?.replace(appHostPath, mainHostPath));
    },
  });
}
```
