### ISSUE TITLE
vue3项目作为主应用，子应用引入arco-design组件，下拉框位置样式异常

### ISSUE THREAD

**Issue by Sunrise1970** [Tencent/wujie#153]
您好：
        无界嵌入arco下拉组件展示异常，偏移的位置刚好是主应用菜单栏的宽度。尝试了相关issues里面的方案也无法解决，帮忙排查一下问题，谢谢~
        
        嵌入前：
             
![image](https://user-images.githubusercontent.com/15205625/190559615-11da1e63-7fab-4cee-907f-e5bad1d73c77.png)
![image](https://user-images.githubusercontent.com/15205625/190559693-89a80493-daee-42bc-8eb3-794b50acef28.png)

       嵌入后：
![image](https://user-images.githubusercontent.com/15205625/190559675-54b96375-e175-4937-9f1e-8fb32dbdc0b0.png)
![image](https://user-images.githubusercontent.com/15205625/190559724-a409273a-83c6-49d1-ac74-313abb3b30b5.png)

       复现仓库：https://github.com/Sunrise1970/wujie-arco-demo.git

**Comment by Sunrise1970** [comment]
目前的做法是，主应用嵌入的子应用容器占全屏，然后子应用padding-left菜单宽度，可规避位置异常问题：

![image](https://user-images.githubusercontent.com/15205625/190606543-810f059a-848f-48b7-a8b6-70e7c6069f1f.png)
![image](https://user-images.githubusercontent.com/15205625/190606584-51943ec2-d489-4609-b479-9a6fa4cd0903.png)

**Comment by Sunrise1970** [comment]
我尝试了一下京东的micro，字节框架的下拉组件样式是没问题的，官方可以参考一下他们是怎么搞的

https://github.com/Sunrise1970/micro-arco-demo.git

**Comment by yiludege** [comment]
由于采用iframe + webcomponent，导致没办法参考，有个比较诡异的做法可以参考一下？https://github.com/Tencent/wujie/issues/123#issuecomment-1249585548

**Comment by Sunrise1970** [comment]
> 

我也是这么搞的

**Comment by yiludege** [comment]
可以解决问题吗

**Comment by TheYuuu** [comment]
> 目前的做法是，主应用嵌入的子应用容器占全屏，然后子应用padding-left菜单宽度，可规避位置异常问题：
> 
> ![image](https://user-images.githubusercontent.com/15205625/190606543-810f059a-848f-48b7-a8b6-70e7c6069f1f.png) ![image](https://user-images.githubusercontent.com/15205625/190606584-51943ec2-d489-4609-b479-9a6fa4cd0903.png)

 这样会导致position为absolute的定位偏移，根本原因还是因为模拟的根节点返回的位置信息要不要偏移修正，但是在微前端这一层无法知道此次的计算路径是absolute还是fixed
