### ISSUE TITLE
子应用带query参数的路由链接点击后query丢失

### ISSUE THREAD

**Issue by cnetinfo** [Tencent/wujie#154]
**描述bug**
子应用带query参数的路由链接点击后query丢失
**如何复现**
home里面 < router-link to="/location?id=123">location</router-link >点击后 ?id=123丢失

**Comment by yiludege** [comment]
我自己这边刚试了一下没有这个问题
1、子应用的location跳转添加一个查询参数
![image](https://user-images.githubusercontent.com/19788268/190836630-41c5a3f1-17e5-4405-85bd-9dc5be25d1c4.png)
点击子应用location 后这个查询参数还是存在的
![image](https://user-images.githubusercontent.com/19788268/190836607-fa0398fe-f3b4-44f8-85f6-fd9b4e413f15.png)

所以能否提供一个复现的demo呢？可能是我理解错了你的意思

**Comment by cnetinfo** [comment]
![image](https://user-images.githubusercontent.com/10990539/190838763-affdea90-5f34-4df3-8649-8d5381696990.png)

我是在vite home.vue里面加了个router-link to="/location?id=123"

**Comment by cnetinfo** [comment]
> 我自己这边刚试了一下没有这个问题 1、子应用的location跳转添加一个查询参数 ![image](https://user-images.githubusercontent.com/19788268/190836630-41c5a3f1-17e5-4405-85bd-9dc5be25d1c4.png) 点击子应用location 后这个查询参数还是存在的 ![image](https://user-images.githubusercontent.com/19788268/190836607-fa0398fe-f3b4-44f8-85f6-fd9b4e413f15.png)
> 
> 所以能否提供一个复现的demo呢？可能是我理解错了你的意思

我是在vite home.vue里面加了个router-link to="/location?id=123"

**Comment by yiludege** [comment]
明白你的意思了，这个地方大部分人搞不明白的点是：

1、子应用的包括查询参数都是在 iframe 里面跑的，和外面的主应用的没有任何关系（不像乾坤、micro-app那样是基于路由匹配），你可以发现无界无需做任何路由适配的工作

2、如果子应用需要和主应用的查询参数保持一致，那么就需要双向的绑定，子应用的查询参数变化了，需要通过通信的方式告诉主应用让主应用带上，主应用查询参数变化了需要通过 子应用的 url 同步给子应用

3、本来主、子应用的路由是解耦的，但是上面的步骤相当于是将主、子应用进行耦合

**Comment by cnetinfo** [comment]
> 



> 



> 明白你的意思了，这个地方大部分人搞不明白的点是：
> 
> 1、子应用的包括查询参数都是在 iframe 里面跑的，和外面的主应用的没有任何关系（不像乾坤、micro-app那样是基于路由匹配），你可以发现无界无需做任何路由适配的工作
> 
> 2、如果子应用需要和主应用的查询参数保持一致，那么就需要双向的绑定，子应用的查询参数变化了，需要通过通信的方式告诉主应用让主应用带上，主应用查询参数变化了需要通过 子应用的 url 同步给子应用
> 
> 3、本来主、子应用的路由是解耦的，但是上面的步骤相当于是将主、子应用进行耦合

目前有的很多子应用都是通过携带的query参数去做接口请求的查询。"通过通信的方式告诉主应用让主应用带上" 这样页面就会执行两遍，或者是直接用通信方式改变原有子应用的跳转方式，但是这样改动成本太大
