### ISSUE TITLE
打开新tab页路径内容不正确

### ISSUE THREAD

**Issue by lyanmm** [Tencent/wujie#167]
**描述bug**
使用 target='_blank' 的方式打开新页面，新页面路径和内容都不对

**如何复现**
给出详细的复现步骤
截图为子应用，主、子应用都是react-router 6
![image](https://user-images.githubusercontent.com/54403240/191701750-e6ebbffd-52af-49b2-a2f9-f5c865101b94.png)
1、2两种方式都不可用，3可以。

**最小复现仓库或者地址**
https://github.com/lyanmm/wujie-demo

想问下这种打开子应用新tab页面的链接要怎么写比较好。
虽然这种写死的方式可行，但着实不优雅，而且改造旧项目的时候很麻烦。

**Comment by yiludege** [comment]
我看了一下demo，总算是知道你是啥意思了，这个问题没有很好的办法的，主要的原因是主应用和子应用的路由是解耦的，其他微前端应该没有这个问题

因为他们的路由是耦合的，也就是共用一套路由体系，但是无界这边子应用的路由运行在 iframe 内部，和外部路由没有任何关系
