### ISSUE TITLE
主应用和子应用都是 vite, 子应用无法正常切换

### ISSUE THREAD

**Issue by matteao03** [Tencent/wujie#168]
## 前言
一个主应用 main，两个子应用 app1 , app2 。主应用和子应用都是 vue3 项目， 通过 vite 打包。
## 问题
子应用无法正常切换
## 复现步骤
- 访问主应用： http://127.0.0.1:5173/ ， 页面上有四个路由： app1,  app2, home, about 。 其中 home ,about 为主应用路由；
- 点击 app1 路由, 可以正常切换 app1 子应用， app1 应用内路由切换也正常；
-  点击 app2 路由，无法正常切换 app2 子应用。 反之， 刷新浏览器，先点击 app2 路由，可以正常访问 app2 子应用, 但是又无法正常访问 app1 子应用；
- 点击 home 路由或者 about 路由，可以正常切换；

## 最小复现仓库：
[wujie-demo-vite3](https://github.com/matteao03/wujie-demo-vite3)

**Comment by yiludege** [comment]
不同子应用直接 name 需要唯一
