### ISSUE TITLE
直接调的window.addEventListener('click', this.onClick, false)，捕获的target异常

### ISSUE THREAD

**Issue by s-boaz** [Tencent/wujie#169]
![c1ad280b25a0cf8b190cade9a1015ab](https://user-images.githubusercontent.com/34855763/191891984-d15cc0eb-6258-45c5-b177-a71180418970.png)

引用driver.js依赖
https://github.com/kamranahmedse/driver.js/blob/master/src/index.js

**Comment by yiludege** [comment]
试着用了好多种方法没有办法在框架层面解决这个问题，这个问题是由于 shadow 引起的原生问题，所以目前只能用代码替换来解决：

1、 如果是第三方库，没有办法只能通过 js-loader 来进行代码替换，将 e.target 替换成 (e.target.shadowRoot && e.composed) ? (e.composedPath()[0] || e.target) : e.target

2、如果是自己的代码，直接写成 (e.target.shadowRoot && e.composed) ? (e.composedPath()[0] || e.target) : e.target 就好了

**Comment by magnnus** [comment]
e.composedPath() 为 空[], 而 e.target 仍为 wujie-app，需要怎么处理呢？

**Comment by wopelo** [comment]
我也遇到了相同的问题，表现是在子应用中点击日期选择器，发现弹不出选择框。查看组件源码发现是通过 window.addEventListener 的方式监听点击事件，并通过 event.targer 判断收起还是展开选择框，但在 shadow dom 下不能拿到正确的target。感觉这种方式还是比较常见的监听点击事件的方式。
我这边的解决方案是使用 jsBeforeLoaders 劫持子应用的 window.addEventListener：
```
function proxyAddEventListenerFactory(windowObj: Window) {
  const rawAddEventListener = windowObj.addEventListener

  function proxyAddEventListener<K extends keyof WindowEventMap>(
    type: K,
    rawListener: (this: Window, ev: WindowEventMap[K]) => any,
    options?: boolean | AddEventListenerOptions,
  ): void {
    const listener = (e: WindowEventMap[K]) => {
      const target = e.target as HTMLElement & { shadowRoot: ShadowRoot }
      const realTarget = (target.shadowRoot && e.composed) ? (e.composedPath()[0] || target) : target
      // 因为 e.target 是只读属性，只能构造一个新的对象代替 Event 对象
      const event: any = {}

      for (let key in e) {
        event[key] = e[key]
      }
      event.target = realTarget  // 将 target 指向正确的节点
      // 防止后续使用 stopPropagation、preventDefault 报错
      event.stopPropagation = () => e.stopPropagation()
      event.preventDefault = () => e.preventDefault()
      event.rawEvent = e

      rawListener.call(windowObj, event)
    }

    rawAddEventListener(type, listener, options)
  }

  return proxyAddEventListener
}

// 主应用加载子应用
export default function LoadApp({
  const plugins = [{ 
    jsBeforeLoaders: [{
      callback(appWindow: Window) {
        appWindow.addEventListener = proxyAddEventListenerFactory(appWindow)
      }
    }]
  }]
  
  return <WujieReact
    name={name}
    url={url}
    plugins={plugins}
  />
})
```
我这边采用上面的方案之后组件展示就正常了，而且主应用的 addEventListener 不受影响。

**Comment by makai1027** [comment]
> e.composedPath() 为空[]，而e.target仍为wujie-app，需要怎么处理呢？

你是不是本地开发环境调试的
