### ISSUE TITLE
Angular 主应用不支持么？

### ISSUE THREAD

**Issue by lanmingle** [Tencent/wujie#170]
PS：Angular 作为主应用呢？

**Comment by yiludege** [comment]
还没有验证，你可以试试呢，应该没啥问题

**Comment by lanmingle** [comment]
没有教程啊？还有 api 文档。

测试可以使用函数：destroyApp, setupApp, preloadApp, startApp 丢进 EL 容器中。

在 Ng 中添加一个按钮触发调用 destroyApp 销毁，html 没有销毁，iframe 这些销毁了。

另外自定义 webcomponent 是什么？（在startApp看到是wujie-app标签，其内部的属性呢？）

文档不足啊！！！

**Comment by yiludege** [comment]
destroyApp 没有销毁 html 确实是一个问题，但是 destroyApp, setupApp, preloadApp, startApp 这些 api 都非常简单而且文档很详尽了啊
