### ISSUE TITLE
vue3 + vite 在setup里面监听子应用事件会累加触发

### ISSUE THREAD

**Issue by icoller** [Tencent/wujie#178]
主应用setup语法糖写监听子应用事件 `bus.$on("click", (msg) => window.alert(msg)) ` ，在切换路由再进入应用页面，所有的事件就会增加一次触发。

**如何复现**
1、第一步：访问应用页面
2、 第二步：切换到其他页面
3、第三步：再次进入应用页面，点击子页面上的@click

**错误截图**

![76453A83-91A3-4528-ADB6-D3DA267372A8](https://user-images.githubusercontent.com/19677896/192079381-75676ace-a069-438a-bf8b-721670fb9bcc.png)

**Comment by yiludege** [comment]
<img width="746" alt="image" src="https://user-images.githubusercontent.com/19788268/192430534-11078193-93a1-41ee-885b-5e74a25f8e87.png">
