### ISSUE TITLE
功能建议：过滤元素和忽略元素？

### ISSUE THREAD

**Issue by lanmingle** [Tencent/wujie#183]
参考地址：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=exclude%e8%bf%87%e6%bb%a4%e5%85%83%e7%b4%a0

当子应用不需要加载某个js或css，可以通过在link、script、style设置exclude属性，当遇到带有exclude属性的元素会进行删除。

当link、script、style元素具有ignore属性，不会处理它，元素将原封不动进行渲染。

其它：
目前我同事反馈，样式隔离有点小毛病（vue2或vue3，ul:element 不同版本下），不知道有验证没有。

**Comment by yiludege** [comment]
[js-exclueds](https://wujie-micro.github.io/doc/guide/plugin.html#js-excludes)和[js-ignores](https://wujie-micro.github.io/doc/guide/plugin.html#js-excludes) 满足你的需求吗

**Comment by lanmingle** [comment]
没有注意！！！

**Comment by Tannnnnnnks** [comment]
> [js-exclueds](https://wujie-micro.github.io/doc/guide/plugin.html#js-excludes)和[js-ignores](https://wujie-micro.github.io/doc/guide/plugin.html#js-excludes) 满足你的需求吗

但是子应用每次需要忽略时  都需要通知主应用开发去加上再部署，特别麻烦， 还是期望提供个类似microApp的方式由子应用自行控制。 @yiludege
