### ISSUE TITLE
Angular14 子应用的懒加载路由在主应用加载失败

### ISSUE THREAD

**Issue by Koondik** [Tencent/wujie#184]
**描述bug**
主应用及子应用框架都为Angular14, 子应用使用loadChildren实现其路由懒加载，生成的dialogs.js在主应用无法正确执行（子应用单独运行却正常）。系统报："vendor.js:28968 ERROR Error: Uncaught (in promise): ChunkLoadError: Loading chunk dialogs failed.
(missing: http://localhost:4201/ngSubApp/dialogs.js)" 错误。

**如何复现**
给出详细的复现步骤
1、进入主、子应用执行pnpm i 安装依赖
2、主、子应用分别执行 pnpm run start 启动应用
3、访问主应用链接：http://localhost:4200/ 
4、点击页面头部dialogs的子应用路由，便看到错误提示

**错误截图**
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/24414651/192313192-c0a24c3d-5df7-48b2-a527-8423a267cd29.png">

**最小复现仓库或者地址**
[DEMO仓库地址](https://gitee.com/koondik/wujieMircoApp.git)

**Comment by yiludege** [comment]
问题描述：
1、在调试这个demo的时候发现，js 文件还没有开始加载而 load 事件就已经触发了
2、看了一下 js 脚本为 module 类型，对于 module 类型脚本框架会采用原生的 script 标签来加载
3、框架对异步脚本加载默认会手动触发 load 事件导致 load 事件提前触发

解决：
只有对于外联转内联的脚本才需要手动触发 load 事件，其他都不应该触发该事件
