### ISSUE TITLE
has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

### ISSUE THREAD

**Issue by rongrongt** [Tencent/wujie#187]
**Access to XMLHttpRequest at 'http://172.16.86.71:9529/dst-apis/sso/auth?sysCode=1&source=1' from origin 'http://172.16.86.71:9528' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.**
403 Forbidden
主应该是webpack+vu2， 子应用也是vue2+webpack。子应用单独运行没有问题，但但是放到主应用加载时就报CORS,子应用已经设置headers: {
      'X-Frame-Options': 'SAMEORIGIN',
      'Access-Control-Allow-Credentials': true,
      'Access-Control-Allow-Origin': 'http://172.16.86.71:9528',
      'Access-Control-Allow-Headers': 'X-Requested-With,Content-Type',
      'Access-Control-Allow-Methods': 'PUT,POST,GET,DELETE,OPTIONS',
      'Content-Type': 'application/json; charset=utf-8',
    }
![image](https://user-images.githubusercontent.com/21823510/192422298-64a2fde9-4f89-4b28-9ecd-cb5fb8006466.png)

**Comment by yiludege** [comment]
跨域问题框架无法解决，可以查看一下常见问题

**Comment by pumpkin123** [comment]
我碰到同样的问题。子应用9529的proxy中需要添加配置，
参考：https://segmentfault.com/a/1190000042546656
