### ISSUE TITLE
子应用的百度地图加载后无法正常显示图层，独立运行没有问题

### ISSUE THREAD

**Issue by xu90** [Tencent/wujie#195]
通过Wujie接入子应用后，子应用的百度地图无法正常显示。具体表现为：
1、图层无法正常显示；
2、图层点击脚本异常

能正常搜索地点，且主应用、子应用同域，不存在跨域行为。像是canvas描画异常？

嵌入主应用的异常图示：
![image](https://user-images.githubusercontent.com/28853506/192997095-d0ecb876-d892-46dc-937e-03b9467104fa.png)

子应用独立运行无异常：
![image](https://user-images.githubusercontent.com/28853506/192996960-953641d7-a499-4032-8b29-36e4c21c435d.png)

各位老师，还请看看是否有解决方案。[抱拳][抱拳]

**Comment by yiludege** [comment]
子应用的百度地图怎么嵌入进去的，我需要复现一下这个问题

**Comment by xu90** [comment]
> 感觉是你这个百度地图还有 js 文件加载失败啊，跨域问题？
> 
> 试试用 [js-ignores](https://wujie-micro.github.io/doc/guide/plugin.html#css-ignores)

子应用和主应用是同域的，也设置了 jsIgnores: [/baidu/]

**Comment by yiludege** [comment]
js 文件都没有加载成功的话地图出不来也正常，需要排查一下为什么 js 文件加载不出来

**Comment by yiludege** [comment]
> 有没有一种可是这些异步加载的JS像是作为地图的数据来源（script加载完毕后读取内容），但是嵌入主应用后 JS被转移到iframe处理导致？

嵌入主应用后JS确实是被转移到iframe里面了，在 iframe 里面的成功了应该就OK啊

**Comment by yiludege** [comment]
很想调试一下这个问题，但是又没有环境

**Comment by xu90** [comment]
主要也不太方便提供demo。但是我这边调试了下，在wujie劫持后，确实也会执行script的load方法。

iframe劫持后在执行load，正常获取到script节点，但其父节点获取为null导致。调试的图示：

wujie劫持：
![image](https://user-images.githubusercontent.com/28853506/193168923-37a7798d-6e17-4733-82cf-5d6117099404.png)

执行load（此时获取的parentNode为null）
![image](https://user-images.githubusercontent.com/28853506/193169166-f4e903cc-5f27-4aeb-aa79-42b86ce7ded9.png)

![image](https://user-images.githubusercontent.com/28853506/193168676-a26ddb18-774f-4cdf-b062-a894b03c6903.png)

**Comment by yiludege** [comment]
这个地方已经在 #188 修复了，看看今天能否发版出来

**Comment by xu90** [comment]
更新至rc.20版本，首次打开子应用脚本无异常，但是地图还是无法显示，通过断点定位后看了下，并未正常执行load方法

添加load监听：
![image](https://user-images.githubusercontent.com/28853506/194683625-76052fa5-4713-4c47-9018-6bdbba1af4ca.png)

进入effect.js的rewriteAppendOrInsertChild方法：
![image](https://user-images.githubusercontent.com/28853506/194683646-c69c2228-0a25-44c0-9c9d-d10e44358b74.png)

进入iframe.js的insertScriptToIframe方法，执行append：
![image](https://user-images.githubusercontent.com/28853506/194683714-b35bdaf8-8b74-405f-8bfe-6c9864671f07.png)

但无法进入下图中的load监听方法，导致地图无法正常绘制：
![image](https://user-images.githubusercontent.com/28853506/194683757-a7481927-23d9-4d12-8699-ce4a5d922da5.png)

是否是因load事件添加的对象，与iframe中加载的对象不同，导致load的监听事件无法正常执行？

**Comment by wang8254** [comment]
在考察是否用无界时，正好看到了这个问题，说一下我用micro-app遇到得加载地图得问题，在我使用micro-app时也出现了地图js加载不成功报跨域得问题，解决方式是在主应用中加载地图得相关api，问题得以解决。不知道是否提供了有用得思路，这只是个人见解

**Comment by xu90** [comment]
> 在考察是否用无界时，正好看到了这个问题，说一下我用micro-app遇到得加载地图得问题，在我使用micro-app时也出现了地图js加载不成功报跨域得问题，解决方式是在主应用中加载地图得相关api，问题得以解决。不知道是否提供了有用得思路，这只是个人见解

我的主应用和子应用是同域的，理应不存在跨域问题，目前是加载后未执行绑定的load方法。主应用加载地图相关api的话，在子应用调整地图key，又或者多个子应用接的是不同的地图服务时，老师这边是怎么处理呢？

**Comment by yiludege** [comment]
> 是否是因load事件添加的对象，与iframe中加载的对象不同，导致load的监听事件无法正常执行？

发现确实有 bug，我这边修改一下

**Comment by yiludege** [comment]
已经发版 #87

**Comment by manwuyu** [comment]
@yiludege 这个问题感觉并没有完全解决，
demo: https://github.com/manwuyu/wujieIssues1

**Comment by yiludege** [comment]
已经完全解决，详见：https://github.com/Tencent/wujie/issues/215#issuecomment-1278793078
