### ISSUE TITLE
图标字体会丢失

### ISSUE THREAD

**Issue by erickwang** [Tencent/wujie#198]
保活模式，react 集成，子应用会出现iconfont图标字体丢失，小图标不见了

**Comment by yiludege** [comment]
本地尝试复现，发现并没有这个问题，可以给一下复现的demo

**Comment by erickwang** [comment]
我抽取demo，简化后，只留几个图标，发现没有问题。但是在项目中，就会有问题。偶尔也会有路由不稳定的情况发生

**Comment by erickwang** [comment]
项目上像这样，丢失了图标
[![xuoojK.jpg](https://s1.ax1x.com/2022/09/30/xuoojK.jpg)](https://imgse.com/i/xuoojK)

正常应该这样子的：
[![xuoHBD.jpg](https://s1.ax1x.com/2022/09/30/xuoHBD.jpg)](https://imgse.com/i/xuoHBD)

测试demo，没有丢失，不知道是不是被干扰的原因
[![xuox3t.jpg](https://s1.ax1x.com/2022/09/30/xuox3t.jpg)](https://imgse.com/i/xuox3t)

**Comment by yiludege** [comment]
后续如果能够有复现demo的话再打开这个issue
