### ISSUE TITLE
第一个issues

### ISSUE THREAD

**Issue by lostcc** [Tencent/wujie#2]
话说，生产环境效果怎么样，有没什么坑啊

**Comment by zihao-web** [comment]
亲身使用，效果还不错， 就是跨域问题有点麻烦，需要子应用开放 CORS 配置就可以了

> 话说，生产环境效果怎么样，有没什么坑啊

**Comment by yiludege** [comment]
> 话说，生产环境效果怎么样，有没什么坑啊

目前无界微前端方案在腾讯内部有20+项目生产环境落地，所以大部分可能存在的问题都已经扫过了，可以在正式环境使用
