### ISSUE TITLE
官方实例 每当子应用跳转页面  子应用先卸载 然后再渲染 再跳转页面 再卸载 再渲染  如果子应用很大 渲染会不会很慢？

### ISSUE THREAD

**Issue by zh1011** [Tencent/wujie#203]
![image](https://user-images.githubusercontent.com/41102878/193440712-86a3b58c-e893-4ac9-9478-2f414c230c6d.png)

https://user-images.githubusercontent.com/41102878/193440802-bfeac02d-f683-42fc-b877-2707f9074ebe.mp4

上面是第一个问题

如果把computed改为data
![image](https://user-images.githubusercontent.com/41102878/193440816-22f7c51e-7917-403d-aa5a-012a70aa6acd.png)
这样只会渲染一次   但是刷新会丢失子应用的路由记录 会返回子应用的首页

https://user-images.githubusercontent.com/41102878/193440892-53b7d1f8-2f6a-4354-812e-3c8bb1612322.mp4

上面是第二个问题

![image](https://user-images.githubusercontent.com/41102878/193440906-bb273c71-fa27-4e32-acda-6d085d3f5108.png)
![image](https://user-images.githubusercontent.com/41102878/193440922-2c594fd4-38dd-479f-b76e-2a380ebc829e.png)
第二个视频 可以看到我加了sync 刷新之后同样会返回子应用的首页

**Comment by yiludege** [comment]
不会的，子应用所有的js文件已经在第一次全部解析运行完毕了，每次重新渲染都只是当前页面的渲染，不管子应用多大，都非常快

**Comment by fyye314** [comment]
但是重复加载也会有问题，比如vue组件的mounted会执行两次，如果在其中发送请求的话也会发送两次。
