### ISSUE TITLE
无界集成 MonacoEditor 后，鼠标点击选择不了行。单独运行子应用正常

### ISSUE THREAD

**Issue by erickwang** [Tencent/wujie#205]
用无界集成一个子应用，用到了MonacoEditor。
 子应用正常，但是无界加载之后，就出现问题了。
 一个是跨域的worker问题，我已经解决了。
另外一个，就是鼠标点击定位无效了。我抽出了一个脱离业务的demo，可以重现问题
demo在这里：
```
https://github.com/erickwang/wujie-monaco-demo
```

**Comment by yiludege** [comment]
这个问题已经查明是 MonacoEditor 的 document.caretRangeFromPoint 在无界中无法兼容

MonacoEditor 其实已经考虑到了 shadowRoot 的情况，但是 MonacoEditor 和 无界没有兼容的地方在于 MonacoEditor 认为shadowRoot 一定在 document.body 内部，而无界子应用 document.body 在 shadowRoot 内部导致 MonacoEditor 认为编辑器不在 shadowRoot内

<img width="372" alt="image" src="https://user-images.githubusercontent.com/19788268/194741261-0dc5df34-a734-4f96-91a5-bf3c3a98e5a0.png">
<img width="676" alt="image" src="https://user-images.githubusercontent.com/19788268/194741274-6494ee29-dd90-43a2-9781-cd022a8b2a95.png">

**Comment by yiludege** [comment]
采用 js-loader 可以解决这个问题
```javascript
plugins: [
  {
    jsLoader: (code) =>
      code.replace(
        "function getShadowRoot(domNode) {",
        "function getShadowRoot(domNode) {if(window.__POWERED_BY_WUJIE__) return window.__WUJIE.shadowRoot;"
      ),
  },
],
```

目前采用这种方案后，鼠标指针的位置计算的又不是很准确，主要是这个 offset 

<img width="584" alt="image" src="https://user-images.githubusercontent.com/19788268/194744482-26e8c7bc-89f9-41e9-845c-35bf570e199d.png">

**Comment by zhuxinping** [comment]
> https://github.com/erickwang/wujie-monaco-demo

请问你这个编辑器脚本跨域是如何处理的呢？我也遇到了

**Comment by water5656** [comment]
同问跨域问题，求解

**Comment by alvin0804** [comment]
monaco-editor@0.44.0 版本这块的源代码被更改过了，所以需要降低版本 monaco-editor@0.34.0 才能正常使用这个方案解决bug

**Comment by 1441412556** [comment]
> 采用 js-loader 可以解决这个问题（线上如果被代码压缩了需要自行查找压缩后的代码进行替换）采用 js-loader 可以解决这个问题（线上如果被代码压缩了需要自行查找压缩后的代码进行替换）
> 
> 采用 js-loader 可以解决这个问题（线上如果被代码压缩了需要自行查找压缩后的代码进行替换）
> 
> ```js
> plugins: [
>   {
>     jsLoader: (code) =>
>       code
>         .replace(
>           "function getShadowRoot(domNode) {",
>           "function getShadowRoot(domNode) {if(window.__POWERED_BY_WUJIE__) return window.__WUJIE.shadowRoot;"
>         )
>         .replace(
>           "const font = window.getComputedStyle(el, null).getPropertyValue('font');",
>           "const font = window.getComputedStyle(el, null).fontSize + ' ' + window.getComputedStyle(el, null).fontFamily"
>         ),
>   },
> ],
> ```
> 
> 第一个代码替换是为了解决 MonacoEditor 的 在无界 shadow 场景下不兼容的问题第一个代码替换是为了解决 MonacoEditor 的 在无界 shadow 场景下不兼容的问题
> 
> 第一个代码替换是为了解决 MonacoEditor 的 在无界 shadow 场景下不兼容的问题
> 
> 第二个代码替换是为了解决鼠标指针的位置计算不准确的问题：第二个代码替换是为了解决鼠标指针的位置计算不准确的问题：
> 
> 第二个代码替换是为了解决鼠标指针的位置计算不准确的问题：
> 
> <img alt="image" width="584" src="https://user-images.githubusercontent.com/19788268/194744482-26e8c7bc-89f9-41e9-845c-35bf570e199d.png">

这个加上后并没有打印出getShadowRoot函数，导致主应用还是不能编辑
![image](https://github.com/Tencent/wujie/assets/41174701/bd98e5fc-4d14-49f9-98a2-e858b9406002)
还有什么解决方法吗？

**Comment by alvin0804** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xiaobai-men** [comment]
> Reference in new issu

那高版本monaco除了降低版本外，有别的解决方案吗，在现在最新的monaco代码里没有找到获取point的位置

**Comment by alvin0804** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xiaobai-men** [comment]
> monaco-editor@0.44.0 版本这块的源代码被更改过了，所以需要降低版本 monaco-editor@0.34.0 才能正常使用这个方案解决bug

那现在对于最新的monaco除了降低版本外还有别的解决方案吗，尝试找了下现在获取point的位置，没有找到相关的

**Comment by yaolunmao** [comment]
> 同问跨域问题，求解

跨域应该worker文件吧，在子应用里面用cdn引用worker文件就可以了

**Comment by yaolunmao** [comment]
> > 采用 js-loader 可以解决这个问题（线上如果被代码压缩了需要自行查找压缩后的代码进行替换）采用 js-loader 可以解决这个问题（线上如果被代码压缩了需要自行查找压缩后的代码进行替换）
> > 采用 js-loader 可以解决这个问题（线上如果被代码压缩了需要自行查找压缩后的代码进行替换）
> > ```js
> > plugins: [
> >   {
> >     jsLoader: (code) =>
> >       code
> >         .replace(
> >           "function getShadowRoot(domNode) {",
> >           "function getShadowRoot(domNode) {if(window.__POWERED_BY_WUJIE__) return window.__WUJIE.shadowRoot;"
> >         )
> >         .replace(
> >           "const font = window.getComputedStyle(el, null).getPropertyValue('font');",
> >           "const font = window.getComputedStyle(el, null).fontSize + ' ' + window.getComputedStyle(el, null).fontFamily"
> >         ),
> >   },
> > ],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 第一个代码替换是为了解决 MonacoEditor 的 在无界 shadow 场景下不兼容的问题第一个代码替换是为了解决 MonacoEditor 的 在无界 shadow 场景下不兼容的问题
> > 第一个代码替换是为了解决 MonacoEditor 的 在无界 shadow 场景下不兼容的问题
> > 第二个代码替换是为了解决鼠标指针的位置计算不准确的问题：第二个代码替换是为了解决鼠标指针的位置计算不准确的问题：
> > 第二个代码替换是为了解决鼠标指针的位置计算不准确的问题：
> > <img alt="image" width="584" src="https://user-images.githubusercontent.com/19788268/194744482-26e8c7bc-89f9-41e9-845c-35bf570e199d.png">
> 
> 这个加上后并没有打印出getShadowRoot函数，导致主应用还是不能编辑 ![image](https://private-user-images.githubusercontent.com/41174701/293006673-bd98e5fc-4d14-49f9-98a2-e858b9406002.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTcyNzksIm5iZiI6MTcxMzc1Njk3OSwicGF0aCI6Ii80MTE3NDcwMS8yOTMwMDY2NzMtYmQ5OGU1ZmMtNGQxNC00OWY5LTk4YTItZTg1OGI5NDA2MDAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDAzMzYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNWZmOTQwYTJkNDYwZmM5MDhhMjE0OTc5NmQ2NDM1MzU3OGM0OTNkYzU4ZWQ5Y2ExMDA0M2IwZGRkMjA1ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CZv0XMZuQAam6lS20T-YISj7YP_aJ03Bag4yC9V8rFw) 还有什么解决方法吗？

我的code打印出来的也是空的 请问您最后如何解决的

**Comment by unitsung** [comment]
> > monaco-editor@0.44.0 版本这块的源代码被更改过了，所以需要降低版本 monaco-editor@0.34.0 才能正常使用这个方案解决bug
> 
> 那现在对于最新的monaco除了降低版本外还有别的解决方案吗，尝试找了下现在获取point的位置，没有找到相关的

monaco-editor@0.47.0 只替换这里就可以了！！！
![image](https://github.com/user-attachments/assets/c3d6a753-2331-418a-a78d-4dafbbd002ba)

**Comment by alvin0804** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by mafx1024** [comment]
版本：monaco-editor: "0.50.0"
- 解决无法选中问题
- 解决控制台报错
主应用：
```jsx
import {InstanceofPlugin } from 'wujie-polyfill';
<WujieReact
        plugins={[
          /**
           * Node: 解决Monaco-editor无法选中文本问题
           */
          InstanceofPlugin({ patchList: ['Node'] }),
        ]}
/>
```
子应用：
```javascript
const fs = require('node:fs');
const path = require('node:path');

// 兼容 monaco-editor 无法在wujie中使用的问题
// issues https://github.com/Tencent/wujie/issues/205
const domPath = path.resolve('./', 'node_modules/monaco-editor/esm/vs/base/browser/dom.js');

let dom = fs.readFileSync(domPath, 'utf-8');

dom = dom.replace(
  `function getShadowRoot(domNode) {`,
  `function getShadowRoot(domNode) {
    if(window.__POWERED_BY_WUJIE__) return window.__WUJIE.shadowRoot;`,
);

fs.writeFileSync(domPath, dom);

const mouseTargetPath = path.resolve(
  './',
  'node_modules/monaco-editor/esm/vs/editor/browser/controller/mouseTarget.js',
);

let mouseTarget = fs.readFileSync(mouseTargetPath, 'utf-8');

mouseTarget = mouseTarget.replace(
  'range.setStart(el.firstChild, offset)',
  'if(!el.firstChild)return;range.setStart(el.firstChild, offset)',
);

fs.writeFileSync(mouseTargetPath, mouseTarget);
```

**Comment by alvin0804** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by kris-oo** [comment]
请教大佬们，这个跨域问题怎么解决的呀

![Image](https://github.com/user-attachments/assets/1f602629-b48b-4e7f-bc4d-bcf936ef7b2d)

**Comment by bambooShow** [comment]
> 采用 js-loader 可以解决这个问题（线上如果被代码压缩了需要自行查找压缩后的代码进行替换）
> 
> plugins: [
>   {
>     jsLoader: (code) =>
>       code
>         .replace(
>           "function getShadowRoot(domNode) {",
>           "function getShadowRoot(domNode) {if(window.__POWERED_BY_WUJIE__) return window.__WUJIE.shadowRoot;"
>         )
>         .replace(
>           "const font = window.getComputedStyle(el, null).getPropertyValue('font');",
>           "const font = window.getComputedStyle(el, null).fontSize + ' ' + window.getComputedStyle(el, null).fontFamily"
>         ),
>   },
> ],
> 第一个代码替换是为了解决 MonacoEditor 的 在无界 shadow 场景下不兼容的问题
> 
> 第二个代码替换是为了解决鼠标指针的位置计算不准确的问题：
> 
> <img alt="image" width="584" src="https://user-images.githubusercontent.com/19788268/194744482-26e8c7bc-89f9-41e9-845c-35bf570e199d.png">

重写 document.caretRangeFromPoint，使用 shadowRoot.elementFromPoint 模拟其行为
/**
 * 文本测量工具 - 复用 Canvas 实例
 */
const textMeasurer = (() => {
  let canvas: HTMLCanvasElement | null = null;
  let ctx: CanvasRenderingContext2D | null = null;

  return {
    measure: (text: string, font: string): number => {
      if (!canvas) {
        canvas = document.createElement('canvas');
        ctx = canvas.getContext('2d');
      }
      if (!ctx) return 0;
      ctx.font = font;
      return ctx.measureText(text).width;
    },
  };
})();

/**
 * 计算点击位置对应的文本偏移量（二分查找）
 */
const calcTextOffset = (text: string, font: string, relativeX: number): number => {
  if (text.length === 0 || relativeX <= 0) return 0;

  let left = 0;
  let right = text.length;

  while (left < right) {
    const mid = Math.floor((left + right) / 2);
    const width = textMeasurer.measure(text.substring(0, mid + 1), font);
    if (width < relativeX) {
      left = mid + 1;
    } else {
      right = mid;
    }
  }

  return left;
};

/**
 * 查找元素内的文本节点（向下遍历）
 */
const findTextContainer = (el: HTMLElement | null): HTMLElement | null => {
  while (el && el.firstChild && el.firstChild.nodeType !== Node.TEXT_NODE) {
    el = el.lastChild as HTMLElement;
  }
  return el;
};

/**
 * 创建 wujie shadowRoot 兼容的 caretRangeFromPoint 实现
 */
const createCaretRangeFromPoint = (
  wujie: { shadowRoot?: ShadowRoot },
  iframeWindow: Window
): ((x: number, y: number) => Range | null) => (x: number, y: number): Range | null => {
  // 懒加载获取 shadowRoot（windowPropertyOverride 执行时可能还未初始化）
  const shadowRoot = wujie.shadowRoot;
  if (!shadowRoot) return null;

  const el = findTextContainer(
    shadowRoot.elementFromPoint(x, y) as HTMLElement | null
  );
  if (!el) return null;

  const range = iframeWindow.document.createRange();

  if (el.firstChild?.nodeType === Node.TEXT_NODE) {
    const textNode = el.firstChild;
    const text = textNode.textContent || '';
    const rect = el.getBoundingClientRect();
    const style = iframeWindow.getComputedStyle(el);
    const font = `${style.fontSize} ${style.fontFamily}`;
    const offset = calcTextOffset(text, font, x - rect.left);

    range.setStart(textNode, Math.min(offset, text.length));
    range.setEnd(textNode, Math.min(offset, text.length));
  } else {
    range.setStart(el, 0);
    range.setEnd(el, 0);
  }

  return range;
};

// 在 windowPropertyOverride 中使用
windowPropertyOverride: (iframeWindow: Window) => {
  const wujie = (iframeWindow as unknown as { __WUJIE?: { shadowRoot?: ShadowRoot } }).__WUJIE;
  
  if (wujie) {
    Object.defineProperty(iframeWindow.document, 'caretRangeFromPoint', {
      value: createCaretRangeFromPoint(wujie, iframeWindow),
      configurable: true,
      writable: true,
    });
  }
}

**Comment by alvin0804** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
