### ISSUE TITLE
子应用使用了react-contextmenu类型的第三方包  无法正确监控鼠标事件

### ISSUE THREAD

**Issue by s861085151** [Tencent/wujie#206]
![image](https://user-images.githubusercontent.com/48351939/194692629-25ee47ed-9361-483e-b466-0842ce12f8e5.png)

**Comment by yiludege** [comment]
1、子应用 window 除了路由和加载相关的事件监听的是 iframe 沙箱的其他事件全部劫持到 主应用的 window 来监听
2、由于子应用的运行在 shadowRoot 当中，导致了主应用 wiindow 监听的 e.target 被浏览器重写为 wujie-app
3、这个地方可以采用 js-loader 通过代码替换的方式，将 handleShowEvent、handleHideEvent 的 e.target 替换为 (e.target.shadowRoot && e.composed) ? (e.composedPath()[0] || e.target) : e.target
