### ISSUE TITLE
element tooltip 位置偏移

### ISSUE THREAD

**Issue by SericXu** [Tencent/wujie#212]
如图，初步检查发现这个tooltip采用的是固定定位。何解🤣
![image](https://user-images.githubusercontent.com/50159079/195236470-a6b6083a-e250-4920-a0a4-09397ab37484.png)

![image](https://user-images.githubusercontent.com/50159079/195236681-cef405ff-4455-4fce-8324-fc876bf63517.png)

**Comment by quqingfei** [comment]
https://github.com/Tencent/wujie/pull/214#issuecomment-1277226699
新版本已经解决了。
已经发布 appendOrInsertElementHook
采用这个 plugin

**Comment by yiludege** [comment]
解决这个问题的关键就是将 tooltip 的定位采用 absolute 定位 而非 fixed 定位

popperjs 有 strategy 字段可以配置的，但是大部分框架没有开放或者将这个字段写死成 fixed

所以 ，解决方案是可以通过代码替换的方式，改变 tooltiop 的定位方式， 看看这个[解决方案](https://github.com/Tencent/wujie/issues/228#issuecomment-1282274977)
