### ISSUE TITLE
关于子应用重新初始化的问题

### ISSUE THREAD

**Issue by SericXu** [Tencent/wujie#213]
遇到这样一个场景：
> **保活模式**
主子应用公用一个登录验证方法，在子应用中通过props跳转到主应用登录页面后，随便点击一个子应用的菜单进入子应用，子应用会停留在跳转登录前的状态，比如弹框之类的还在打开状态，且与点击的菜单内容并未对应。

经过判断应该是需要应用卸载和重新装载，但是照着文档使用destoryApp后，没实现重新装载。请问怎么实现？

**Comment by xinlei3166** [comment]
mark

**Comment by huanghe621123** [comment]
我也是想重载子应用，但是没有找到方法，兄弟解决了吗

**Comment by huanghe621123** [comment]
我现在遇到了一个问题，我的子应用内部location.href改变了，结果把无界的标签给刷没了，就剩一个iframe了，我看了下源码，改子应用location.href的时候会被无界代理proxy方法劫持，执行他的set方法，清空了当前的无界标签和影子dom，重新挂载了一个iframe上去。
我只是想在url改变后重新加载这个子应用，有没有实现的方法

**Comment by huanghe621123** [comment]
> 我在想是不是加一个refreshApp，这样方便大家来重载子应用

感觉需要用到重载子应用的场景还是蛮多的

**Comment by yiludege** [comment]
> 我现在遇到了一个问题，我的子应用内部location.href改变了，结果把无界的标签给刷没了，就剩一个iframe了，我看了下源码，改子应用location.href的时候会被无界代理proxy方法劫持，执行他的set方法，清空了当前的无界标签和影子dom，重新挂载了一个iframe上去。 我只是想在url改变后重新加载这个子应用，有没有实现的方法

这个是预期行为，在子应用了面 location.href = xxx 是一个无法实现的能力，所以无界这边直接新开了一个iframe给到用户使用，如果此时浏览器点击返回，还可以返回之前的子应用状态

**Comment by huanghe621123** [comment]
> > 我现在遇到了一个问题，我的子应用内部location.href改变了，结果把无界的标签给刷没了，就剩一个iframe了，我看了下源码，改子应用location.href的时候会被无界代理proxy方法劫持，执行他的set方法，清空了当前的无界标签和影子dom，重新挂载了一个iframe上去。 我只是想在url改变后重新加载这个子应用，有没有实现的方法
> 
> 这个是预期行为，在子应用了面 location.href = xxx 是一个无法实现的能力，所以无界这边直接新开了一个iframe给到用户使用，如果此时浏览器点击返回，还可以返回之前的子应用状态

所以说目前无法在当前子应用里重载一个新的url的资源是吗，而且新开iframe后还会把子应用的url挂到主应用后面

**Comment by hengyanqwe** [comment]
我也有类似的需求

**Comment by hengyanqwe** [comment]
> 我现在遇到了一个问题，我的子应用内部location.href改变了，结果把无界的标签给刷没了，就剩一个iframe了，我看了下源码，改子应用location.href的时候会被无界代理proxy方法劫持，执行他的set方法，清空了当前的无界标签和影子dom，重新挂载了一个iframe上去。 我只是想在url改变后重新加载这个子应用，有没有实现的方法

我也是

**Comment by yiludege** [comment]
不是无界不能实现，而是微前端目前不可能实现这样的能力，你可以看看其他微前端方案呢
