### ISSUE TITLE
子应用加载百度地图js 只有部分功能，加载百度地图css 不成功

### ISSUE THREAD

**Issue by manwuyu** [Tencent/wujie#215]
**描述bug**
子应用加载三方js 只有部分功能，加载三方css 不成功

**如何复现**
给出详细的复现步骤
直接运行demo

**错误截图**
主应用有问题，比如地图无法拖拽 显示不正确
![image](https://user-images.githubusercontent.com/6800546/195269043-ad748787-64bc-4e67-87b7-761727f82f5a.png)
子应用都是好的
![image](https://user-images.githubusercontent.com/6800546/195269253-9f0837d0-88c5-4bc3-988d-4f79b2fa3add.png)

**最小复现仓库或者地址**
https://github.com/manwuyu/wujieIssues1

**Comment by manwuyu** [comment]
关于跨域加载资源的已经解决
但bmapgl 依旧报错 功能异常
bmapv3 报错  但功能目前是好的

**Comment by yiludege** [comment]
1、将 wujie 更新到 1.0.0-rc.23
2、设置一下 plugins 就可以了
```javascript
plugins={[{
  appendOrInsertElementHook(_element, _iframeWindow, rawElement) {
    if(rawElement)
    Object.defineProperty(rawElement, "parentNode", { get: () => ({ removeChild: () => null }) });
  },
}]}
```

<img width="1714" alt="image" src="https://user-images.githubusercontent.com/19788268/195821261-eaf00956-6d43-469d-91b9-ea5f2b91e005.png">
