### ISSUE TITLE
Uncaught TypeError: Illegal invocation

### ISSUE THREAD

**Issue by bulesky123** [Tencent/wujie#219]
**描述bug**
门户是一个用乾坤来做微前端，子应用（用wujie来当基座，里面嵌入子应用）
**如何复现**
给出详细的复现步骤
![image](https://user-images.githubusercontent.com/16065485/195787258-40300156-28d4-45cf-bcf2-bf9061320529.png)

**错误截图**
![image](https://user-images.githubusercontent.com/16065485/195787150-fabe2248-3db1-454a-8007-165d60080751.png)

**最小复现仓库或者地址**
项目结构：

父--->子--->孙

父-->子 ：采用的是乾坤方式（这个不是我们负责的）
我们负责的是   子-->孙  

猜测：是不是乾坤里面与wujie里面都对window对象做了代理，有冲突之类的
ps: 单独单开是可以正常访问，当接入到乾坤里面后报错

**Comment by yiludege** [comment]
目前不支持 微前端 互相嵌套，因为每个微前端都对 window 做了很多副作用，没办法做到兼顾的
