### ISSUE TITLE
bugs: 路径错误时解析URL报错

### ISSUE THREAD

**Issue by liRemons** [Tencent/wujie#22]
### 文件路径：wujie-core/utils.ts
函数体：fixElementCtrSrcOrHref
代码：new URL(value,  this.baseURL || '')   
当 value 不是合法的URL时，会报错，阻塞继续渲染
建议增加容错

示例：将子应用的url 设为 http://remons.cn/@website_pages/my

**Comment by yiludege** [comment]
确实代码容错这块做的不够，不过这个地方value为非法URL值和子应用的url应该没有关系吧

**Comment by liRemons** [comment]
> 

是的，value和子应用URL没有关系，这里只是举个例子
