### ISSUE TITLE
子应用项目是用rem单位实现的布局，必须给主应用的html标签设置fontSize才行，能不能只对当前子应用的html标签设置fontSize

### ISSUE THREAD

**Issue by expanding** [Tencent/wujie#222]

**Comment by yiludege** [comment]
这个地方子应用的dom还是挂载在 主应用上，所以rem最终读取的是主应用的 html，暂时没有办法

**Comment by shr1998vip** [comment]
我之前老项目使用了postcss-px2rem这个插件, 单位就是使用的rem, 然后使用wujie集成的话, 子项目布局会乱, 后来我自己写了一个postcss-px-to-vwvh这个插件, 可以解决这个问题, 不知道有没有帮助
