### ISSUE TITLE
开启路由同步时，切换子应用的tab（路由变化），刷新后，点击后退按钮，路由不变页面内容也不变

### ISSUE THREAD

**Issue by expanding** [Tencent/wujie#223]
![image](https://user-images.githubusercontent.com/26728915/196079230-7c394646-f7a3-4d7e-8c2d-0e36a89e7e82.png)

**Comment by yiludege** [comment]
刷新页面，history堆栈都清空了，前进后退必然没办法生效哦

**Comment by yiludege** [comment]
我的理解错误，history堆栈不会清空。

子应用运行在 iframe 内部，子应用发生跳转的时候即 iframe 跳转路由的时候会在浏览器里面添加一条记录，注意这条记录是和iframe 严格绑定的，当发生刷新后原来的 iframe 被销毁子应用渲染的时候又新建了一个 iframe，此时点击回退的话浏览器只会将上一条记录里面的 iframe 回退，但是那个 iframe 已经销毁了，所以没有办法回退了
