### ISSUE TITLE
vue3子应用element-plus的el-table的悬浮提示错位，求解！

### ISSUE THREAD

**Issue by ZhyThomas** [Tencent/wujie#228]
**描述bug**
vue3子应用element-plus的el-table的悬浮提示错位，求解！

**如何复现**
给出详细的复现步骤
1、给vue3子应用包裹margin和padding
2、添加appendOrInsertElementHook的plugins
3、 打开el-table的悬浮提示

**错误截图**
![image](https://user-images.githubusercontent.com/29219116/196362685-76fffb23-ab36-4da9-b741-a8d1d76c4ad8.png)

![image](https://user-images.githubusercontent.com/29219116/196362273-e520b25c-4772-42d4-9ce7-4012ca2d127e.png)
![image](https://user-images.githubusercontent.com/29219116/196362357-67860f5d-7c39-4974-bb27-1e2f93d7f167.png)

![image](https://user-images.githubusercontent.com/29219116/196361624-3ad71829-5656-4e7b-ae0b-bdff6ff12b58.png)

**最小复现仓库或者地址**
https://github.com/ZhyThomas/wujieTest

**Comment by yiludege** [comment]
这个 plugin 没办法发挥作用，因为这个 tooltip 没有插入在 body 内

**Comment by yiludege** [comment]
通过另外一个 plugin 可以解决这个问题（生产代码压缩后可能需要重新找出压缩代码来替换）：
```javascript
plugins: [
  {
    jsLoader: (code) => {
      return code.replace('strategy: \\"fixed\\"', 'strategy: \\"absolute\\"');
    },
  },
],
```
具体原理：
element-plus 里面将这个 popper 的 strategy 写死了 fixed
![image](https://user-images.githubusercontent.com/19788268/196423294-9f6bd078-5620-432e-9bb4-04bef7948eb2.png)

我们需要采用 strategy 为 absolute 定位即可，最终效果：

![image](https://user-images.githubusercontent.com/19788268/196423618-d967f6d8-b591-472b-9c71-eb643c36a8a9.png)

也可以采用[这个方案](https://github.com/Tencent/wujie/issues/205#issuecomment-1273160357)来做代码替换

**Comment by ZhyThomas** [comment]
收到，亲测有效，感谢！

**Comment by gaolongge** [comment]
> 收到，亲测有效，感谢！

遇到同样的问题，tooltip 插入了 body 内，appendOrInsertElementHook 这个 plugin还是无法发挥作用，能看看你的解决方案吗

**Comment by zlwaiwjj** [comment]
加了同样的plugin 无法解决

**Comment by NewNameArk** [comment]
加了同样的plugin 无法解决
