### ISSUE TITLE
如何加载包含customElements的子应用

### ISSUE THREAD

**Issue by 670010378** [Tencent/wujie#230]
**描述bug**
主应用加载包含customElements的子应用，customElements元素未正常渲染

**如何复现**
给出详细的复现步骤
见最小复现仓库或者地址示例

**错误截图**
**子应用可以正常加载customElements：**
<img width="961" alt="image" src="https://user-images.githubusercontent.com/38980140/196622062-8c2a6163-7390-4e6b-b355-d5efac9566fe.png">

**主应用未正常加载子应用的customElements：**
<img width="846" alt="image" src="https://user-images.githubusercontent.com/38980140/196622454-f84ab59b-cc44-42a7-b316-111f28b06477.png">

**最小复现仓库或者地址**
https://github.com/670010378/wujie-custom-elements-test

**Comment by yiludege** [comment]
这个地方问题确实存在，子应用的 dom 最终是插入到 主应用 的 dom 中，相当于子应用的 dom 其实是主应用的 dom 一部分

在子应用中定义 customElements 相当于在子应用沙箱 iframe 中定义，这个无法作用到主应用的 dom 上

如果在主应用的 js 定义了这个 customElements 那么这个自定义元素可以正常渲染出来

**Comment by zhoukekestar** [comment]
确实存在这个问题，对于一些不太复杂的场景，可以对老的 customElements 做替换处理来正确渲染。
可以参考：https://gist.github.com/zhoukekestar/21788dc4dda81832e91ba34421e69426
