### ISSUE TITLE
嵌套的子应用图片无法加载

### ISSUE THREAD

**Issue by AlexandreJw** [Tencent/wujie#231]
描述bug
官方mian-vue的在线例子：https://wujie-micro.github.io/demo-main-vue/home
A子应用中嵌套B子应用 刷新浏览器 B子应用的图片路径变成A子应用的路径

如何复现

1. 点击react16此菜单 
2. 点击内嵌tab 
3. 查看被嵌套的react17应用logo路径
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/27912478/196900703-62c11ed2-27ac-4a62-b800-86539b11592c.png">

**一旦此错误产生 单独打开react17的子应用，logo就会保持这个错误的路径，只能在react17的子应用的路径下刷新才会重新加载正确的图片**

各个子应用之间有共同的组件（在这个例子中相当于B子应用），此场景非常重要，希望能得到解决

**Comment by yiludege** [comment]
已经发版修复，demo也更新了
