### ISSUE TITLE
开启同步URL的时候，提供自定义函数

### ISSUE THREAD

**Issue by jardenliu** [Tencent/wujie#234]
提个建议，开启同步URL的时候，是否可以提供自定义函数，让开发者可以自己实现想要的同步逻辑，而不是只是提供替换  把长链接变成短一点？

**Comment by yiludege** [comment]
这个地方确实不太好做开放，比较容易出现问题，可以选择路由耦合的方案，demo中下拉的那些菜单都采用了耦合路由的方式
