### ISSUE TITLE
啥是保活，保活是什么意思

### ISSUE THREAD

**Issue by WayYOLO** [Tencent/wujie#24]
![image](https://user-images.githubusercontent.com/14833363/182540680-39c0ceaa-2a7b-411d-9887-936ce1459bc0.png)
引入报这错，有人遇到吗
Uncaught DOMException: Blocked a frame with origin "http://localhost:8001" from accessing a cross-origin frame.

**Comment by yiludege** [comment]
保活的意思是相当于子应用级别的keep-alive，切换走了子应用实例不销毁，切回来子应用state和路由都保持不变

这个报错能提供一下主应用和子应用的地址以及接入的代码吗

**Comment by afeiship** [comment]
@WayYOLO 这个是主应用与子应用的 domain cors 问题
