### ISSUE TITLE
官方示例，react17-sub，home切换到dialog，再切回来，多次操作后直接浏览器卡死

### ISSUE THREAD

**Issue by longyinczy** [Tencent/wujie#240]
**描述bug**
清晰准确的描述bug

**如何复现**
给出详细的复现步骤
1、第一步 xxx
2、 第二步 xxx

**错误截图**
如果有可以将截图带上

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by huangshihu1992** [comment]
同问，从任意一个保活的子应用的state实例页，修改数字后，再切换到其他子应用的state实例页，来回几次浏览器就卡死了

**Comment by izjing** [comment]
按照标题操作百分百复现

**Comment by yiludege** [comment]
写 demo  react hook 的疏忽导致重复emit，已经修改完毕
