### ISSUE TITLE
中文乱码问题，无界无法解析gbk编码的页面

### ISSUE THREAD

**Issue by 595202868** [Tencent/wujie#242]
**描述bug**
当引入的网站编码为GBK时，entry.ts中fetch加载出来的中文为乱码。

**如何复现**
给出详细的复现步骤
1、第一步 
无界引入一个编码为GBK的网页
2、 第二步 
fetch中加载发现网页中文乱码，fetch解析方法为response.text() 无法解析GBK编码，您看能否加个自定义编码的接口，比如：
```
fetch(url).then(
  (response) => res.arrayBuffer(),
  (e) => {
   loadError?.(url, e);
   return Promise.reject(e);
 }
).then((res)=>{
  html = new TextDecoder("GBK").decode(res)//编码改成可配置
})
```

**错误截图**
![image](https://user-images.githubusercontent.com/23697890/198450712-1f06ace8-ba36-4f5b-8101-66f5b29498a3.png)
**请求位置截图**
![image](https://user-images.githubusercontent.com/23697890/198450096-b84942e2-cc93-47e5-9f5c-6b619a73dc7f.png)
**GBK网站例子**
[test1.zip](https://github.com/Tencent/wujie/files/9884505/test1.zip)

**Comment by yiludege** [comment]
这个地方自定义 fetch 可以做到，当发现为 html 的 url 时

自定义 fetch  先解码 html 好然后返回一个 response 对象，text方法返回 html
