### ISSUE TITLE
常见问题6里面的，把相对地址替换为绝对地址，具体是怎么替换

### ISSUE THREAD

**Issue by ldd-winter** [Tencent/wujie#25]
解决方案： 使用插件中的[css-loader](https://wujie-micro.github.io/doc/guide/plugin.html#css-loader)在运行时将相对地址代码替换成绝对地址, 这个具体替换的代码demo有吗？

**Comment by ldd-winter** [comment]
谢谢

**Comment by TheShining** [comment]
我 "wujie-vue3": "^1.0.16" 还是有这个问题， 
子应用代码：background-image: url('@/assets/images/user.jpg'); 
或者 background-image: url('../../../../assets/images/user1.jpg'); 都不行
子应用baseUrl: http://localhost:5178
最终会链接到主应用端口 5173
http://localhost:5173/src/assets/images/user.jpg

**Comment by TheShining** [comment]
> 举个例子： cssLoader: (code, url) => { return code.replace('./images/my-image.png', 'https://localhost:8000//images/my-image.png') } 可以用正则匹配去做到更加通用

这个我也试了，但是code里面没有我的代码，我的css代码写在vue3单页面文件<style lang="scss" scoped>标签里面

**Comment by ChanHaiWei** [comment]
> 我 "wujie-vue3": "^1.0.16" 还是有这个问题， 子应用代码：background-image: url('@/assets/images/user.jpg'); 或者 background-image: url('../../../../assets/images/user1.jpg'); 都不行 子应用baseUrl: http://localhost:5178 最终会链接到主应用端口 5173 http://localhost:5173/src/assets/images/user.jpg

我使用的react，background-image是写在Style.module.css文件里的，通过cssLoader也是找不到
