### ISSUE TITLE
vue2  : "webpack": "^3.6.0", 设置了headers *,依然报跨域问题，请问怎么解决？

### ISSUE THREAD

**Issue by skyLoveSnap** [Tencent/wujie#253]
![image](https://user-images.githubusercontent.com/40157361/200750510-9f9c6f71-7a27-44c6-b9aa-542a659f1737.png)
<img width="721" alt="image" src="https://user-images.githubusercontent.com/40157361/200751054-0bb45208-9205-4891-9d33-d3a704d4c10d.png">

**Comment by yiludege** [comment]
跨域问题需要用户自行解决
