### ISSUE TITLE
不兼容 sweetalert2

### ISSUE THREAD

**Issue by cloydlau** [Tencent/wujie#264]
**描述bug**
使用 [sweetalert2](https://github.com/sweetalert2/sweetalert2) 报错: `TypeError: Cannot set properties of undefined (setting 'oninput')`
sweetalert2 的用户规模还是很大的，还是值得兼容的

**如何复现**
在子应用使用最基本的 `Swal.fire` 就可以复现

**错误截图**
![image](https://user-images.githubusercontent.com/31238760/202339619-685269ac-a7b7-40d9-8c24-678c2e42490b.png)

**最小复现仓库或者地址**
https://github.com/cloydlau/wujie-sweetalert2

**Comment by jardenliu** [comment]
这个问题应该是跟这个我发现的问题点 https://github.com/Tencent/wujie/issues/256 是一致的。

SweetAlert初始化的时候也是使用了innerHTML来实现的
https://github.com/sweetalert2/sweetalert2/blob/b3c867651023e1499e41e01a7599dde210662948/src/utils/dom/init.js#L144

在获取子节点的时候使用的getDirectChildByClass方法
```ts
/**
 * Get direct child of an element by class name
 *
 * @param {HTMLElement} elem
 * @param {string} className
 * @returns {HTMLElement | undefined}
 */
export const getDirectChildByClass = (elem, className) => {
  const children = Array.from(elem.children)
  for (let i = 0; i < children.length; i++) {
    const child = children[i]
    if (child instanceof HTMLElement && hasClass(child, className)) {
      return child
    }
  }
}
```

`child instanceof HTMLElement ` 为 `false` 导致了没有query到child节点，在调用oninput方法时候，节点为空，控制台报错

**Comment by cloydlau** [comment]
@jardenliu 感谢，https://github.com/Tencent/wujie/issues/256 中的代码可以临时解决这个问题。
