### ISSUE TITLE
单例模式下，iconfont symbol引用svg第一次会展示，主应用切换菜单后第二次svg会消失

### ISSUE THREAD

**Issue by sunc0323** [Tencent/wujie#268]
代码附件：
[svg-demo.zip](https://github.com/Tencent/wujie/files/10055300/svg-demo.zip)
目前看第二次打开没有给body内部的最顶上添加一个svg元素
![image](https://user-images.githubusercontent.com/23629147/203018768-db475710-1933-4fd8-b834-609ee26939b8.png)
![image](https://user-images.githubusercontent.com/23629147/203018956-4b48d6c6-28eb-4fec-b4a8-8b330a3f1696.png)

**Comment by sunc0323** [comment]
试了一下，单例模式在main.js里往body下添加dom都会切换菜单都会被清除

**Comment by evemike** [comment]
我也遇到这个问题了！

**Comment by yiludege** [comment]
这个问题看是否可以这样，一般是单例模式才会出现这个问题

在 afterMount 生命周期的时候，将这个 svg 保存在一个变量上

在beforeMount 生命周期的时候，将这个svg 重新插入到子应用上

这样应该可以的

**Comment by doumaimusics** [comment]
你这里说的是哪个插件啊？？？？
![image](https://user-images.githubusercontent.com/20314064/236424638-e0365dc4-7e81-44ac-b2b3-c6e86e65a11b.png)
