### ISSUE TITLE
在chrome 85以下版本，子应用执行window.window报错

### ISSUE THREAD

**Issue by jardenliu** [Tencent/wujie#280]
**描述bug**
在Chrome 85以及以下版本中，子应用执行 `window.window`报错。

**如何复现**
给出详细的复现步骤
1、打开Chrome 85以及以下版本浏览器
2、  打开无界在线预览页面 https://wujie-micro.github.io/doc/wujie/
3、打开控制台执行 `window[0].__WUJIE.proxy.window` 约等于 子应用执行`window.window`

**错误截图**
<img width="744" alt="image" src="https://user-images.githubusercontent.com/15191056/203515619-216c5388-bf1f-425c-8f88-43d05669efa0.png">

**最小复现仓库或者地址**
https://wujie-micro.github.io/doc/wujie/

**Comment by jardenliu** [comment]
#### 原因分析

无界的子应用运行环境使用Proxy对原有的window进行代理，`window.window`会触发Proxy下面的代码 L57
https://github.com/Tencent/wujie/blob/9d657ee98470089071c2e906848c7476105343c9/packages/wujie-core/src/proxy.ts#L49-L74

通过判断self和window会返回 `target.__WUJIE.proxy`，来实现proxyWindow的返回

此时会触发Proxy的handler.get()的约束机制
 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/get#invariants

#### **85版本之前**
window的PropertyDescriptor
<img width="752" alt="image" src="https://user-images.githubusercontent.com/15191056/203517613-f1c15964-4672-4bde-a3d6-434e1a1f875c.png">

configurable 和 writable 为false，会触发约束无法正确返回 `target.__WUJIE.proxy`

#### ***85版本之后*
window的PropertyDescriptor

<img width="788" alt="image" src="https://user-images.githubusercontent.com/15191056/203518030-0b8c94db-3aef-4500-a68f-726400710a2a.png">

此时获取方式变成了getter，不会触发约束，正常返回

**Comment by Emmally** [comment]
请问该问题是否可解？

**Comment by yiludege** [comment]
暂时可以用这个插件来操作一波 https://wujie-polyfill.github.io/doc/plugins/windowGetter.html
