### ISSUE TITLE
子应用使用element-plus会报警告

### ISSUE THREAD

**Issue by wu-zhi-yuan** [Tencent/wujie#294]
**描述bug**
element-plus组件的事件在编译时会抛出警告

**错误截图**

![F8MOM35T`L4MW8RWPDPQ0GX](https://user-images.githubusercontent.com/79829985/204691923-255519c6-67ab-4fb0-8504-372706c4c22a.png)

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by wu-zhi-yuan** [comment]
子应用中类似使用element的输入框， 按钮等， 所有鼠标事件都会抛出警告

**Comment by Freedom555** [comment]
你好，请问这个问题是如何解决的呢？

**Comment by water5656** [comment]
+1

**Comment by ycx0303** [comment]
+1

**Comment by DaTongDXM** [comment]
怎么解决的？为啥关闭了
