### ISSUE TITLE
主应用vue2向子应用vue2传递信息 bus.$emit('xxx',{xxx})   事件订阅数量为空

### ISSUE THREAD

**Issue by yayyyy** [Tencent/wujie#297]
**描述bug**
主应用里的A界面  通过按钮 向   子应用X   传递信息 ，但是  点击A界面按钮子应用X并未生效

**错误截图**
![image](https://user-images.githubusercontent.com/38713931/204959335-91ac0ae8-4435-4d18-86e7-d21aeedce5d9.png)
![image](https://user-images.githubusercontent.com/38713931/204959374-773c28bc-6fcc-43e0-b2f2-8c28fcd52566.png)

**Comment by yayyyy** [comment]
![image](https://user-images.githubusercontent.com/38713931/204959894-800ad8d8-0b08-43a6-bc4f-98fbacac3991.png)
![image](https://user-images.githubusercontent.com/38713931/204959930-88dcdacc-647a-4012-a7a7-34aea64d2bea.png)

**Comment by yiludege** [comment]
感觉是子应用还没有渲染？

**Comment by wu-zhi-yuan** [comment]
子应用还没激活， 相当于事件还没注册， 直接触发就触发不了事件

**Comment by yiludege** [comment]
那肯定啊，这个$on事件都没有注册到事件池里面，$emit的时候发现事件池里面没事件，就会报这个告警

**Comment by yayyyy** [comment]
对的，确实是在主应用的入口没有预加载子应用，🙇‍

**Comment by yayyyy** [comment]
是的是的
