### ISSUE TITLE
子应用里调navigator.clipboard.readText，会报错DOMException: Document is not focused

### ISSUE THREAD

**Issue by banchichen** [Tencent/wujie#298]
**描述bug**
使用wujie加载的子应用，无法使用navigator.clipboard.readText访问剪切板，会报错 DOMException: Document is not focused，看起来是因为执行子应用js的iframe不是激活态导致，直接使用iframe或qiankun是可以的，请作者大大帮忙看看可以怎么绕过

**如何复现**
1、启动wujie的demo工程
2、任意选一个字应用，比如wujie/examples/react16，打开src/App.js，在useEffect里加入下面读取剪切板的代码：
```javascript
 navigator.clipboard
      .readText()
      .then((res) => console.log('clipboard.readText success', res))
      .catch((e) => console.error('clipboard.readText error',e));
```
3、控制台报错：DOMException: Document is not focused

**错误截图**
![image](https://user-images.githubusercontent.com/12755494/204980554-311cd8ed-a3b1-44d7-9041-3ffdef83507e.png)

**最小复现仓库或者地址**
wujie自己的仓库即可复现

**Comment by banchichen** [comment]
我这边先这样绕过了：
```javascript
  const navigator = window.__POWERED_BY_WUJIE__ ? window.parent.navigator : window.navigator;
  navigator.clipboard...
```
使用window.parent.navigator可以正常访问clipboard
供大家参考

**Comment by yiludege** [comment]
就像报错所说，确实子应用的 document 没有聚焦，子应用的 iframe沙箱 的 display: none

子应用的 dom 其实是挂载在主应用 shadow 上了，子应用的 iframe沙箱 的对 dom 的操作劫持到 shadow 了

**Comment by yiludege** [comment]
plugins: [
    {
      windowPropertyOverride: (subWindow) =>
        Object.defineProperty(subWindow.Navigator.prototype, "clipboard", {
          get: () => {
            return subWindow.__POWERED_BY_WUJIE__ ? subWindow.parent.navigator.clipboard : subWindow.navigator;
          },
        }),
    },
  ]
