### ISSUE TITLE
如何在本地环境中加载不用域里的子应用呢

### ISSUE THREAD

**Issue by 202780181** [Tencent/wujie#30]
![image](https://user-images.githubusercontent.com/27540653/183017637-9ed26c2f-599e-47ba-b8db-29aa64bd9a58.png)

**Comment by yiludege** [comment]
看看[常见问题](https://wujie-micro.github.io/doc/question/#_1%E3%80%81%E8%AF%B7%E6%B1%82%E8%B5%84%E6%BA%90%E6%8A%A5%E9%94%99)

如果只是想尝试一下的话试试做一下[whistle代理](https://wproxy.org/whistle/)呢
https://boss.greatge.net http://localhost:8000
https://boss.greatge.net/hallv2mb  https://boss.greatge.net/hallv2mb/
