### ISSUE TITLE
建议：增加一个事件，当子应用内部的路由发生变化时主应用能够得到通知

### ISSUE THREAD

**Issue by yn-tadpole** [Tencent/wujie#301]
目前子应用内部路由变化无法通过主应用的watch监测到，建议增加一个事件能够获知子应用的路由有变化

**Comment by yiludege** [comment]
现在就可以通过微前端提供的[全局事件](https://wujie-micro.github.io/doc/guide/communication.html#eventbus-%E9%80%9A%E4%BF%A1)做到，框架本身是无法做到监听子应用路由变化的

**Comment by dreamerblue** [comment]
@yiludege 不可能吧？看起来wujie应该是知道这个事件的，毕竟会同步子应用 url 到主应用的 query。我们也需要这个能力，当发生 url 变化的时候让主应用可以感知。
