### ISSUE TITLE
降级处理后，子应用的文档模式声明<!DOCTYPE html>不见了

### ISSUE THREAD

**Issue by GuoDoubleV** [Tencent/wujie#302]
**描述bug**
降级处理后，通过iframe加载的子应用的文档模式声明<!DOCTYPE html>不见了，导致子应用的文档模式不正确，以至于出现很多文档模式差异导致的bug。

**如何复现**
子应用开启降级处理即可

**Comment by squallliu** [comment]
@xuzhidanxu 我的原补丁中是有这部分内容的，合并后就没了
