### ISSUE TITLE
在多个子应用同时激活的情况下 ，打开页面出现白屏

### ISSUE THREAD

**Issue by Hollelihanqi** [Tencent/wujie#31]

**Comment by Hollelihanqi** [comment]
在多个子应用同时激活的情况下 ，第一次进入打开页面其它子应用加载比较，出现白屏

**Comment by yiludege** [comment]
一个子应用的加载我可以分为三个过程：

1、静态资源的请求下载，2、资源的运行，保活html的解析、js的解析执行，3、子应用的实例mount

其中 过程 1 可以通过 preloadApp 来提前加载，2 和 3 可以通过 preloadApp 的 exec模式来提前执行，但是这个preloadApp是相当于将子应用的加载提前来做

如果子应用从来都没有加载也没有采用preloadApp预加载就会出现白屏的。

如果子应用之前已经加载过了：

- 运行的是保活模式（sync = true），那么子应用重新打开过程1、2、3都不需要，无白屏时间
- 运行的是单例模式（sync = false && 做了生命周期适配），那么子应用会重新进行只会过程3，白屏时间很短
- 运行的是重建模式（sync = false && 没有做生命周期适配），那么子应用重新打开会进行过程2、3，白屏时间较长

**Comment by jk4235** [comment]
可以考虑增加loader,减少焦虑😄

**Comment by yiludege** [comment]
@jk4235  loader 已经全覆盖 html、css、js，用户主动性非常大了
