### ISSUE TITLE
子应用是纯html，请问如何接入呢

### ISSUE THREAD

**Issue by MilkWangStudio** [Tencent/wujie#315]
子应用是多页应用，通过a标签进行跳转，目前直接接入进来时，会发现点击a标签，整个页面全部跳转到了子应用。
请问该如何适配呢？

**Comment by makai1027** [comment]
解决了么 ，就是那种xxx.html的路径，怎么搞的

**Comment by yiludege** [comment]
对于纯 html 页面，不需要做适配，但是对于 a 标签这样的不支持内部调整，新开 tab 跳转吧

**Comment by makai1027** [comment]
我今天试了一下，其实也是可以的，
首先就是利用NGINX将所有的.html删除，实现host/xxx/pageName
`
location / {
            # 防止跨域
          add_header Access-Control-Allow-Origin *;
          add_header Access-Control-Allow-Headers X-Requested-With;
          add_header Access-Control-Allow-Methods GET,POST,OPTIONS;
          root   /xxx/project-website-template;
          index  index.html index.htm;
          # 删除.html后缀
          if ($request_uri ~ ^/(.*)\.html$) {
              return 302 /$1;
          }
          # 重定向
          try_files $uri $uri.html $uri/ =404;
      }
`
代码中
<img width="625" alt="image" src="https://user-images.githubusercontent.com/24761813/207593459-706308f8-0ae7-410f-b7c2-3b4e7786a3c3.png">
子路径我用的空的vue文件挂的component，不然vue-router会报错

不过相对于每一个页面，JQuery还是会加载多次，但是如果有缓存，资源可以从缓存中拿

**Comment by xionglongxiang** [comment]
这个问题有进展吗，我们有旧的应用需要作为子应用。

**Comment by makai1027** [comment]
> 这个问题有进展吗，我们有旧的应用需要作为子应用。

用iframe，工具不支持纯前端

**Comment by xionglongxiang** [comment]
> > 这个问题有进展吗，我们有旧的应用需要作为子应用。
> 
> 用iframe，工具不支持纯前端

也就是说，iframe不能直接接入wujie？
