### ISSUE TITLE
请问有什么办法能在子应用中获取到主应用中的某个DOM节点

### ISSUE THREAD

**Issue by lzs246** [Tencent/wujie#32]
我这边有个特别的场景，需要在子应用中获取到主应用中某个DOM节点

以前项目未采用微前端方案时，是直接通过document.querySelector(xxx)，但是现在接入wujie后，我发现document.querySelector会从shadowRoot中找，这样以前代码就有bug

请问有什么好办法解决吗？
感谢

**Comment by yiludege** [comment]
由于iframe和主应用是同域的，可以直接通过window.parent.document.querySelector(xxx)拿
