### ISSUE TITLE
同个页面下，切换保活应用时，丢失路由信息

### ISSUE THREAD

**Issue by Xusenbiao** [Tencent/wujie#320]
**描述bug**
同个页面下，开启了路由同步模式，切换保活应用时，路由没有显示对应子应用的参数。

**如何复现**
给出详细的复现步骤
1、第一步
在test.vue页面下设置不同的保活应用：
```
<template>
  <div>
    <button @click="switchApp">切换</button>
    <WujieVue width="100%" height="100%" :name="activeName" :url="activUrl" :alive="true" :sync="true"></WujieVue>
  </div>
</template>
  
<script>
export default {
  data() {
    return {
      activUrl: "//localhost:7300/dialog",
      activeName: "vue3",
    };
  },
  methods: {
    switchApp() {
      if (this.activeName === "vue3") {
        this.activeName = "react16"
        this.activUrl = "//localhost:7600"
      } else {
        this.activeName = "vue3"
        this.activUrl = "//localhost:7300/dialog"
      }
    }
  }
};
</script>
```
首次进入路由正常：`http://localhost:8000/test?vue3=%2Fdialog`

2、 第二步
点击切换按钮，切换保活应用。

结果：页面正常显示，但路由的search参数丢失：`http://localhost:8000/test`。

预期：显示目标子应用的search参数：`http://localhost:8000/test?react16=%2Fhome`

**相关说明**
在调试的过程中，发现是在移除`Shadow DOM`这一步之后，路由丢失的：

```
    if (!container.querySelector(`div[${LOADING_DATA_FLAG}]`)) {
      // 清除内容
      clearChild(container);
    }
```

**Comment by yiludege** [comment]
这个问题是这样的，每次 webcomponent 的 disconnectedCallback 生命周期会调用 sandbox.unmount，这这个 unmount 里面会清理一些没有激活的查询参数（clearInactiveAppUrl）这个函数的判断依据是该子应用的 webcomponent 的 host 没有挂载在主应用上则应该清除，这个地方由于 两个子应用都采用同一个 WujieVue，导致新的子应用的渲染会比旧的子应用销毁更快，从而把新的查询参数给清理掉了
