### ISSUE TITLE
请教一下，全局函数有什么好的处理办法吗？

### ISSUE THREAD

**Issue by candy-Tong** [Tencent/wujie#326]
HTML 原生 onclick 这些事件，触发的是全局函数？
而 script 的定义的全局 function，被留在闭包中了。那么 onclick 就会报错。这个有什么好的处理办法吗？

**Comment by JingDeZhe** [comment]
有解决的方式吗，感觉JS对页面的引用没有问题，当反方向就会出问题，找不到函数定义？

**Comment by yiludege** [comment]
全局函数 应该用 window.xxx 来定义

**Comment by JingDeZhe** [comment]
主应用：
``` html
<body>
  <div>Main</div>
  <div id="container"></div>
  <script src="/lib/wujie.js"></script>
  <script>
    wujie.setupApp({
      name: '01',
      url: 'http://localhost:8003/wujie/sub.html',
      el: '#container',
    })
    wujie.startApp({ name: '01' })
  </script>
</body>
```
子应用：
```html
<body>
<div>
  <p>Sub</p>
  <button onclick="alertHello()" id="btn">hello</button>
</div>
<script>
  window.alertHello = function () {
    alert('hello')
  }
</script>
</body>
```

就是这种很单纯的情况，点击时会找不到`alertHello`的定义:
`Uncaught ReferenceError: alertHello is not defined`

**Comment by yiludege** [comment]
明白了，挂在到 proxyWindow上去了，需要挂载到原生window对象可以试试：

window.__WUJIE_RAW_WINDOW__.alertHello = function () {
    alert('hello')
  }

**Comment by JingDeZhe** [comment]
这样并不可以，依旧会找不到定义，我看了一下，点击时的上下文中Window是很普通的原生对象，没有任何patch之类。

**Comment by yiludege** [comment]
查到原因了，子应用的 dom 挂载在主应用的 webcomponet 内部，导致这个 button 点击时的上下文是主应用 window 对象，所以定义在子应用 iframe 内的 window 并没有起作用，如果改成：
```javascript
window.parent.alertHello = function () {
    alert('hello')
  }
```
我这里是验证生效的，但是这样又会污染主应用，所以这个地方会有点难处理了，最好采用 xxx.addEventListener 这样方式才能避免

**Comment by JingDeZhe** [comment]
通过addEventListener的方式的确可以生效，但找不到定义在degrade模式下依旧存在，感觉应该不单纯是webcomponent导致的问题。

**Comment by yiludege** [comment]
degrade模式下，子应用的 dom 不是放进 webcomponent 而是一个 新的 iframe，所以这种场景还是需要采用 addEventListener 来处理，框架也没有办法 将 js iframe 里面定义的全局变量搬到 dom firame里面去

**Comment by JingDeZhe** [comment]
谢谢，感觉改造老版应用的时候这个问题阻碍太大。🥲

**Comment by yiludege** [comment]
是的，这是个挺严重的问题，我之前还没有意识到这个问题

**Comment by JingDeZhe** [comment]
有没有一种可能去增加一个新的模式，将html直接渲染到js sanbox的iframe内部，在这种情况下不分离render与script，虽然感觉就像一个单纯的iframe，但在这种情况下似乎有奇效。🥲

**Comment by JingDeZhe** [comment]
`initRenderIframeAndContainer`的时候复用sanbox.iframe，不新生成iframe。

**Comment by yiludege** [comment]
不可能的，分离render和script就是为了子应用可以挂起，快速切换子应用的时候只移除render部分承载 js 的iframe继续保持在后台，如果都渲染到 iframe，那么iframe势必要放置到对应的dom位置来进行展示，切换的时候又要移走，而iframe节点一旦移动会导致iframe自动刷新进而子应用被销毁掉，这种场景还不如直接采用原生的iframe

**Comment by JingDeZhe** [comment]
唉，我也是这样想的，惆怅。😿

**Comment by yyystation** [comment]
我是这样解决的：
利用wujie提供的plugin插件，在htmlLoader中读取到html文档后，把html中所有的内联script标签中的内容合并在一个script中，并且把标签中所有的函数同时放在主应用的window对象中（新建一个key：dict的字段保存）和子应用自己的对象中：
```js
plugins={[
        {
            htmlLoader: (code) => {
                window.frs = {} //子应用frs
                let template = document.createElement("div")
                template.innerHTML = code
                //对onclick事件进行重写
                const buttons = template.querySelectorAll("button")
                Array.from(buttons).forEach((button) => {
                    if (button.hasAttribute("onclick")) {
                        const onclick_handler = button.getAttribute("onclick")
                        button.setAttribute("onclick", "window.frs." + onclick_handler)
                    }
                })
                //将html中的内联Script合并成一个，将所有的function挂在到windows
                const scripts = template.querySelectorAll("script")
                let all_script_str = ""
                Array.from(scripts).forEach((script) => {
                    const src = script.getAttribute("src");
                    if (!src) {
                        all_script_str += script.innerHTML;
                        script.parentNode.removeChild(script)
                    }
                })
                const pattern = /function([_a-zA-Z0-9\s]+)\(/g
                let result = all_script_str.match(pattern)
                if (!result) {
                    return code
                }
                for (let item of result) {
                    item = item.replace(" ", "").replace("function", "").replace("(", "")
                    if (item) {
                        // 因为onclick事件作用在父应用的window对象中，因此需要把函数挂到父应用上，而一些比如formatter属性读取的是本地函数，同时也要绑定在本地window上
                        all_script_str += `window.parent.frs.${item} = ${item};window.${item} = ${item};`
                    }
                }
                let tmpScript = document.createElement("script")
                tmpScript.innerHTML = all_script_str
                template.append(tmpScript)
                return template.innerHTML
            },
        }
    ]}
```

**Comment by jack-le** [comment]
我测试你这个方法了，好像并没有生效啊

**Comment by jack-le** [comment]
> 我是这样解决的： 利用wujie提供的plugin插件，在htmlLoader中读取到html文档后，把html中所有的内联script标签中的内容合并在一个script中，并且把标签中所有的函数同时放在主应用的window对象中（新建一个key：dict的字段保存）和子应用自己的对象中：
> 
> ```js
> plugins={[
>         {
>             htmlLoader: (code) => {
>                 window.frs = {} //子应用frs
>                 let template = document.createElement("div")
>                 template.innerHTML = code
>                 //对onclick事件进行重写
>                 const buttons = template.querySelectorAll("button")
>                 Array.from(buttons).forEach((button) => {
>                     if (button.hasAttribute("onclick")) {
>                         const onclick_handler = button.getAttribute("onclick")
>                         button.setAttribute("onclick", "window.frs." + onclick_handler)
>                     }
>                 })
>                 //将html中的内联Script合并成一个，将所有的function挂在到windows
>                 const scripts = template.querySelectorAll("script")
>                 let all_script_str = ""
>                 Array.from(scripts).forEach((script) => {
>                     const src = script.getAttribute("src");
>                     if (!src) {
>                         all_script_str += script.innerHTML;
>                         script.parentNode.removeChild(script)
>                     }
>                 })
>                 const pattern = /function([_a-zA-Z0-9\s]+)\(/g
>                 let result = all_script_str.match(pattern)
>                 if (!result) {
>                     return code
>                 }
>                 for (let item of result) {
>                     item = item.replace(" ", "").replace("function", "").replace("(", "")
>                     if (item) {
>                         // 因为onclick事件作用在父应用的window对象中，因此需要把函数挂到父应用上，而一些比如formatter属性读取的是本地函数，同时也要绑定在本地window上
>                         all_script_str += `window.parent.frs.${item} = ${item};window.${item} = ${item};`
>                     }
>                 }
>                 let tmpScript = document.createElement("script")
>                 tmpScript.innerHTML = all_script_str
>                 template.append(tmpScript)
>                 return template.innerHTML
>             },
>         }
>     ]}
> ```
我试了一下你这个方法，好像没有生效啊
