### ISSUE TITLE
无界保活模式下 主应用 跳转 子应用的路由 问题

### ISSUE THREAD

**Issue by lisering** [Tencent/wujie#332]
**描述bug**
主应用：vite + vue3 + vue-router4 端口1000 路由模式 history
子应用：vite + vue3 + vue-router4 端口1000 路由模式 hash

**如何复现**
给出详细的复现步骤
1、第一步 打开主应用
2、 第二步 点击链接 跳转到 子应用路由页面
3、点击子应用链接，来回点击第一个链接 会出现
     http://localhost:1000/mdm?mdm=%2Fsystem%23%2Fundefined
     这个undefined不知道咋回事
4、官网 vue主应用示例 下vue3保活模式，切换到 vue3保活 链接也不跳转

**最小复现仓库或者地址**
[仓库地址：https://github.com/lisering/wujieroute](https://github.com/lisering/wujieroute)
`pnpm i`
`pnpm dev`

**Comment by yiludege** [comment]
将子应用路由监听的代码改一下应该就好了：
 ```javascript
 if(route.params.path) wujieVue.bus.$emit("mdm-router-change", `/${route.params.path}`);
```

**Comment by lisering** [comment]
> 将子应用路由监听的代码改一下应该就好了：
> 
> ```js
> if(route.params.path) wujieVue.bus.$emit("mdm-router-change", `/${route.params.path}`);
> ```

App.vue 原来的代码
`<template>
  <RouterView />
</template>

<script setup lang="ts">
import { onMounted, watch } from "vue";
import { useRoute, useRouter } from "vue-router";

const route = useRoute();
const router = useRouter();

watch(
  () => route,
  (val) => {
    window.$wujie?.bus.$emit("sub-route-change", "mdm", route.path);
  }
);

onMounted(() => {
  window.$wujie?.bus.$on("mdm-router-change", (path: string) => {
    return router.push(path);
  });
});
</script>
`
修改后的代码
`<template>
  <RouterView />
</template>

<script setup lang="ts">
import { onMounted, watch } from "vue";
import { useRoute, useRouter } from "vue-router";

const route = useRoute();
const router = useRouter();

watch(
  () => route,
  (val) => {
    // window.$wujie?.bus.$emit("sub-route-change", "mdm", route.path);
    if (route.params.path) {
      window.$wujie?.bus.$emit("mdm-router-change", `/${route.params.path}`);
    }
  }
);

onMounted(() => {
  window.$wujie?.bus.$on("mdm-router-change", (path: string) => {
    return router.push(path);
  });
});
</script>
`
修改后进入子应用子路由后跳回子应用首页还是回不来子应用首页
