### ISSUE TITLE
[求助] 使用cookie的鉴权方式，如何在主应用内打开子应用

### ISSUE THREAD

**Issue by code-lixm** [Tencent/wujie#335]
**描述bug**
打开的主应中，子应用拿不到cookie, 无法在请求的时候获取到cookie 携带发送正确的请求

**Comment by yiludege** [comment]
子应用和主应用如果不同的域名，肯定拿不到主应用的cookie啊

**Comment by code-lixm** [comment]
> 子应用和主应用如果不同的域名，肯定拿不到主应用的cookie啊

现在是开发环境 如何解决这个问题啊

**Comment by yiludege** [comment]
这个和环境没有关系，跨域问题、登录态问题都不是微前端框架可以解决的问题，需要业务方来处理的

**Comment by code-lixm** [comment]
线上同域就无所谓了，目前来看这种本地开发，在主应用打开子应用（子应用的cookie无法携带上，只能换鉴权的策略），那这样适配成本就高了呀

**Comment by yiludege** [comment]
线上同域，本地开发也可以做到同域啊，用 whistle 代理一下？

**Comment by code-lixm** [comment]
谢谢！我过会试试！

**Comment by code-lixm** [comment]
问题解决了：开发环境在子应用的proxy 中设置header: {cookie: ''} 手动写入cookie。可以解决在开发环境中，主应打开子应用（子应用内部发起请求的问题）

**Comment by youyujianghu** [comment]
> 问题解决了：开发环境在子应用的proxy 中设置header: {cookie: ''} 手动写入cookie。可以解决在开发环境中，主应打开子应用（子应用内部发起请求的问题）

set-cookie是后端返回得你怎么处理，你怎么得到set-cookie里得值
