### ISSUE TITLE
主应用和子应用之间的通信事件无法取消

### ISSUE THREAD

**Issue by Cref-t** [Tencent/wujie#336]
通过eventBus进行主应用与子应用之间的通信
可以正常$on监听和$emit发送，但是$off不起作用

主应用页面进行监听，取消
子应用页面进行emit发送

**Comment by yiludege** [comment]
给个demo，我这边可以正常取消

**Comment by Cref-t** [comment]
> 



> 给个demo，我这边可以正常取消

大概了解到是怎么一回事了，我的callback是单独放在组件里的，每次切换页面，组件重新渲染，上一次监听事件的callback和重新渲染的callback其实已经不是一个函数了，所以无法正常取消，你这边正常取消是放在什么文件中去进行取消操作呢？还是说callback放在window中

**Comment by yiludege** [comment]
![image](https://user-images.githubusercontent.com/19788268/209943475-d1b74936-6b89-411f-aa55-9e8775f740ef.png)
[文档](https://wujie-micro.github.io/doc/api/bus.html#clear)有交代，这个就像 addEventListener 一样，需要手动清除

**Comment by xieanwen** [comment]
这是子应用
![image](https://github.com/Tencent/wujie/assets/24740695/90eaf221-e0d3-44ca-9130-225a7c62f976)
这是主应用
![企业微信截图_16895822225657](https://github.com/Tencent/wujie/assets/24740695/cb4fe945-b7a4-4f79-aa17-247fed3b0633)
每次切换菜单，都会增加一次监听，取消不了

**Comment by youyou12344** [comment]
bus.$off(eventName, fn) 的第二个参数 fn ，
应该等于 bus.$on(eventName, cbFn) 调用时传入的回调函数 cbFn ，不是自定义的函数。
类似 removeEventListener
