### ISSUE TITLE
为什么强制origin是子应用的origin?

### ISSUE THREAD

**Issue by Ives7** [Tencent/wujie#340]
如果可以设置为副应用的话，一些跨域ajax和cookie的问题就可以解决，现在平添了一些麻烦～请问各位大佬有设置子应用请求origin的渠道吗？

**Comment by yiludege** [comment]
不是强制 origin 的问题，目前所有的微前端方案都是 在主应用 将 子应用的静态资源请求回来，然后再将这些资源注入到沙箱去运行，所以静态资源会存在跨域问题，当然无界也提供 jsIgnores 插件来支持 script 原生加载

再说 ajax 请求，无界的沙箱是 iframe，为了通信和 dom 的挂载，必须保证 iframe 的 src 保持和主应用同源，所以在 iframe沙箱 里面发起的 ajax 也会出现跨域的问题，而且这个问题也没有办法避免

综合来说，采用微前端的技术方案，就需要子应用支持跨域请求，支持跨域配置也算不复杂

**Comment by jeffzing** [comment]
为什么我的子应用发起的请求，origin是底座的域名

**Comment by xinlanlan** [comment]
> 不是强制 origin 的问题，目前所有的微前端方案都是 在主应用 将 子应用的静态资源请求回来，然后再将这些资源注入到沙箱去运行，所以静态资源会存在跨域问题，当然无界也提供 jsIgnores 插件来支持 script 原生加载
> 
> 再说 ajax 请求，无界的沙箱是 iframe，为了通信和 dom 的挂载，必须保证 iframe 的 src 保持和主应用同源，所以在 iframe沙箱 里面发起的 ajax 也会出现跨域的问题，而且这个问题也没有办法避免
> 
> 综合来说，采用微前端的技术方案，就需要子应用支持跨域请求，支持跨域配置也算不复杂

配置跨域没有问题，但是现在ajax无法携带cookie，配置credentials: 'include' 只能保证请求静态资源的fetch携带cookie，但是我的子应用的ajax没有携带

**Comment by murrayee** [comment]
> > 不是强制 origin 的问题，目前所有的微前端方案都是 在主应用 将 子应用的静态资源请求回来，然后再将这些资源注入到沙箱去运行，所以静态资源会存在跨域问题，当然无界也提供 jsIgnores 插件来支持 script 原生加载
> > 再说 ajax 请求，无界的沙箱是 iframe，为了通信和 dom 的挂载，必须保证 iframe 的 src 保持和主应用同源，所以在 iframe沙箱 里面发起的 ajax 也会出现跨域的问题，而且这个问题也没有办法避免
> > 综合来说，采用微前端的技术方案，就需要子应用支持跨域请求，支持跨域配置也算不复杂
> 
> 配置跨域没有问题，但是现在ajax无法携带cookie，配置credentials: 'include' 只能保证请求静态资源的fetch携带cookie，但是我的子应用的ajax没有携带

一样的问题 ，请问有解决办法吗

**Comment by yiludege** [comment]
ajax 没有办法代理，也可以设置携带 cookie，设置一下不就可以了吗

**Comment by murrayee** [comment]
> ajax 没有办法代理，也可以设置携带 cookie，设置一下不就可以了吗
主应用加载子应用302链接，这个链接会设置登录cookie，就需要无界fetch加include。然后这个302链接设置请求头位主应用origin。问题这样确实是解决了应用静态资源cores问题，但是应用的请求客户端，请求的时候cookie就拿不到了。实际上放到外部浏览器是有的，请问下，如何解决啊

**Comment by yiludege** [comment]
微前端不是iframe，子应用一旦302就意味着承载子应用的沙箱iframe会跳走到登录页面，这样子应用的iframe沙箱就全部被破坏了成为一个普通的iframe，这个登录态需要额外处理的，保证进入子应用前是登录上了的
