### ISSUE TITLE
子应用设置单例模式，进行生命周期的改造，router可以提前定义好吗？

### ISSUE THREAD

**Issue by Cref-t** [Tencent/wujie#344]
<img width="649" alt="1673250011339" src="https://user-images.githubusercontent.com/40594548/211260106-acb63f4b-590a-4eb6-b260-fce36fa674d8.png">

以上子应用生命周期的改造，我看demo中router都是直接在代码块中定义赋值，可以在router.js文件中定义好，然后直接export出来使用吗？

**Comment by yiludege** [comment]
生命周期改造最好每次都 new 一个路由实例，如果复用的话会在某些高版本路由上有干扰，保留上次的路径
