### ISSUE TITLE
module script的默认执行顺序好像是类似defer的？我测试下来不是和普通script串行的

### ISSUE THREAD

**Issue by liuyang0826** [Tencent/wujie#349]
**描述bug**
我在vite项目中，原本html里面有一段内联的script，现在接到无界之后，脚本的执行顺序和之前有差别导致了问题
参考一下这篇文章的描述
https://hospodarets.com/native-ecmascript-modules-the-first-overview#how-the-browser-loads-and-executes-the-modules

**如何复现**
给出详细的复现步骤
1、第一步 xxx
2、 第二步 xxx

**错误截图**
如果有可以将截图带上

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by yiludege** [comment]
对于非 module 的模块，无界统一将外联请求回来转内联，然后按照顺序插入到 iframe 内执行

对于 type 为 module的模块以及内联模块，无界是直接通过 <script src ='xxxx' type='module'> 这样的方式按照属性插入到 iframe 运行沙箱内的，感觉不应该出现这样的问题

**Comment by liuyang0826** [comment]
![image](https://user-images.githubusercontent.com/30269670/211560611-233840bb-525f-4ddc-aea9-e63b82ff79d0.png)
以上图为例，正常的顺序inline是比module先执行的，但是无界里面会后执行。

**Comment by lucy091** [comment]
> 对于非 module 的模块，无界统一将外联请求回来转内联，然后按照顺序插入到 iframe 内执行
> 
> 对于 type 为 module的模块以及内联模块，无界是直接通过 <script src ='xxxx' type='module'> 这样的方式按照属性插入到 iframe 运行沙箱内的，感觉不应该出现这样的问题

<img width="909" alt="image" src="https://user-images.githubusercontent.com/33422728/210957961-89bb09dd-9b11-4805-b255-493cab417bf0.png">

动态插入的 anync=false的多个脚本，也无法保证脚本的执行，浏览器默认行为是可以保证执行顺序的
