### ISSUE TITLE
子应用百度地图问题，BMap is not defined

### ISSUE THREAD

**Issue by cuteCloud** [Tencent/wujie#357]
**描述bug**
子应用index.html引入了百度地图和依赖于百度地图的插件，主应用报 BMap is not defined

**如何复现**
给出详细的复现步骤
<script
  type="text/javascript"
  src="https://api.map.baidu.com/getscript?v=2.0&&s=1"
></script>

<script type="text/javascript" src="/static/js/bdMap/TextIconOverlay.js"></script>

<script
  type="text/javascript"
  src="https://api.map.baidu.com/library/MarkerClusterer/1.2/src/MarkerClusterer_min.js"
></script>

<script
  type="text/javascript"
  src="https://api.map.baidu.com/library/DrawingManager/1.4/src/DrawingManager_min.js"
></script>
<link rel="stylesheet" href="https://api.map.baidu.com/library/DrawingManager/1.4/src/DrawingManager_min.css" />

<script type="text/javascript" src="https://api.map.baidu.com/library/GeoUtils/1.2/src/GeoUtils_min.js"></script>

**Comment by yiludege** [comment]
需要看看[常见问题](https://wujie-micro.github.io/doc/question/#_2%E3%80%81%E7%AC%AC%E4%B8%89%E6%96%B9%E5%8C%85%E5%B7%B2%E7%BB%8F%E5%BC%95%E5%85%A5%EF%BC%8C%E4%BD%BF%E7%94%A8%E6%97%B6%E6%8A%A5%E9%94%99)
