### ISSUE TITLE
子应用集成

### ISSUE THREAD

**Issue by enjoy-wind** [Tencent/wujie#359]
**描述bug**
一般子应用都有独立的菜单栏和登录逻辑，如何在不侵入子应用的前提下，完成子应用菜单栏隐藏，跳转到子应用的登录页。

**如何复现**
无

**错误截图**
如果有可以将截图带上

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by yiludege** [comment]
可以通过插件写一些样式来隐藏？ https://wujie-micro.github.io/doc/guide/plugin.html#css-before-loaders
