### ISSUE TITLE
setupApp 设置的参数，和 <WujieReact   {...props} /> 是否需要一个规范？

### ISSUE THREAD

**Issue by sauron0914** [Tencent/wujie#362]
现在的情况是，可以通过 setupApp 设置参数，也可以通过  <WujieReact   {...props} /> 设置参数，是否真的需要这样？

**Comment by yiludege** [comment]
setupApp 的考量有两个：

-  <WujieReact {...props} /> 可能出现在多个地方，为了避免相同的props重复书写，可以通过 setupApp 来设置默认参数，props 里面只需要放有差异的属性
- prelaodApp 的属性和 props 基本重复，所以避免重复写的话也可以通过 setupApp 来解决
