### ISSUE TITLE
是否可以同时支持支持单例+保活模式

### ISSUE THREAD

**Issue by enjoy-wind** [Tencent/wujie#365]
在实际的项目中，需要同时支持保活和单例的特性，请问是否支持？或者如何配置

**Comment by yiludege** [comment]
> 需要同时支持保活和单例的特性

具体是哪些特性呢

**Comment by enjoy-wind** [comment]
就是保活和单例的特性呀。
比如我一个主应用，要接一个子应用里面的两个菜单。
当我点击子应用A菜单，然后一顿操作，这个时候我要子应用B菜单才能完成A菜单的操作。
首先我肯定选择了保活模式，但是当我选择保活模式时，A应用的2个菜单不能资源共享，假设我首屏渲染比较慢，当点击B菜单时还会很慢，体验不好

**Comment by yiludege** [comment]
又要保持 A 菜单的内容不丢失，又要 可以切换 A B 菜单，我觉得可以采用保活模式，然后A B 菜单都对应同一个子应用，A菜单路由采用keep-alive，A B 菜单切换采用通信的方式告知子应用

**Comment by enjoy-wind** [comment]
> 
额，这不增加了子应用改造,体验度不降低啦，从无界的框架角度能否增加一种模式，支持此功能.

**Comment by yiludege** [comment]
框架做不到
