### ISSUE TITLE
保活模式下，子应用A 通过 props 和 eventBus 跳转到子应用B指定页面，但是返回到子应用A需要 back 两次

### ISSUE THREAD

**Issue by sauron0914** [Tencent/wujie#368]
**描述bug**

保活模式下，子应用A 通过 props 和 eventBus 跳转到子应用B指定页面，但是返回到子应用A需要 back 两次

**如何复现**

**错误截图**

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by airoy** [comment]
主应用路由$emit后，子应用路由监听$on执行时建立flag禁止 子应用再$emit通知主应用变化；相反子应用路由$emit后，主应用路由监听$on执行时建立flag禁止主应用再$emit通知子应用变化；并且主子应用router.push 改为router.replace
