### ISSUE TITLE
加载A.css资源时，这类语法 @import "./B.css"   无法根据A资源的相对路径去加载

### ISSUE THREAD

**Issue by 499190982** [Tencent/wujie#372]
**描述bug**
如题

**如何复现**
子应用 css资源内包含
<img width="485" alt="image" src="https://user-images.githubusercontent.com/24449830/216258057-2c3075f7-7fd3-4421-81b6-e8cfaca2f430.png">

**错误截图**
错误情况：
<img width="547" alt="image" src="https://user-images.githubusercontent.com/24449830/216258306-f9fec9b4-8417-4fdb-8981-af06d0d80f06.png">
正确情况：
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/24449830/216258469-72e0e885-8a5b-4eee-a093-2bb7f4dbada6.png">

**最小复现仓库或者地址**

**Comment by yiludege** [comment]
可以自行通过plugin来对css内部的相对路径进行修正
