### ISSUE TITLE
加载js时 script标签 被 wujie代码包裹，导致一些dom操作报错

### ISSUE THREAD

**Issue by 499190982** [Tencent/wujie#374]
**描述bug**
如题，一些dom操作无法获取到配置在标签上的属性
**如何复现**
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/24449830/216299245-7218b5a5-4b49-4d3c-87dc-fe3920c00fff.png">

**错误截图**

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by yszhangjl** [comment]
遇到同样的问题

**Comment by 499190982** [comment]
> 遇到同样的问题
我临时使用这种方式处理了
<img width="574" alt="image" src="https://user-images.githubusercontent.com/24449830/222348972-197d60b8-351c-4a3a-9613-8c2ce54b74ac.png">
