### ISSUE TITLE
如果子应用已经是WebComponent的微前端应用，那将会出错

### ISSUE THREAD

**Issue by yorkezhong** [Tencent/wujie#384]
**描述bug**
如果子应用已经是WebComponent的微前端应用，那将会出错。
如在micro-app框架下：子应用在降级模式里报error”Cannot set property createElement of #<Document> which has only a getter“
在普通模式挂载中报"Cannot set property undefined of src"

**如何复现**
给出详细的复现步骤
1、第一步 xxx
2、 第二步 xxx

**错误截图**
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/36060878/217700792-afc66e3a-d32b-41ea-a3ba-22601a98eca9.png">

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by yiludege** [comment]
不支持微前端套娃
