### ISSUE TITLE
在线体验时，页面布局混乱，oob

### ISSUE THREAD

**Issue by xuejunnan** [Tencent/wujie#387]
**描述bug**
进入无界主页，然后点击在线体验，再点击右下角的umi， 就会出现下面截图里面的样子

**错误截图**
![image](https://user-images.githubusercontent.com/28776348/217771204-d0aed931-da7f-4bff-ade9-145601e44525.png)

=

**Comment by yiludege** [comment]
完全正常，这个才说明了子应用的DOM是全局的，弹窗可以撑到整个页面，这种混乱需要子应用配合适配，无界没办法让这些网站来配合
