### ISSUE TITLE
cookie 设置在二级域名时，子应用请求接口没有带上cookie

### ISSUE THREAD

**Issue by AzronChan** [Tencent/wujie#389]
主应用：a.baidu.com
子应用：b.baidu.com
cookie: token = xxx, path = .ruqimobility.com;
已处理好跨域，分别单独打开主应用或者子应用，都可以拿到token；

问题：
在主应用加载了子应用，子应用发起请求如 `b.baidu.com/getlist`, request header 里没有token cookie 导致鉴权失败

请问如何解决？

ps: 在本地主应用和子应用都是localhost但不同端口的情况下，也出现以上问题。但是可以理解，毕竟不同端口，所以通过`axios`请求时配置 `withCredentials = true` 可以解决；但是部署后，同二级域名情况下，按道理应该可以拿到cookie，所以就没有配置 `withCredentials ` 了然后就失败了

**Comment by yiludege** [comment]
> 但是部署后，同二级域名情况下，按道理应该可以拿到cookie，所以就没有配置 withCredentials  了然后就失败了

这个按道理是按哪个道理？，三级域名不同也是跨域，跨域就不会默认带上cookie的吧

**Comment by renwofei423** [comment]
> > 但是部署后，同二级域名情况下，按道理应该可以拿到cookie，所以就没有配置 withCredentials  了然后就失败了
> 
> 这个按道理是按哪个道理？，三级域名不同也是跨域，跨域就不会默认带上cookie的吧

端口不同算跨域吗？

**Comment by salmanLee** [comment]
> > > 但是部署后，同二级域名情况下，按道理应该可以拿到cookie，所以就没有配置 withCredentials  了然后就失败了
> > 
> > 
> > 这个按道理是按哪个道理？，三级域名不同也是跨域，跨域就不会默认带上cookie的吧
> 
> 端口不同算跨域吗？

![image](https://github.com/Tencent/wujie/assets/31683902/e152abff-da69-4e1e-bdb8-45ba051e9dca)

**Comment by z58362026** [comment]
我本地访问设置withCredentials = true，不同端口可以带上cookie，但是network，的接口status状态，显示cors error，是什么原因，我使用的是vite启动，也配置了跨域请求头

**Comment by xinlanlan** [comment]
为什么我设置了withCredentials = true 不通端口还是带不上呢
