### ISSUE TITLE
子应用跳转地址编码问题

### ISSUE THREAD

**Issue by zhoufanglu** [Tencent/wujie#390]
**描述bug**
跳转子应用地址自动编码？
**如何复现**
父子应用都是vue3+ vite, 路由模式都是history

**错误截图**
目前地址展示:`http://127.0.0.1:5173/child-app-1?child-app-1=%2Fchild-app-1%2FHelloWorld` 
实际应该是`http://127.0.0.1:5173/child-app-1/HelloWorld`
![image](https://user-images.githubusercontent.com/24451091/218387733-f5cddc38-cbdf-458e-9be7-6ed65ff43f7a.png)

**代码**
```js
<WujieVue
      width="100%"
      height="100%"
      name="child-app-1"
      :url="url"
      :sync="true"
      :fetch="fetch"
      :props="props"
      :before-load="beforeLoad"
      :before-mount="beforeMount"
      :after-mount="afterMount"
      :before-unmount="beforeUnmount"
      :after-unmount="afterUnmount"
    ></WujieVue>
```

**Comment by trynotbecool** [comment]
是 :sync="true" 这个api导致的
具体可以参考https://wujie-micro.github.io/doc/guide/sync.html

**Comment by jiangdexiao** [comment]
> 是 :sync="true" 这个api导致的 具体可以参考https://wujie-micro.github.io/doc/guide/sync.html

跟这个没关系，没有这个也是有这个问题

**Comment by zhoufanglu** [comment]
> 是 :sync="true" 这个api导致的 具体可以参考https://wujie-micro.github.io/doc/guide/sync.html

去掉了，我跳转子应用，上面路由地址就没变化了

**Comment by yiludege** [comment]
可以查看demo的路由耦合方案，左侧菜单栏下拉里面的场景应该符合你的需求
