### ISSUE TITLE
子应用如何改变主应用的url

### ISSUE THREAD

**Issue by BeckyWang** [Tencent/wujie#392]
**描述bug**
子应用通过a链接点击可直接改变主应用url，但是通过window.location.href="XXX"的方式会出现iframe嵌套，还有其他方法通过js改变主应用url吗？

**如何复现**
给出详细的复现步骤
1、第一步 xxx
2、 第二步 xxx

**错误截图**
如果有可以将截图带上

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by yiludege** [comment]
可以通过通信的方式让主应用跳转路由

**Comment by BeckyWang** [comment]
> 可以通过通信的方式让主应用跳转路由

这么做的话是不是就要侵入子应用代码，需要在子应用里面作判断？
我在想，能否开启一个配置，开启后就将子应用的location操作都作用到主应用上，或者暴露一个钩子，主应用能监听到子应用location操作？
