### ISSUE TITLE
请问子应用改造那里的跨域处理怎么配置

### ISSUE THREAD

**Issue by wssnail** [Tencent/wujie#395]
我在createApp()上使用官网给出的配置，打包部署后提示错误res没有set方法
app.use((req, res, next) => {
  // 路径判断等等
  res.set({
    "Access-Control-Allow-Credentials": true,
    "Access-Control-Allow-Origin": req.headers.origin || "*",
    "Access-Control-Allow-Headers": "X-Requested-With,Content-Type",
    "Access-Control-Allow-Methods": "PUT,POST,GET,DELETE,OPTIONS",
    "Content-Type": "application/json; charset=utf-8",
  });
  // 其他操作
});

另外我遇到部署后，主、子应用使用域名，存在GET\POST跨域问题，静态资源能访问子应用的nginx，并且配置nginx(主、子应用)的跨域都不起作用

**Comment by ZephyrTan** [comment]
我觉得官网说的不详细，这个看着像是nodejs的后端服务，这个app难道是vue的app吗？

**Comment by yszhangjl** [comment]
https://enable-cors.org/server_nginx.html

**Comment by Weicup** [comment]
问题解决了？

**Comment by Crazysanlang** [comment]
> 我在createApp()上使用官网给出的配置，打包部署后提示错误res没有set方法 app.use((req, res, next) => { // 路径判断等等 res.set({ "Access-Control-Allow-Credentials": true, "Access-Control-Allow-Origin": req.headers.origin || "*", "Access-Control-Allow-Headers": "X-Requested-With,Content-Type", "Access-Control-Allow-Methods": "PUT,POST,GET,DELETE,OPTIONS", "Content-Type": "application/json; charset=utf-8", }); // 其他操作 });
> 
> 另外我遇到部署后，主、子应用使用域名，存在GET\POST跨域问题，静态资源能访问子应用的nginx，并且配置nginx(主、子应用)的跨域都不起作用

请问解决了吗？ 我目前也遇到了这样的问题

**Comment by alexders** [comment]
同问，怎么解决的？
