### ISSUE TITLE
[Question] 怎么将子应用内动态加载 js 运行到 wujie 创建的同域名 iframe 中

### ISSUE THREAD

**Issue by cryzzchen** [Tencent/wujie#400]
**描述bug**
在业务中会使用一个三方包，该三方包会根据业务的配置通过在 document.body 上动态创建 script 标签来下载需要的 js 文件。

![image](https://user-images.githubusercontent.com/3948124/219277735-f45bcc33-e732-4f69-b371-3cbd5fb5fae0.png)

如上图，问题来了，三方包被打包在业务 JS 里面，需要使用动态 script 中加载的全局变量，因为 iframe 的隔离性，导致访问失败。

跟官网[第三方包已经引入，使用时报错](https://wujie-micro.github.io/doc/question/#_2%E3%80%81%E7%AC%AC%E4%B8%89%E6%96%B9%E5%8C%85%E5%B7%B2%E7%BB%8F%E5%BC%95%E5%85%A5%EF%BC%8C%E4%BD%BF%E7%94%A8%E6%97%B6%E6%8A%A5%E9%94%99)描述的不同点在于：动态 JS 由动态创建 script 标签来加载，wujie 无法获取到，因此我无法通过引入 jsLoader 来改变其内容

想问下这个场景有什么比较好的解决方法么？

**Comment by cryzzchen** [comment]
或者可以提供 iframe 的 document 么？在执行三方包时，我将内部的 document 替换成 iframe 的 document（目前指向了 shadow root）

**Comment by yiludege** [comment]
1、动态js 插入到 shadowroot 中的 body 中时无界会将这个动态 js 下载下来转移到 iframe 内联运行

2、window. __WUJIE_RAW_WINDOW__.document  可以拿到原生的 iframe document对象
