### ISSUE TITLE
关于 Cannot read properties of undefined (reading 'querySelectorAll')报错

### ISSUE THREAD

**Issue by vannvan** [Tencent/wujie#404]
**描述bug**
如题

**如何复现**

偶现，官方在线体验就有的问题

https://wujie-micro.github.io/doc/wujie/

**错误截图**
<img width="968" alt="image" src="https://user-images.githubusercontent.com/43501134/219593043-bb1dce3a-f256-49ed-bf81-33c2c904e9db.png">

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by 961998264** [comment]
我也碰到这个问题，是element的table组件出现这个问题，和版本有关系

**Comment by miaoyumeng** [comment]
> 我也碰到这个问题，是element的table组件出现这个问题，和版本有关系

你好，请问怎么解决这个问题的？
