### ISSUE TITLE
想请教下无界的官方demo,是怎么实现正常展示 antd 等第三方域名的站点的，访问 iframe.contentWindow. history 等 api 时，不会跨域吗

### ISSUE THREAD

**Issue by AwesomeDevin** [Tencent/wujie#409]
**非bug**
想请教下无界的官方demo,是怎么实现正常展示 antd 等第三方域名的站点的，访问 iframe.contentWindow. history 等 api 时，不会跨域吗?

我这边本地测试访问 antd 会有跨域问题.  
![](https://img12.360buyimg.com/img/s900x43_jfs/t1/140420/30/24705/19399/63f2e267Ff8302bc1/34e94c3b9a2e18a0.png)

**Comment by gadzan** [comment]
## 第一个问题
你可以看下antd的响应头，资源都是 access-control-allow-origin: * 的，这些文档站点基本都是允许跨域访问的，这也是作为微前端子应用的必要条件；

## 第二个问题：
无界在创建子应用时会在页面文档创建一个同域的iframe，以上面antd为例：
`<iframe src="//wujie-micro.github.io/doc" style="display: none" name="https://ant.design/components/drawer-cn/" data-wujie-flag=""></iframe>`
同域的资源父窗口浏览器是允许可以调用的，不会跨域，这是无界实现的原理；

## 第三个问题
同上，这个无界的iframe的src是这样拼起来的：`window.location.protocol + "//" + window.location.host`，没有端口号，我看你的 origin 是 `http://dev.jd.com:3000`，与被创建的 iframe 不同端口号会导致跨域。
你应该只是代理了ip与域名，试下把端口号改成80，或者用其他代理工具把端口号也代理，就没问题了

**Comment by AwesomeDevin** [comment]
> ## 第一个问题
> 你可以看下antd的响应头，资源都是 access-control-allow-origin: * 的，这些文档站点基本都是允许跨域访问的，这也是作为微前端子应用的必要条件；
> 
> ## 第二个问题：
> 无界在创建子应用时会在页面文档创建一个同域的iframe，以上面antd为例： `<iframe src="//wujie-micro.github.io/doc" style="display: none" name="https://ant.design/components/drawer-cn/" data-wujie-flag=""></iframe>` 同域的资源父窗口浏览器是允许可以调用的，不会跨域，这是无界实现的原理；

感谢回复，主要是第二个疑问比较大，原来创建的是是同域 iframe
