### ISSUE TITLE
new URL函数导致二级菜单下刷新出现资源获取报404错误

### ISSUE THREAD

**Issue by zzylj** [Tencent/wujie#413]
**描述bug**
在多级路由下进行刷新，资源路径错误导致获取不到相应资源文件，报404错误。

**如何复现**
在packages/wujie-core/src/utils.ts文件下，劫持元素原型相对地址的赋值转绝对地址 rawElementSetAttribute()函数会获取资源路径的相对地址，与子应用当前路径下的绝对地址进行拼接，得到资源的绝对路径进行资源获取

在该函数中调用了两次getAbsolutePath()方法，传入的第二个参数为资源的路径，在packages/wujie-core/src/iframe.ts中的patchElementEffect函数设置，获取的为get函数的返回值，

传入的第一个参数为xxx.js(文件名称)或者  /xxx/xxx(相对路径) ，当传入的为xxx.js时，会调用getAbsolutePath()方法返回new URL(url,base).href ,  例如url为xxx.js，base为http://localhost:8080/aaa/bbb时，进行路径拼接会将最后一级路由替换掉（如果是相对路径则会全部替换）返回http://localhost:8080/aaa/xxx.js，路径因此多了一层/aaa路由，导致404错误。
![image2023-2-21_16-22-8](https://user-images.githubusercontent.com/125952595/220389140-5afc3ade-5997-4649-bb8c-2add52dc1889.png)

目前解决方法有两种
①在packages/wujie-core/src/iframe.ts中的patchElementEffect函数下，定义baseURI的get方法时，删除proxyLocation.pathname，即get: () => proxyLocation.protocol + "//" + proxyLocation.host, 目前没有发现问题，baseURI也只在劫持元素原型相对地址的赋值转绝对地址时用到了两次。且pathname在url为相对路径时会被完全替换掉,没有起到作用，为什么baseURI的get定义要加一层pathname?

②在以下两处添加条件判断，将传入的url均变为相对路径（判断是否以“/”开头，若不是则在头部添加“/”），保证可以将pathname全部替换掉。
![2023-02-21_16-11-31](https://user-images.githubusercontent.com/125952595/220388618-97d0a23d-f42b-43eb-b764-7932f0b9fad0.png)

我想问一下以上两种方法可行吗？会不会有什么影响？

**错误截图**
如果有可以将截图带上

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by renwofei423** [comment]
关注一下，期待官方回复、解决

**Comment by renwofei423** [comment]
顶一下

**Comment by yiludege** [comment]
这个问题我觉得不应该这样做，举一个很简单的例子：
