### ISSUE TITLE
wujie拦截子应用阿里图标库的js文件

### ISSUE THREAD

**Issue by JCqiu** [Tencent/wujie#415]
**描述bug**
清晰准确的描述bug
![image](https://user-images.githubusercontent.com/16211027/220819450-24b373a9-abe3-4320-b5f2-9f01a7750f5e.png)
wujie拦截子应用阿里图标库的js文件
**如何复现**
给出详细的复现步骤
1、第一步 xxx
2、 第二步 xxx

**错误截图**
![image](https://user-images.githubusercontent.com/16211027/220819450-24b373a9-abe3-4320-b5f2-9f01a7750f5e.png)

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by JCqiu** [comment]
![image](https://user-images.githubusercontent.com/16211027/220819683-899dc6c7-cd58-4642-8359-121f24b20505.png)

**Comment by JCqiu** [comment]
![image](https://user-images.githubusercontent.com/16211027/220820001-05a97f1d-3953-424f-b095-df5991fe1ddf.png)
试过这几个插件还是会被拦截

**Comment by JCqiu** [comment]
![1677132411596](https://user-images.githubusercontent.com/16211027/220832361-e8e3b811-3f75-48eb-b39c-bf2015814c1a.jpg)
![微信图片_20230223140407](https://user-images.githubusercontent.com/16211027/220832377-19a87175-9f7d-43a5-89b8-7d3de3ab0f75.png)
第一次进入的时候图标js文件在生效,第二次进入图标js文件就没有了

**Comment by yiludege** [comment]
这个地方已经回到了这个问题，不是js文件被劫持的问题，而是js只会运行一次，生成的svg在切换后悔丢失，所以需要保存起来，https://github.com/Tencent/wujie/issues/197#issuecomment-1420390244
