### ISSUE TITLE
子应用引用第三方js，第三方js依赖另外的js，会提示跨域问题，怎么解决？ 

### ISSUE THREAD

**Issue by 1017178399** [Tencent/wujie#416]

**Comment by Lincong-pro** [comment]
我也遇到了一样的问题，就是我引用的Cesium.js，但是Cesium.js依赖另外的js，它就是/undefined/Widgets/xx.js找不到。原本正确的路径是/libs/Cesium现在变成了/undefined

**Comment by water5656** [comment]
monaco-eidtor，new worker时好像也是这个问题，求解

**Comment by fuuhoo** [comment]
请问解决了么

**Comment by fuuhoo** [comment]
> 我也遇到了一样的问题，就是我引用的Cesium.js，但是Cesium.js依赖另外的js，它就是/undefined/Widgets/xx.js找不到。原本正确的路径是/libs/Cesium现在变成了/undefined
请问解决了吗？
