### ISSUE TITLE
子应用 vue3和vite项目做了兼容，通过无界方式chrome 49加载有问题，独立访问子应用可以。官方demo项目在chrome49，也未能加载

### ISSUE THREAD

**Issue by wangshengli1992** [Tencent/wujie#423]
**描述bug**
清晰准确的描述bug

**如何复现**
给出详细的复现步骤
1、第一步 xxx
2、 第二步 xxx

**错误截图**
如果有可以将截图带上

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by yiludege** [comment]
暂不支持49

**Comment by huangliyun02** [comment]
目前无界支持到的chrome版本最低是多少呢 @yiludege
