### ISSUE TITLE
外链脚本没有按照引入的顺序执行

### ISSUE THREAD

**Issue by achuan9** [Tencent/wujie#424]
**描述bug**
外链脚本没有按照引入的顺序执行，而是谁先加载完就执行谁

**如何复现**
给出详细的复现步骤
1、子应用通过外链形式引入`vue.global.prod.min.js`

2、主应用配置`jsIgnores`:
```js
plugins: [{
    jsIgnores: [/vue\.global\.prod/]
}]
```
3、 打开控制台会提示`Uncaught ReferenceError: Vue is not defined`

**最小复现仓库或者地址**
这里精简了一下Wujie相关的代码来复现BUG：
https://stackblitz.com/edit/js-6myawr?file=index.html

**Comment by Newway1997** [comment]
应该是不支持这个vue.global.prod.min.js，这个js里直接是在全局作用域用的var声明变量Vue，被无界[用function包裹](https://github.com/Tencent/wujie/blob/f92942fb8ee6f3d8aa1c1dbe9eb646875645fbf4/packages/wujie-core/src/iframe.ts#L716)后，var变量声明不会挂载到window上，类似于这样：
```js
(function(){
    var Vue;
})()
console.log(Vue)//Uncaught ReferenceError: Vue is not defined
```
所以得用将全局变量挂载到window上或者umd格式的外联脚本

**Comment by achuan9** [comment]
> 应该是不支持这个vue.global.prod.min.js，这个js里直接是在全局作用域用的var声明变量Vue，被无界[用function包裹](https://github.com/Tencent/wujie/blob/f92942fb8ee6f3d8aa1c1dbe9eb646875645fbf4/packages/wujie-core/src/iframe.ts#L716)后，var变量声明不会挂载到window上，类似于这样：
> 
> ```js
> (function(){
>     var Vue;
> })()
> console.log(Vue)//Uncaught ReferenceError: Vue is not defined
> ```
> 
> 所以得用将全局变量挂载到window上或者umd格式的外联脚本

嗯嗯你说的这个也是日常开发需要注意的一个地方，但是我说的这个是动态添加`iframe`并新增外链脚本出现的问题

**Comment by Newway1997** [comment]
> > 应该是不支持这个vue.global.prod.min.js，这个js里直接是在全局作用域用的var声明变量Vue，被无界[用function包裹](https://github.com/Tencent/wujie/blob/f92942fb8ee6f3d8aa1c1dbe9eb646875645fbf4/packages/wujie-core/src/iframe.ts#L716)后，var变量声明不会挂载到window上，类似于这样：
> > 
> > ```js
> > (function(){
> >     var Vue;
> > })()
> > console.log(Vue)//Uncaught ReferenceError: Vue is not defined
> > ```
> > 
> > 所以得用将全局变量挂载到window上或者umd格式的外联脚本
> 
> 嗯嗯你说的这个也是日常开发需要注意的一个地方，但是我说的这个是动态添加`iframe`并新增外链脚本出现的问题

就是这个vue.global.prod.min.js外链不行，执行顺序是对的，你把这个外链换成jquery的，在wujie中都是可以的。而且你这个精简的demo也不对，wujie是先获取外链js内容转为内联的script再append的，这个demo是直接append的外链script

**Comment by achuan9** [comment]
> 

我这个demo就是说明不通过`fetch`后`append`到`head`中的情况，也就是配置`jsIgnores`的情况，为啥你说`vue.global.prod.min.js`外链不行？

**Comment by Newway1997** [comment]
哦，我理解你的意思了。我是指这个不配置jsIgnores也不行

**Comment by achuan9** [comment]
> 哦，我理解你的意思了。我是指这个不配置jsIgnores也不行

嗯嗯，你说的那个闭包的问题我知道的

**Comment by achuan9** [comment]
配置`jsLoader`，例如：
`jsLoader: (code, url, base) => {
    return code.replace("var Vue", "window.Vue");
}`

**Comment by fychinesepjj** [comment]
这个问题我也碰到了，加载的子应用中动态插入js，js的执行顺序很随机。
比如有个文件index.js 依赖window.antd，antd 资源包动态插入和执行应是在index.js之前的，单在wujie的容器中执行的时，就变成index.js先执行，并且情况很随机有时正常有时候不正常。
同时这个情况和资源包加载的时间也有很大关系，在wujie中是先加载完毕，先执行就导致了这个问题

**Comment by fychinesepjj** [comment]
@yiludege 请教这个问题现在有什么方案可以绕过去么
