### ISSUE TITLE
子应用代码执行性能问题

### ISSUE THREAD

**Issue by fanqi7** [Tencent/wujie#429]
通过实践数据验证，发现动态创建script执行代码的性能跟eval执行代码的性能差不多，但比new Function的方式性能低很多，是否考虑使用new Function的方式替换动态创建script的方式
数据验证方法可参考如下方式：
`var str = '';
for (let i = 0; i < 100; i++) {
  str += `var test_${i} = ${i};\n`;
}
console.time('eval exec');
eval(str);
console.timeEnd('eval exec');
console.time('eval exec 2');
eval(str);
console.timeEnd('eval exec 2');

console.time('fn exec');
var fn = new Function(str);
fn();
console.timeEnd('fn exec');

console.time('fn exec 2');
fn();
console.timeEnd('fn exec 2');`

**Comment by fanqi7** [comment]
我通过一下代码验证了动态创建script执行代码的方式（这种方式是无界执行子应用代码的采用的方式）和eval方式对比了代码运行性能，发现二者性能并无区别，甚者比eval低一点。其中new Function的方式性能最高，请问后期是否考虑做相关的优化：改用new Function的方式
`
var str = '';
for (let i = 0; i < 100; i++) {
  str += `var test_${i} = ${i};\n`;
}

function loadScriptString(code){
  var script=document.createElement("script");
  script.type="text/javascript";
  script.textContent = code;
  document.getElementsByTagName('head')[0].appendChild(script);
}

console.time('eval exec');
eval(str);
console.timeEnd('eval exec');

console.time('script exec');
loadScriptString(str)
console.timeEnd('script exec');

console.time('fn exec');
var fn = new Function(str);
fn();
console.timeEnd('fn exec');

`

**Comment by yiludege** [comment]
想让代码跑在iframe里面，就算采用 new Function的方式，那么也是 `<script> new Function (xxx) <script>`的方式运行，没有区别的
