### ISSUE TITLE
单 Vue 应用不会渲染

### ISSUE THREAD

**Issue by jawn-ha** [Tencent/wujie#43]
目前子应用只是一个简单的单Vue应用，没有用vue-router、vuex、webpack等，但是组件没有渲染，iframe中可以正常显示
控制台没有任何报错
<img width="558" alt="image" src="https://user-images.githubusercontent.com/16000122/183829345-278c1786-8956-4fdb-aacb-8ec670213c88.png">
<img width="588" alt="image" src="https://user-images.githubusercontent.com/16000122/183828819-e0526f3e-57a8-48b6-8d97-bff5488d6623.png">
<img width="610" alt="image" src="https://user-images.githubusercontent.com/16000122/183829014-d8eda16b-7bae-4bcd-8908-0c3d9192b6ae.png">

是index.html的内联js没有执行吗？

**Comment by yiludege** [comment]
简单的单vue应用可以给一个示例链接吗，index.html的内联js会执行的

**Comment by yiludege** [comment]
明白大概的问题了，window.onload事件应该不会执行，导致这个问题

**Comment by jawn-ha** [comment]
> 明白大概的问题了，window.onload事件应该不会执行，导致这个问题
> 
> 把 window.onload = 删除掉试试？

删掉真就可以了
