### ISSUE TITLE
django的模板页面作为wujie的子应用的时候，提示一些js函数找不到。

### ISSUE THREAD

**Issue by yyystation** [Tencent/wujie#431]
html代码中
< button class="btn btn-info" onclick="load_some_back_data()"> 查询 </button >

<script>
//代码块中包含以下：
function load_some_back_data() {
   .......
}
</script>

当点击页面上的按钮后，提示：
Uncaught ReferenceError: load_some_back_datais not defined

原因似乎是 wujie把所有的scrit块，都用单独的 
(function(window, self, global, location) {
   ...一个script中的代码
}).bind(window.__WUJIE.proxy)(
  window.__WUJIE.proxy,
  window.__WUJIE.proxy,
  window.__WUJIE.proxy,
  window.__WUJIE.proxyLocation,
);
然后用eval去执行，导致html中的事件无法找到相关函数，这种情况要如何处理？

**Comment by yiludege** [comment]
这个问题看看 issue： https://github.com/Tencent/wujie/issues/326
