### ISSUE TITLE
localStorage 并没有实现 iframe 沙箱的隔离效果

### ISSUE THREAD

**Issue by evemike** [Tencent/wujie#433]
**描述bug**
子应用中使用 localStorage.clear() 时，会连带清除主应用中的 数据

**如何复现**
给出详细的复现步骤
1.主应用设置一个 localStorage 值
2.子应用设置一个不同的 localStorage 值
3.子应用中调用 localStorage.clear() 方法
4.查看缓存数据，发现所有数据都被清除了。

对比 iframe 原生方式，并不会清除主应用的 缓存数据。

**错误截图**

**最小复现仓库或者地址**

**Comment by yiludege** [comment]
目前 localStorage 没有做隔离哈

**Comment by evemike** [comment]
哦，好吧~
