### ISSUE TITLE
 vite4子应用切换 样式丢失

### ISSUE THREAD

**Issue by Ttou** [Tencent/wujie#434]
**描述bug**

- vue2 项目的 ElementUI 字体图标无法显示
- 子应用不保活时切路由后再回来，样式消失
- 切换应用时，路由报警告

**如何复现**

**错误截图**
![iShot_2023-03-09_16 42 45](https://user-images.githubusercontent.com/4298437/223967794-9558a588-1c25-4d96-9ad1-13ca8d224b59.gif)

**最小复现仓库或者地址**
[复现仓库](https://github.com/Ttou/wujie-issue.git)

**Comment by Ttou** [comment]
试了下样式丢失和vite的版本有关，vite2.7正常，vite4丢失

**Comment by Ttou** [comment]
路由警告改成vue2做主应用就不报了

**Comment by Ttou** [comment]
字体问题和vite版本有关，vite2.9正常

**Comment by codeflyA** [comment]
遇到了同样的问题 vite4下 vant的字体图标不显示，单独打开子应用的项目没问题，放到wujie框架下vant的字体图标不显示。

**Comment by Ttou** [comment]
基于 vite2.9 + vue-cli5 + wujie1.0.14 的演示项目:
仓库地址：https://gitee.com/jh_shot/wujie-template
演示地址：https://jh_shot.gitee.io/wujie-template

**Comment by yiludege** [comment]
vite 4 加载样式的代码：
![ve(ovite resoweStyle(v](https://github.com/Tencent/wujie/assets/19788268/218263ab-0962-4042-9714-b3f0583803ff)
这个 __vite__updateStyle 具体代码实现：
![documnt hesd oprerdoitd(styte) style - style (disableds false, Redia： -》](https://github.com/Tencent/wujie/assets/19788268/99ee1964-ff7b-4b21-a99d-d76ce83ac61d)

无界子应用如果是单例模式，js只会执行一遍，动态加载进来的样式，无界需要收集起来，等子应用下次切换回来，再将这些样式恢复，对于 document.body.appendChild，和 document.head.appendChild 这样的方法 无界内部已经劫持进行收集，但是vite4上面的代码可以看到采用了 style.InsertAdjacentElement 这样的方法导致无界没有收集到，所以采用下面的插件修改一下 style.InsertAdjacentElement 成 document.head.appendChild可以了，当然也可以不修改InsertAdjacentElement，将InsertAdjacentElement进来的样式放进 iframeWindow.__WUJIE.styleSheetElements里面，下次渲染就可以将样式还原了

```
      plugins: [
        {
          patchElementHook(element, iframeWindow) {
            if (element.nodeName === "STYLE") {
              element.insertAdjacentElement = function (_position, ele) {
                iframeWindow.document.head.appendChild(ele);
              };
            }
          },
        },
      ]
```

**Comment by Ttou** [comment]
试了下，确实可以，不过vite4+vue3+element-plus设置为保活，也需要加上这个配置，不然组件的样式会丢失

**Comment by wen403** [comment]
这个插件在哪使用

**Comment by wen403** [comment]
已解决，完美解决使用不了iconfont的问题，感谢大佬
![image](https://github.com/Tencent/wujie/assets/67454874/68d0440f-5752-48a2-ba59-0f358356d272)

**Comment by Funbin** [comment]
> vite 4 加载样式的代码： ![ve(ovite resoweStyle(v](https://private-user-images.githubusercontent.com/19788268/249991462-218263ab-0962-4042-9714-b3f0583803ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNjc2NDksIm5iZiI6MTcwMTE2NzM0OSwicGF0aCI6Ii8xOTc4ODI2OC8yNDk5OTE0NjItMjE4MjYzYWItMDk2Mi00MDQyLTk3MTQtYjNmMDU4MzgwM2ZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDEwMjkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiOWYwZTY1MmQ0ZWQ0MDM0MjdhYWU1Y2U1YzcxYWFhNWE2NzEzZjQ5YzUxYjZhODg0YzdkMTBmYWQ2YTE5NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OdUO8Q5TqYjk2n_e_Eiv5VHLx2ZmhHi9x1piN59fvaY) 这个 __vite__updateStyle 具体代码实现： ![documnt hesd oprerdoitd(styte) style - style (disableds false, Redia： -》](https://private-user-images.githubusercontent.com/19788268/249991501-99ee1964-ff7b-4b21-a99d-d76ce83ac61d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNjc2NDksIm5iZiI6MTcwMTE2NzM0OSwicGF0aCI6Ii8xOTc4ODI2OC8yNDk5OTE1MDEtOTllZTE5NjQtZmY3Yi00YjIxLWE5OWQtZDc2Y2U4M2FjNjFkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDEwMjkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmOGZhNTIxMjU4NmRhODM1NThlZGZlOWU3ZmQyMmM3ODk0Y2NiY2I2YjQwNmYzNGRjN2ViYjUyNjlmOGJkY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SLgW6xQZGMwFzahdoE9T1DNERYOECv7pY-3YuP_slCo)
> 
> 无界子应用如果是单例模式，js只会执行一遍，动态加载进来的样式，无界需要收集起来，等子应用下次切换回来，再将这些样式恢复，对于 document.body.appendChild，和 document.head.appendChild 这样的方法 无界内部已经劫持进行收集，但是vite4上面的代码可以看到采用了 style.InsertAdjacentElement 这样的方法导致无界没有收集到，所以采用下面的插件修改一下 style.InsertAdjacentElement 成 document.head.appendChild可以了，当然也可以不修改InsertAdjacentElement，将InsertAdjacentElement进来的样式放进 iframeWindow.__WUJIE.styleSheetElements里面，下次渲染就可以将样式还原了
> 
> ```
>       plugins: [
>         {
>           patchElementHook(element, iframeWindow) {
>             if (element.nodeName === "STYLE") {
>               element.insertAdjacentElement = function (_position, ele) {
>                 iframeWindow.document.head.appendChild(ele);
>               };
>             }
>           },
>         },
>       ]
> ```

patchElementHook  切换子应用2次后不再执行

**Comment by PanZhangOne** [comment]
> > vite 4 加载样式的代码： ![ve(ovite resoweStyle(v](https://private-user-images.githubusercontent.com/19788268/249991462-218263ab-0962-4042-9714-b3f0583803ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNjc2NDksIm5iZiI6MTcwMTE2NzM0OSwicGF0aCI6Ii8xOTc4ODI2OC8yNDk5OTE0NjItMjE4MjYzYWItMDk2Mi00MDQyLTk3MTQtYjNmMDU4MzgwM2ZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDEwMjkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiOWYwZTY1MmQ0ZWQ0MDM0MjdhYWU1Y2U1YzcxYWFhNWE2NzEzZjQ5YzUxYjZhODg0YzdkMTBmYWQ2YTE5NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OdUO8Q5TqYjk2n_e_Eiv5VHLx2ZmhHi9x1piN59fvaY) 这个 __vite__updateStyle 具体代码实现： ![documnt hesd oprerdoitd(styte) style - style (disableds false, Redia： -》](https://private-user-images.githubusercontent.com/19788268/249991501-99ee1964-ff7b-4b21-a99d-d76ce83ac61d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNjc2NDksIm5iZiI6MTcwMTE2NzM0OSwicGF0aCI6Ii8xOTc4ODI2OC8yNDk5OTE1MDEtOTllZTE5NjQtZmY3Yi00YjIxLWE5OWQtZDc2Y2U4M2FjNjFkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDEwMjkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmOGZhNTIxMjU4NmRhODM1NThlZGZlOWU3ZmQyMmM3ODk0Y2NiY2I2YjQwNmYzNGRjN2ViYjUyNjlmOGJkY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SLgW6xQZGMwFzahdoE9T1DNERYOECv7pY-3YuP_slCo)
> > 无界子应用如果是单例模式，js只会执行一遍，动态加载进来的样式，无界需要收集起来，等子应用下次切换回来，再将这些样式恢复，对于 document.body.appendChild，和 document.head.appendChild 这样的方法 无界内部已经劫持进行收集，但是vite4上面的代码可以看到采用了 style.InsertAdjacentElement 这样的方法导致无界没有收集到，所以采用下面的插件修改一下 style.InsertAdjacentElement 成 document.head.appendChild可以了，当然也可以不修改InsertAdjacentElement，将InsertAdjacentElement进来的样式放进 iframeWindow.__WUJIE.styleSheetElements里面，下次渲染就可以将样式还原了
> > ```
> >       plugins: [
> >         {
> >           patchElementHook(element, iframeWindow) {
> >             if (element.nodeName === "STYLE") {
> >               element.insertAdjacentElement = function (_position, ele) {
> >                 iframeWindow.document.head.appendChild(ele);
> >               };
> >             }
> >           },
> >         },
> >       ]
> > ```
> 
> patchElementHook 切换子应用2次后不再执行

也遇到同样的问题，请问有没有解决啊

**Comment by weizhigang55** [comment]
> 已解决，完美解决使用不了iconfont的问题，感谢大佬
> 
> ![image](https://github.com/Tencent/wujie/assets/67454874/68d0440f-5752-48a2-ba59-0f358356d272)

好兄弟，想问下具体怎么使用的，有点不太明白稍微

**Comment by wen403** [comment]
> yiludege

把@yiludege发的插件放进去就行了

**Comment by LJiangA** [comment]
> > 已解决，完美解决使用不了iconfont的问题，感谢大佬
> > ![image](https://private-user-images.githubusercontent.com/67454874/275141239-68d0440f-5752-48a2-ba59-0f358356d272.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNDg1NDAsIm5iZiI6MTcxNjM0ODI0MCwicGF0aCI6Ii82NzQ1NDg3NC8yNzUxNDEyMzktNjhkMDQ0MGYtNTc1Mi00OGEyLWJhNTktMGYzNTgzNTZkMjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDAzMjQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNDQ5MTFkMGE0NWI3ZGZmYTAzYzI0NWYxM2Y0MzMzNmM1YjI3YzQ4MDIyYTk3MWJhZmEzNThlNTM3YjFhMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JVbYiVWhPNIhEgYwZC7ChYrkGcwsdwaQ0YF0MmL9bCg)
> 
> 好兄弟，想问下具体怎么使用的，有点不太明白稍微

这样可以解决
![image](https://github.com/Tencent/wujie/assets/64141612/b239c99e-a4b6-4e53-9df1-404962181046)

**Comment by weizhigang55** [comment]
> > > 已解决，完美解决使用不了iconfont的问题，感谢大佬
> 
> > > ![image](https://private-user-images.githubusercontent.com/67454874/275141239-68d0440f-5752-48a2-ba59-0f358356d272.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNDg1NDAsIm5iZiI6MTcxNjM0ODI0MCwicGF0aCI6Ii82NzQ1NDg3NC8yNzUxNDEyMzktNjhkMDQ0MGYtNTc1Mi00OGEyLWJhNTktMGYzNTgzNTZkMjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDAzMjQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNDQ5MTFkMGE0NWI3ZGZmYTAzYzI0NWYxM2Y0MzMzNmM1YjI3YzQ4MDIyYTk3MWJhZmEzNThlNTM3YjFhMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JVbYiVWhPNIhEgYwZC7ChYrkGcwsdwaQ0YF0MmL9bCg)
> 
> > 
> 
> > 好兄弟，想问下具体怎么使用的，有点不太明白稍微
> 
> 
> 
> 这样可以解决
> 
> ![image](https://github.com/Tencent/wujie/assets/64141612/b239c99e-a4b6-4e53-9df1-404962181046)
> 
> 
> 
> 

感激感激，我明天试试看下，谢谢大佬了

**Comment by LJiangA** [comment]
> Vite4搭建的子应用，在切换路由2次后，页面就无法正常加载，有遇到类似的问题吗？另一个子应用是使用webpack + vue2搭建的子应用，就是正常的

也遇到了类似问题，请问解决了吗？

**Comment by xiaomo1128** [comment]
> > Vite4搭建的子应用，在切换路由2次后，页面就无法正常加载，有遇到类似的问题吗？另一个子应用是使用webpack + vue2搭建的子应用，就是正常的
> 
> 也遇到了类似问题，请问解决了吗？

您添加了 上面 plugins 那一段代码，依旧出现 无法正常加载的问题吗

**Comment by LJiangA** [comment]
> > > Vite4搭建的子应用，在切换路由2次后，页面就无法正常加载，有遇到类似的问题吗？另一个子应用是使用webpack + vue2搭建的子应用，就是正常的
> > 
> > 
> > 也遇到了类似问题，请问解决了吗？
> 
> 您添加了 上面 plugins 那一段代码，依旧出现 无法正常加载的问题吗

刚开始是可以正常加载的，且第一次切换vite4子应用内的路由也可以正常显示，但切到其他子应用后再切回vite4子应用，进行路由切换时，就无法正常加载了

**Comment by LJiangA** [comment]
> > > > > Vite4搭建的子应用，在切换路由2次后，页面就无法正常加载，有遇到类似的问题吗？另一个子应用是使用webpack + vue2搭建的子应用，就是正常的
> > > > 
> > > > 
> > > > 也遇到了类似问题，请问解决了吗？
> > > 
> > > 
> > > 您添加了 上面 plugins 那一段代码，依旧出现 无法正常加载的问题吗
> > 
> > 
> > 刚开始是可以正常加载的，且第一次切换vite4子应用内的路由也可以正常显示，但切到其他子应用后再切回vite4子应用，进行路由切换时，就无法正常加载了
> 
> 我拿别人搭建好的 vue3vite主应用 react子应用+vue3vite子应用 wujie最新模版，也出现了像您说的这个问题
> 
> 但是我问到一个大佬，他用wujie接入以vue3vite主应用 vue3vite等多个子应用，他说没有这些问题(接入成功)，而且他的微前端业务场景也挺复杂的，您可以加 wujie群，进群讨论一下你的问题

好的，我已经加群了，但是目前先被另一个[问题#71](https://github.com/Tencent/wujie/issues/71)给困扰着了

**Comment by hnldlsjzt** [comment]
无界的保活模式。在 vite5 的环境下，加上了这个插件后，还是会丢失样式

**Comment by BraveAriesZyc** [comment]
> Vite4搭建的子应用，在切换路由2次后，页面就无法正常加载，有遇到类似的问题吗？另一个子应用是使用webpack + vue2搭建的子应用，就是正常的

路由的模式吧

**Comment by zr520** [comment]
谢谢，解决了vite高版本样式丢失问题

**Comment by zhmlarry** [comment]
大佬这个插件名npm插件名叫什么？不用下载引入直接用吗？

**Comment by weizhigang55** [comment]
@zhmlarry 这不是插件库，不需要下载引入

**Comment by yiludege** [comment]
框架将在1.0.28版本支持

**Comment by lucoyuk1** [comment]
> 无界的保活模式。在 vite5 的环境下，加上了这个插件后，还是会丢失样式

子应用vite5+v3开保活样式正常

**Comment by book-qian** [comment]
1.0.28 增加了prop style 之后，vue2会报警告 “style” is reserved attribute and cannot be as component prop ,如何解决？

**Comment by sky124380729** [comment]
为什么我用这个plugins是生效的，去掉plgins升级到1.0.29还是不生效

**Comment by itmanyong** [comment]
vite8+unocss66.6.0默认情况下：在从主应用其他路由切换到子应用时还是会出现不加载unocss的样式的情况，如果url直接指向子应用的路由直接刷新的情况下是正常的
庆兴的是楼主的方法有效
