### ISSUE TITLE
chrome 升级后，子项目弹窗不能全屏了。

### ISSUE THREAD

**Issue by tang66** [Tencent/wujie#440]
**描述bug**
Chrome版本 111.0.5563.64
 "wujie-vue3": "^1.0.2"

未升级前Chrome版本109 弹窗显示正常

**错误截图**
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/29703704/224973298-9d31e38a-abc2-4ac4-9e41-5c23e73fa227.png">

**最小复现仓库或者地址**
https://wujie-micro.github.io/demo-main-vue/vue3?vue3=%2Fdemo-vue3%2Fdialog

**Comment by yiludege** [comment]
已经OK

**Comment by reacoulchen** [comment]
> 已经OK

楼主，怎么解决的，我项目也遇到这个问题，是要升级版本还是加入什么代码吗

**Comment by agileago** [comment]
@yiludege  外部如果有fixed的元素，依然不能全屏

<img width="1888" alt="image" src="https://user-images.githubusercontent.com/11799110/225326282-65754056-1824-4484-b796-62722ffc3a89.png">
