### ISSUE TITLE
子应用调用百度地图正常，通过主应用调用子应用显示跨域问题

### ISSUE THREAD

**Issue by Jckong-zc** [Tencent/wujie#442]
主应用页面 http://101.34.32.37:9090/?vite=%2Fdemo-vite%2FbaiduMap#/vite-sub/baiduMap
子应用页面 http://101.34.32.37:8000/demo-vite/baiduMap
直接加载页面 报跨域问题

点击查询后-查看线路数据 渲染地图

[仓库](https://gitee.com/kzion-zc/wujie-vite)

**Comment by gyhyfj** [comment]
请问是怎么解决的呢

**Comment by thatsfelix** [comment]
看上去他好像也没有解决
![image](https://user-images.githubusercontent.com/58354564/226525531-f46ecbd2-2fbc-4c61-b263-27604b78f715.png)

**Comment by resyin** [comment]
可以尝试如下设置：

```
  const plugins = [
    {
      // 解决百度地图 cors
      jsIgnores: [/baidu/],
      // 解决百度地图加载后 parentNode === null
      appendOrInsertElementHook(_element, _iframeWindow, rawElement) {
        if (rawElement)
          Object.defineProperty(rawElement, 'parentNode', {
            get: () => ({ removeChild: () => null }),
          });
      },
    },
  ];

  setupApp({...,plugins})
```
