### ISSUE TITLE
vue3子应用会继承主应用的样式

### ISSUE THREAD

**Issue by weishenai** [Tencent/wujie#446]
**描述bug**
vue3子应用继承了主应用的class

**如何复现**
给出详细的复现步骤
1、第一步 : 在wujie-vue 标签外包裹一层div,定义class=“vue3Content”,
2、第二步 : 子应用样式文件注释
3、第三步：给vue3Content添加样式，子应用受影响

**错误截图**
如果有可以将截图带
![Snipaste_2023-03-16_17-39-35](https://user-images.githubusercontent.com/59504283/225576856-e826b3c4-a8f1-4845-addd-c28a658df4c3.png)
上

**Comment by yiludege** [comment]
https://lamplightdev.com/blog/2019/03/26/why-is-my-web-component-inheriting-styles/
