### ISSUE TITLE
官方文档首页在2560显示器布局错乱

### ISSUE THREAD

**Issue by tong822218** [Tencent/wujie#449]
**描述bug**
官方文档首页在2560显示器布局错乱

**如何复现**
给出详细的复现步骤
打开官方网站：https://wujie-micro.github.io/doc/guide/

**错误截图**
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/9926531/225839326-a4347586-3348-4965-b790-ec2e55a8164c.png">

**Comment by yiludege** [comment]
@ErKeLost 帮忙看看呢

**Comment by yiludege** [comment]
宽度问题，修复了
