### ISSUE TITLE
主应用中如有position为absolute、fixed的元素，则子应用的弹窗无法全屏

### ISSUE THREAD

**Issue by fanqi7** [Tencent/wujie#458]
如图
![screenshot-20230320-174700](https://user-images.githubusercontent.com/46001043/226307198-2f298816-dcad-4b0a-a20c-f032c0e9c1b2.png)

**Comment by yiludege** [comment]
外部的z-index都比子应用内容高，子应用的弹窗怎么覆盖全局呢

**Comment by 13407864574** [comment]
你好，这个问题解决了吗

**Comment by Thinking80s** [comment]
同问？解决了吗？
