### ISSUE TITLE
子应用使用vite搭建，使用vite-plugin-svg-icons插件svg雪碧图，嵌入到主应用中，图标就不显示了

### ISSUE THREAD

**Issue by yilidan** [Tencent/wujie#460]
**描述bug**
子应用单独访问没有问题，嵌入到主应用中，图标没有了
body下面也没有插入svg

**如何复现**
给出详细的复现步骤
1、npm i vite-plugin-svg-icons -D
2、plugins: [
    viteSvgIcons({
        iconDirs: [path.resolve(process.cwd(), 'src/icons')],
        symbolId: 'icon-[dir]-[name]',
      }),
]

**错误截图**
![image](https://user-images.githubusercontent.com/20895477/226558934-3a47db15-1f18-4d56-9a05-82ab93f2aef6.png)

![image](https://user-images.githubusercontent.com/20895477/226559821-2cba975c-0eab-4542-b77c-754b6815bf95.png)

**如果没有嵌入到wujie的svg正确截图**
![image](https://user-images.githubusercontent.com/20895477/226560449-a3632663-66d4-4f75-9369-995147549dd8.png)

**Comment by hamflx** [comment]
@yilidan 之前碰到过一个这个插件的问题，忘了当时是什么现象了，你可以把 `vite-plugin-svg-icons` 替换成 `@hamflx/vite-plugin-svg-icons` 试试。

这个包 `@hamflx/vite-plugin-svg-icons` 改动点：https://github.com/vbenjs/vite-plugin-svg-icons/compare/main...hamflx:vite-plugin-svg-icons:main。

**Comment by yilidan** [comment]
> 

好的，我试下看

**Comment by yilidan** [comment]
> @yilidan 之前碰到过一个这个插件的问题，忘了当时是什么现象了，你可以把 `vite-plugin-svg-icons` 替换成 `@hamflx/vite-plugin-svg-icons` 试试。
> 
> 这个包 `@hamflx/vite-plugin-svg-icons` 改动点：[vbenjs/vite-plugin-svg-icons@main...hamflx:vite-plugin-svg-icons:main](https://github.com/vbenjs/vite-plugin-svg-icons/compare/main...hamflx:vite-plugin-svg-icons:main)

我把vite-plugin-svg-icons升级到最新的版本，2.0.1的版本，可以正常显示了，谢谢，大佬了

**Comment by HECHONG999** [comment]
> > @yilidan 之前碰到过一个这个插件的问题，忘了当时是什么现象了，你可以把 `vite-plugin-svg-icons` 替换成 `@hamflx/vite-plugin-svg-icons` 试试。
> > 这个包 `@hamflx/vite-plugin-svg-icons` 改动点：[vbenjs/vite-plugin-svg-icons@main...hamflx:vite-plugin-svg-icons:main](https://github.com/vbenjs/vite-plugin-svg-icons/compare/main...hamflx:vite-plugin-svg-icons:main)
> 
> 我把vite-plugin-svg-icons升级到最新的版本，2.0.1的版本，可以正常显示了，谢谢，大佬了

为什么我vite-plugin-svg-icons已经升级到 2.0.1 ,但线上环境 图标就不显示了

**Comment by LGD-PEWS** [comment]
您好，子应用使用vite，如何解决跨域问题？

**Comment by yilidan** [comment]
> > > @yilidan 之前碰到过一个这个插件的问题，忘了当时是什么现象了，你可以把 `vite-plugin-svg-icons` 替换成 `@hamflx/vite-plugin-svg-icons` 试试。
> > > 这个包 `@hamflx/vite-plugin-svg-icons` 改动点：[vbenjs/vite-plugin-svg-icons@main...hamflx:vite-plugin-svg-icons:main](https://github.com/vbenjs/vite-plugin-svg-icons/compare/main...hamflx:vite-plugin-svg-icons:main)
> > 
> > 
> > 我把vite-plugin-svg-icons升级到最新的版本，2.0.1的版本，可以正常显示了，谢谢，大佬了
> 
> 为什么我vite-plugin-svg-icons已经升级到 2.0.1 ,但线上环境 图标就不显示了

我后面升级到最新版本就行了，我还开启了降级模式 degrade: true模式

**Comment by yiludege** [comment]
这个地方是第一次 svg 就没有还是切换子应用后 svg 不存在了

**Comment by yilidan** [comment]
> 这个地方是第一次 svg 就没有还是切换子应用后 svg 不存在了

目前这个问题已经解决了，我把vite-plugin-svg-icons升级到最新的版本，2.0.1的版本
