### ISSUE TITLE
wujie 子应用环境下vite框架 body 中 js外链资源和module 执行顺序不对导致报错

### ISSUE THREAD

**Issue by ykshao** [Tencent/wujie#463]
**描述bug**
清晰准确的描述bug
![image](https://user-images.githubusercontent.com/13257015/226899863-86ffa879-cb10-4a0d-afd8-3dd068ddb581.png)

**如何复现**
给出详细的复现步骤
1、项目用到的js链接 正常是放到body里, 但是在vite 环境下,  作为wujie子应用这种方式会报错,  看加载顺序是错误

**错误截图**

![image](https://user-images.githubusercontent.com/13257015/226913476-0f79788d-202d-41be-aff3-a115cf063792.png)
![image](https://user-images.githubusercontent.com/13257015/226913477-60dc91e7-994b-4291-82cf-729452333d3c.png)

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by yiludege** [comment]
看看最新的版本是否解决你的问题了呢
