### ISSUE TITLE
子应用通过document.getElementById获取元素为空

### ISSUE THREAD

**Issue by huyyasia** [Tencent/wujie#464]
**描述bug**
加载子应用时，子应用会通过document.getElementById获取模板中的js信息，并动态加载执行
但是通过document.getElementById取节点为null

**如何复现**
应用启动时

**错误截图**
![image](https://user-images.githubusercontent.com/6420401/227076130-8f33f3d3-8099-44b9-bb45-8a1ce6af114f.png)

**Comment by yiludege** [comment]
重复问题 #374

**Comment by huyyasia** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
