### ISSUE TITLE
子系统通过调用window.location.href出现问题

### ISSUE THREAD

**Issue by kangkang1995** [Tencent/wujie#466]
**描述bug**
子系统有个退出到子系统登录页的功能，然后子系统调用的是window.location.href，然后主应用的shadow dom变成了iframe，下面有图

**如何复现**
给出详细的复现步骤及图片
1. 图一是正常的
![正常图片](https://user-images.githubusercontent.com/23490616/227131102-09c47d6a-97c4-40ea-99e8-d3a18c297610.png)
2. 然后点击按钮退出登录 ； 逻辑是window.location.href = “*****”；
3. 然后变成了下图
![bug图片](https://user-images.githubusercontent.com/23490616/227131254-1f7749e6-5b22-48dd-8144-883f185c2842.png)

**Comment by yiludege** [comment]
预期行为，调用window.location.href会将当前子应用隐藏，并且生成一个新的iframe替换，点击浏览器返回是可以返回到子应用上的，[demo](https://wujie-micro.github.io/demo-main-vue/react16?react16=%2Fdemo-react16%2Flocation)有对这个问题做过解释

**Comment by sonofmagic** [comment]
请问这个问题有更加细致的解释，遇到了什么场景，为什么要这么设计嘛？我看了这个 demo
![image](https://github.com/user-attachments/assets/86f020e6-83c3-42e5-9fc9-22bddb8c6d92)

也看到了源代码里面这样的实现:
https://github.com/Tencent/wujie/blob/9733864b0b5e27d41a2dc9fac216e62043273dd3/packages/wujie-core/src/proxy.ts#L19-L35

但是不知道具体遇到了什么场景，需要这样设计，我目前粗鄙的见解是因为 location.href 是可以随便跳的，跳子应用的时候正常，跳外部的网站，或者下载的时候，会导致预期行为不一致，所以用 iframe 去进行替换。
