### ISSUE TITLE
子应用引用的第三方组件，样式丢失

### ISSUE THREAD

**Issue by 18610509683** [Tencent/wujie#47]
典型如 element ui

**Comment by yiludege** [comment]
这样描述我也太难解决了吧，demo 里面用的就是 element ui，目前已知一个 bug 就是 异步组件的样式在组件第二次渲染的时候可能会丢失 具体可查看 #19 

可以详细描述一下你的场景，或者你 fork 一份我的代码，在我demo里面复现一下这个问题？
