### ISSUE TITLE
子应用无法获取当前应用中的window.xx全局变量

### ISSUE THREAD

**Issue by kervin521** [Tencent/wujie#471]
**描述bug**
清晰准确的描述bug

**如何复现**
给出详细的复现步骤
1、第一步 xxx
2、 第二步 xxx

**错误截图**
如果有可以将截图带上

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by gadzan** [comment]
子应用获取主应用的全局变量

```js
window.parent.xxx;
```

参考文档：
https://wujie-micro.github.io/doc/guide/communication.html#window-%E9%80%9A%E4%BF%A1

**Comment by zxw394** [comment]
+1
