### ISSUE TITLE
子应用的iframe, 其window.parent指向的是主应用的window，而非子应用的window

### ISSUE THREAD

**Issue by fanqi7** [Tencent/wujie#475]

**Comment by yiludege** [comment]
发现无论如何都无法侵入到子应用的iframe内部去修改 window.parent 的属性，所以可能需要iframe做一下兼容

先通过window.parent.frames 拿到所有子应用的iframe

然后iframe.name比对获取到所属的 子应用的iframe

最后 window.parent = iframe.contentWindow 重新覆盖设置

**Comment by fanqi7** [comment]
@yiludege
