### ISSUE TITLE
多页面应用接入问题

### ISSUE THREAD

**Issue by maorunjie-2019** [Tencent/wujie#476]
接入多页面应用如何保持路由同步？

**Comment by yiludege** [comment]
用 sync 有什么问题吗

**Comment by maorunjie-2019** [comment]
我说的是多页面应用不是单页面应用，比如服务端渲染的这种项目好像不支持吧

> 用 sync 有什么问题吗

**Comment by maorunjie-2019** [comment]
> 用 sync 有什么问题吗

服务端渲染的这种老项目没有前端路由，只能每次去后端请求新的页面，这种项目该怎么接入wujie呢？
