### ISSUE TITLE
custom elements 接入wujie不渲染

### ISSUE THREAD

**Issue by maorunjie-2019** [Tencent/wujie#478]
**描述bug**
custom elements 接入wujie不渲染

**如何复现**
给出详细的复现步骤
自定义元素并在页面使用，子应用单独运行，正常展示custom elements ；
接入wujie custom elements不展示

**错误截图**
![image](https://user-images.githubusercontent.com/55609793/228146633-3c3dca8f-3ddd-470e-bdf2-e84659ad51d1.png)
![image](https://user-images.githubusercontent.com/55609793/228146649-577a0c5b-da1b-4337-9b54-bd7ef94aff09.png)

**Comment by maorunjie-2019** [comment]
这里貌似需要把主应用的window. customElements代理到子应用

**Comment by yiludege** [comment]
我这里可以正常显示呢，你把你的demo贴上来

**Comment by zhoukekestar** [comment]
确实存在这个问题，对于一些不太复杂的场景，可以对老的 customElements 做替换处理来正确渲染。
可以参考：https://gist.github.com/zhoukekestar/21788dc4dda81832e91ba34421e69426
