### ISSUE TITLE
wangeditor QuillEditor富文本无法正常使用

### ISSUE THREAD

**Issue by 1393983569** [Tencent/wujie#479]
**wangeditor**
无法修改 解决后 又出现了无法复制粘贴

**QuillEditor**
无法使用工具栏，点击后控制台报错

**Comment by yiludege** [comment]
对于 wangeditor 试试这样写插件：

```javascript
  plugins: [
    {
      jsBeforeLoaders: [
        {
          content: `window.Selection = window.parent.Selection`,
        },
      ],
      jsLoader: (code) => {
        return code
          .replace("n.isCollapsed", "n.baseOffset === n.focusOffset")
          .replace("n.collapsed", "n.startOffset === n.endOffset");
      },
    },
  ],

```

## 具体原理：
1、子应用运行在 iframe内，dom在主应用的shadowdom中，当选中文字时，在主应用监听selectionchange，并且通过 document.getSelection()获取选中的selection，在wangEditor中 会判断这个 selection instanceof window.Selection，很明显主应用的selection 不可能是 iframe 里面window Selection的实例，所以干脆将主应用的 Selection赋值给 iframe 的 Selection 

2、shadowDom 大坑，详见 [stackoverflow](stackoverflow)，在shadowDom中 Selection.isCollapsed永远为true，相当于永远没有选中，所以只能修改 wangEditor 的代理，让取代读取 isCollapsed 为 baseOffset 和 focusOffset的对比，就知道是否选中了文字了

## 注意：
n.isCollapsed 和  n.collapsed 相当于是做wangEditor 压缩代码的替换，具体代码在这个地方：
![image](https://user-images.githubusercontent.com/19788268/228786760-844daf8b-ca27-4efb-a76e-f171f41b6320.png)



## 最终效果可用：

![image](https://user-images.githubusercontent.com/19788268/228783829-5e0291c0-d8ef-4f8b-bbcb-2347d8742374.png)

**Comment by bch110112** [comment]
复制粘贴还是不行

**Comment by yiludege** [comment]
是的，在看

**Comment by yiludege** [comment]
发现问题了，又是 instanceof 的问题，wangEditor有这么一行代码：
```javascript
l instanceof DataTransfer
```
在无界中运行永远为false，因为dom是主应用的，里面的dataTransfer 永远不可能是 iframe 的 DataTransfer实例，而是外面主应用的，所以完整的plugins应该是：
```javascript
plugins: [
    {
      jsBeforeLoaders: [
        {
          content: `window.Selection = window.parent.Selection; window.DataTransfer = window.parent.DataTransfer`,
        },
      ],
      jsLoader: (code) => {
        return code
          .replace("n.isCollapsed", "n.baseOffset === n.focusOffset")
          .replace("n.collapsed", "n.startOffset === n.endOffset");
      },
    },
  ]
```

**Comment by cgbin24** [comment]
子应用开启降级模式时依旧无法解决，即子应用设置【degrade: true】时这个问题同样存在，应该如何处理呢

**Comment by cgbin24** [comment]
> 发现问题了，又是 instanceof 的问题，wangEditor有这么一行代码：
> 
> ```js
> l instanceof DataTransfer
> ```
> 
> 在无界中运行永远为false，因为dom是主应用的，里面的dataTransfer 永远不可能是 iframe 的 DataTransfer实例，而是外面主应用的，所以完整的plugins应该是：
> 
> ```js
> plugins: [
>     {
>       jsBeforeLoaders: [
>         {
>           content: `window.Selection = window.parent.Selection; window.DataTransfer = window.parent.DataTransfer`,
>         },
>       ],
>       jsLoader: (code) => {
>         return code
>           .replace("n.isCollapsed", "n.baseOffset === n.focusOffset")
>           .replace("n.collapsed", "n.startOffset === n.endOffset");
>       },
>     },
>   ]
> ```

子应用开启降级模式时依旧无法解决，即子应用设置【degrade: true】时这个问题同样存在，应该如何处理呢

**Comment by bch110112** [comment]
富文本里的内容ctrl+c 无法复制到粘贴板，麻烦看下

**Comment by yiludege** [comment]
> 富文本里的内容ctrl+c 无法复制到粘贴板，麻烦看下

我这边好像没啥问题，无法复制到粘贴板指的是什么呢

**Comment by yilidan** [comment]
> > 富文本里的内容ctrl+c 无法复制到粘贴板，麻烦看下
> 
> 我这边好像没啥问题，无法复制到粘贴板指的是什么呢

开启降级模式之后，复制粘贴会无效，输入连续数字，光标会跑到前面

**Comment by MeghanAndrade** [comment]
> > 富文本里的内容ctrl+c 无法复制到粘贴板，麻烦看下
> 
> 我这边好像没啥问题，无法复制到粘贴板指的是什么呢

请问下您使用的wangeditor 是哪个版本呢，5.1.22 复制粘贴会有问题

**Comment by 1393983569** [comment]
> 发现问题了，又是 instanceof 的问题，wangEditor有这么一行代码：
> 
> ```js
> l instanceof DataTransfer
> ```
> 
> 在无界中运行永远为false，因为dom是主应用的，里面的dataTransfer 永远不可能是 iframe 的 DataTransfer实例，而是外面主应用的，所以完整的plugins应该是：
> 
> ```js
> plugins: [
>     {
>       jsBeforeLoaders: [
>         {
>           content: `window.Selection = window.parent.Selection; window.DataTransfer = window.parent.DataTransfer`,
>         },
>       ],
>       jsLoader: (code) => {
>         return code
>           .replace("n.isCollapsed", "n.baseOffset === n.focusOffset")
>           .replace("n.collapsed", "n.startOffset === n.endOffset");
>       },
>     },
>   ]
> ```
复制粘贴可以了，但是还是有点小问题，无法选中文字后使用 加粗、改变背景颜色、字体颜色、下划线工具，无法选中删除。


https://user-images.githubusercontent.com/42171813/229428021-475efd29-e3c5-4e3c-9def-5a119d89f2ce.mp4

**Comment by yiludege** [comment]
目前用下面这个plugins 在降级和非降级似乎都挺好用的

plugins: [
    {
      jsBeforeLoaders: [
        {
          callback: (appWindow) => {
            Object.defineProperties(appWindow, {
              Selection: {
                get: () =>
                  appWindow.__WUJIE.degrade
                    ? appWindow.__WUJIE.document.defaultView.Selection
                    : appWindow.parent.Selection,
              },
              DataTransfer: {
                get: () =>
                  appWindow.__WUJIE.degrade
                    ? appWindow.__WUJIE.document.defaultView.DataTransfer
                    : appWindow.parent.DataTransfer,
              },
            });
          },
        },
      ],
      jsLoader: (code) => {
        return code
          .replace("e instanceof t.Node", "e instanceof (window.__WUJIE.degrade ? window.Node : t.Node)")
          .replace("n.isCollapsed", "n.baseOffset === n.focusOffset")
          .replace("n.collapsed", "n.startOffset === n.endOffset");
      },
    },
  ],

**Comment by bch110112** [comment]
https://user-images.githubusercontent.com/12929563/229670148-da524e67-b829-49d9-a6a9-7e1a0ebff995.mp4


鼠标选中的内容无法复制，ctrl+a就可以

**Comment by 1393983569** [comment]
> 鼠标选中的内容无法复制，ctrl+a就可以
> 
> ![image](https://user-images.githubusercontent.com/12929563/229670393-94c6c704-e6c4-4cf1-b0b9-e0cd24b897a4.png)

@yiludege 我也遇到了同样的问题

**Comment by 1393983569** [comment]
@yiludege 大佬帮忙看看啊，后台系统基本都有富文本，这个功能还是挺重要的

**Comment by peak1024** [comment]
@1393983569 解决了么

**Comment by 1393983569** [comment]
> @1393983569 解决了么

目前无解

**Comment by laotou** [comment]
火狐下，无解

**Comment by wxwzl** [comment]
> 目前用下面这个plugins 在降级和非降级似乎都挺好用的，wangEditor 版本：5.1.23
> 
> ```js
> plugins: [
>     {
>       jsBeforeLoaders: [
>         {
>           callback: (appWindow) => {
>             Object.defineProperties(appWindow, {
>               Selection: {
>                 get: () =>
>                   appWindow.__WUJIE.degrade
>                     ? appWindow.__WUJIE.document.defaultView.Selection
>                     : appWindow.parent.Selection,
>               },
>               DataTransfer: {
>                 get: () =>
>                   appWindow.__WUJIE.degrade
>                     ? appWindow.__WUJIE.document.defaultView.DataTransfer
>                     : appWindow.parent.DataTransfer,
>               },
>             });
>           },
>         },
>       ],
>       jsLoader: (code) => {
>         return code
>           .replace("e instanceof t.Node", "e instanceof (window.__WUJIE.degrade ? window.Node : t.Node)")
>           .replace("n.isCollapsed", "n.baseOffset === n.focusOffset")
>           .replace("n.collapsed", "n.startOffset === n.endOffset");
>       },
>     },
>   ],
> ```

并不行啊

**Comment by laotou** [comment]
该邮箱已经转发至阿里去邮

**Comment by wxwzl** [comment]
> 目前用下面这个plugins 在降级和非降级似乎都挺好用的，wangEditor 版本：5.1.23
> 
> ```js
> plugins: [
>     {
>       jsBeforeLoaders: [
>         {
>           callback: (appWindow) => {
>             Object.defineProperties(appWindow, {
>               Selection: {
>                 get: () =>
>                   appWindow.__WUJIE.degrade
>                     ? appWindow.__WUJIE.document.defaultView.Selection
>                     : appWindow.parent.Selection,
>               },
>               DataTransfer: {
>                 get: () =>
>                   appWindow.__WUJIE.degrade
>                     ? appWindow.__WUJIE.document.defaultView.DataTransfer
>                     : appWindow.parent.DataTransfer,
>               },
>             });
>           },
>         },
>       ],
>       jsLoader: (code) => {
>         return code
>           .replace("e instanceof t.Node", "e instanceof (window.__WUJIE.degrade ? window.Node : t.Node)")
>           .replace("n.isCollapsed", "n.baseOffset === n.focusOffset")
>           .replace("n.collapsed", "n.startOffset === n.endOffset");
>       },
>     },
>   ],
> ```

在safari浏览器 有时候可以，有时候不可以。不可以的时候我看节点，这些插件都没有执行，可以的时候safari浏览器贼卡，控制台都打不开

**Comment by lujiaxu111** [comment]
@1393983569现在好了吗

**Comment by lujiaxu111** [comment]
@伊鲁格 我点击富文本编辑器时有时候获取不到输入的内容 输入空格的时候富文本编辑器的内容会清空

**Comment by lujiaxu111** [comment]
> 对于 wangeditor 尝试这样写插件：
> 
> ```js
>   plugins: [
>     {
>       jsBeforeLoaders: [
>         {
>           content: `window.Selection = window.parent.Selection`,
>         },
>       ],
>       jsLoader: (code) => {
>         return code
>           .replace("n.isCollapsed", "n.baseOffset === n.focusOffset")
>           .replace("n.collapsed", "n.startOffset === n.endOffset");
>       },
>     },
>   ],
> ```
> 
> ## 具体原理：
> 1、子应用运行在iframe内，dom在主应用的shadowdom中，选举中文字时，在主应用监听selectionchange，并且通过document.getSelection()获取选中的选择，在wangEditor中会判断这个选择窗口实例。 Selection，很明显主应用的选择不可能是 iframe 里面 window Selection 的实例，所以干脆将主应用的 Selection 赋值给 iframe 的 Selection
> 
> 2、shadowDom大坑，参见[stackoverflow](https://stackoverflow.com/questions/68882638/why-is-selection-iscollapsed-always-true-in-a-shadow-dom)，在shadowDom中Selection.isCollapsed永远为true，相反修改永远没有选中，所以只能用wangEditor的代码，读取让isCollapsed修改成baseOffset和focusOffset的对比，就知道是否选中了文字了
> 
> ## 注意：
> n.isCollapsed 和 n.collapsed 实际上是做wangEditor 压缩代码的替换，具体代码在这个位置： ![图像](https://user-images.githubusercontent.com/19788268/228786760-844daf8b-ca27-4efb-a76e-f171f41b6320.png)
> 
> ## 最终达到的效果：
> ![图像](https://user-images.githubusercontent.com/19788268/228783829-5e0291c0-d8ef-4f8b-bbcb-2347d8742374.png)

你demo中vue配置的嵌入我的主应用没有任何问题 ，但是我自己的子应用嵌入之后就不能更改文字颜色 也不能复制粘贴，我用的vite+vue+t-design

**Comment by it-Hanwener** [comment]
有解决的方案吗？各位哥哥们~

**Comment by laotou** [comment]
该邮箱已经转发至阿里去邮

**Comment by gyt95** [comment]
> 目前用下面这个plugins 在降级和非降级似乎都挺好用的，wangEditor 版本：5.1.23
> 
> ```js
> plugins: [
>     {
>       jsBeforeLoaders: [
>         {
>           callback: (appWindow) => {
>             Object.defineProperties(appWindow, {
>               Selection: {
>                 get: () =>
>                   appWindow.__WUJIE.degrade
>                     ? appWindow.__WUJIE.document.defaultView.Selection
>                     : appWindow.parent.Selection,
>               },
>               DataTransfer: {
>                 get: () =>
>                   appWindow.__WUJIE.degrade
>                     ? appWindow.__WUJIE.document.defaultView.DataTransfer
>                     : appWindow.parent.DataTransfer,
>               },
>             });
>           },
>         },
>       ],
>       jsLoader: (code) => {
>         return code
>           .replace("e instanceof t.Node", "e instanceof (window.__WUJIE.degrade ? window.Node : t.Node)")
>           .replace("n.isCollapsed", "n.baseOffset === n.focusOffset")
>           .replace("n.collapsed", "n.startOffset === n.endOffset");
>       },
>     },
>   ],
> ```

这种方式可以复制粘贴，可以修改，可以ctrl+a全部删除，但是只能从最后一行单个单个文字删除，不能选中部分文字删除，也不能选中部分文字加粗。点击加粗后，只能是后续输入的文字生效。如何解决？

**Comment by loser-or-no** [comment]
> > @gyt95 试下这个插件呢，`不能选中部分文字删除，也不能选中部分文字加粗` 目测是 isCollapsed 的问题：https://wujie-polyfill.github.io/doc/plugins/selection.html
> 
> 感谢，之前试过。我用的是 Vue3 ，根据文档我把这个 plugin 加在 组件上，结果无效。刚才我尝试改为加在 setupApp 函数的 plugins 参数里，才成功。

大佬可以提供下 setupApp使用得代码片段吗

**Comment by laotou** [comment]
该邮箱已经转发至阿里去邮

**Comment by loser-or-no** [comment]
> **wangeditor** 无法修改 解决后 又出现了无法复制粘贴
> 
> **QuillEditor** 无法使用工具栏，点击后控制台报错
老哥这边可以解决了吗

**Comment by loser-or-no** [comment]
> > 富文本里的内容ctrl+c 无法复制到粘贴板，麻烦看下
> 
> 我这边好像没啥问题，无法复制到粘贴板指的是什么呢
> 
>  2023-03-31.17.44.51.mov

复制完之后，删除完全部得内容输入，中文输入法，首个字母不会触发输入法。光标也会自动消失

**Comment by laotou** [comment]
没解决，换了，不用无界了，换了头条的garfish,在我这里比无界，还有京东那个都稳定多了，已经生产环境上了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月8日(周三) 上午10:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tencent/wujie] wangeditor QuillEditor富文本无法正常使用 (Issue #479)




   
富文本里的内容ctrl+c 无法复制到粘贴板，麻烦看下
  
我这边好像没啥问题，无法复制到粘贴板指的是什么呢
 
2023-03-31.17.44.51.mov
  
复制完之后，删除完全部得内容输入，中文输入法，首个字母不会触发输入法。光标也会自动消失

**Comment by homestylew** [comment]
> 目前用下面这个plugins 在降级和非降级似乎都挺好用的，wangEditor 版本：5.1.23
> 
> ```js
> plugins: [
>     {
>       jsBeforeLoaders: [
>         {
>           callback: (appWindow) => {
>             Object.defineProperties(appWindow, {
>               Selection: {
>                 get: () =>
>                   appWindow.__WUJIE.degrade
>                     ? appWindow.__WUJIE.document.defaultView.Selection
>                     : appWindow.parent.Selection,
>               },
>               DataTransfer: {
>                 get: () =>
>                   appWindow.__WUJIE.degrade
>                     ? appWindow.__WUJIE.document.defaultView.DataTransfer
>                     : appWindow.parent.DataTransfer,
>               },
>             });
>           },
>         },
>       ],
>       jsLoader: (code) => {
>         return code
>           .replace("e instanceof t.Node", "e instanceof (window.__WUJIE.degrade ? window.Node : t.Node)")
>           .replace("n.isCollapsed", "n.baseOffset === n.focusOffset")
>           .replace("n.collapsed", "n.startOffset === n.endOffset");
>       },
>     },
>   ],
> ```

选择文字以后，对文字进行加粗这些没有效果

**Comment by homestylew** [comment]
> 有点小问题，无法选中文字后

我也遇到了，请问解决了吗
