### ISSUE TITLE
可不可以提供vite构建工具为主应用

### ISSUE THREAD

**Issue by wanglihui0608** [Tencent/wujie#48]
可不可以提供vite构建工具为主应用？

**Comment by yiludege** [comment]
这个和打包框架没有关系的，可以之间参考vue为主应用？

**Comment by wanglihui0608** [comment]
主应用在本地开时
1. 用`webpack`处理`iframe`跨域如下：
``` js
devServer: {
    headers: {
      "Access-Control-Allow-Origin": "*",
    },
}
```
可以解决`iframe`
2. `vite`处理`iframe`跨域如下：
``` js
// vite.config.js
server: {
   headers: {
      'Access-Control-Allow-Origin': '*',
    },
    cors: true
}
```
不可以解决`iframe`
![image](https://user-images.githubusercontent.com/22893139/183904500-72814ea9-2288-4f26-aff0-8936d81d5734.png)

**Comment by yiludege** [comment]
有一种特殊情况，初始化 子应用的 iframe 的时候加载了主应用的部分js，这种情况可以采用在**主应用**的 html 的 head 里最前面放入一个`<script> if(__POWERED_BY_WUJIE__) window.stop </script> 来排除

除了这个框架肯能导致的问题，其他跨域问题前端应该都能排除出来

**Comment by gaofeng222** [comment]
请问讨论的问题解决了吗，可以用vite作为主引用吗

**Comment by yiludege** [comment]
跨域问题不是微前端的问题，看 #51 ，主子都是 vite 应用也可以正常工作，我司内部大量 vite 主应用在跑，后续我再出一个demo 来指导用户怎么做。
