### ISSUE TITLE
官网示例的弹窗表现异常，样式错乱

### ISSUE THREAD

**Issue by heikabujianai** [Tencent/wujie#480]
第一步
  进入官网示例
  https://wujie-micro.github.io/demo-main-vue/all?react16=%2Fdemo-react16%2Fhome&react17=%2Fdemo-react17%2Fhome&vue2=%2Fdemo-vue2%2F%23%2Fhome&vue3=%2Fdemo-vue3%2Fhome&vite=%2Fdemo-vite%2Fhome&angular12=%2Fdemo-angular12
第二步
 点击第一个react应用的弹窗
第三步
 下滑看到 打开antd弹窗下的 open modal按钮
第四步
 点击，能看到错乱的样式

**Comment by yiludege** [comment]
忘了发最新版本了，已经修复

**Comment by heikabujianai** [comment]
还是这个页面
https://wujie-micro.github.io/demo-main-vue/all?react16=%2Fdemo-react16%2Fhome&react17=%2Fdemo-react17%2Fhome&vue2=%2Fdemo-vue2%2F%23%2Fhome&vue3=%2Fdemo-vue3%2Fhome&vite=%2Fdemo-vite%2Fhome&angular12=%2Fdemo-angular12

1、弹窗关闭的时候，子应用的滚动条会重置到顶部
2、最后一个angular12 的子应用的背景图扩散到主应用了
