### ISSUE TITLE
使用 wujie 嵌套 2 层： 升级到 1.0.12（13），最底层应用无法正常展示。

### ISSUE THREAD

**Issue by magnnus** [Tencent/wujie#487]
##  详情

主应用 A （react 17）使用 wujie-react
子应用 B （vue2）使用 wujie-vue2 - 对于 C 来说，B 是它的主应用。
子应用 C （react 17)

其中嵌套关系如下：**A 嵌套 B， B 嵌套 C** （并不是 A 嵌套 B、C）。

但是自从一次意外升级到 1.0.12 ，应用 C 就不显示了，也不报错。

从浏览器控制台看 iframe 元素，是没有加载 C 的部分 JS 资源的。

其中 C 应用对应的 html 如下， js 资源只执行到   `window.routerBase = "/apps/requirement/"` 这一行，后续就不在有 js 资源处理了。

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no,viewport-fit=cover"
    />
    <title>需求</title>
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
    <meta name="referrer" content="no-referrer" />
    <link rel="stylesheet" href="/apps/requirement/umi.css" />
    <script>
      window.routerBase = "/apps/requirement/";
    </script>
    <script src="/apps/requirement/@@/devScripts.js"></script>
    <script>
      //! umi version: 3.5.35
    </script>
  </head>
  <body>
    <div id="root"></div>
    <p style="display: none">
      Thu Mar 30 2023 20:11:58 GMT+0800 (中国标准时间)
    </p>

    <script src="/apps/requirement/umi.js"></script>
  </body>
</html>
```

##  应用 A 升级到 1.0.12（13）

无法正常渲染 C。B 和 A 使用相同版本。

##  应用 A 使用 1.0.6 

可以正常展示。B 和 A 使用相同版本。

**Comment by magnnus** [comment]
通过在应用 B 中，配置 plugins - jsLoader, 观测到后续 js 并没有加载，network 也没有请求。

**Comment by magnnus** [comment]
目前测试，主要跟 主应用 A 的版本有关，从 1.0.11 开始出现问题。

**Comment by AYWK** [comment]
1.011版本的修改，这里不直接引用原来的iframeWindow，在多层渲染时候，调用__WUJIE_RAW_DOCUMENT_QUERY_SELECTOR__会使用顶层的iframe的contentWindow而不是当前的contentWindow，所以找不到渲染dom了
<img width="1607" alt="image" src="https://user-images.githubusercontent.com/25224101/229073146-48ad6dcf-2b80-4be3-b5b4-dab17563db68.png">

**Comment by yiludege** [comment]
嗯，我已经定位到这个问题了，今天就发版出来
