### ISSUE TITLE
vant 的样式在无界中没有正常显示

### ISSUE THREAD

**Issue by shenhaoguangDayDayUp** [Tencent/wujie#488]
**描述bug**
我单独运行子应用 vite4 + vue3 + vant4,vant组件样式正常显示,当我嵌套进 wujie后,vant 样式就不正常显示了,
**如何复现**
运行demo 就可以看到问题了

**错误截图**
![4881680229081_ pic](https://user-images.githubusercontent.com/17617821/229015199-9f9bdf44-612b-4435-9640-ab57063b64d8.jpg)

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度
https://github.com/shenhaoguangDayDayUp/wujie-demo

**Comment by yiludege** [comment]
试试这个插件呢
```javascript
  plugins: [
    {
      patchElementHook(element, iframeWindow) {
        if (element.nodeName === "STYLE") {
          element.insertAdjacentElement = function (_position, ele) {
            iframeWindow.document.head.appendChild(ele);
          };
        }
      },
    },
  ],
```
我这边看起来是正常了

![image](https://user-images.githubusercontent.com/19788268/229681504-8c4d3f77-e9ea-44e8-8c9d-fefa18ddb368.png)
