### ISSUE TITLE
子应用开启降级后，wangeditor富文本编辑器无法正常工作

### ISSUE THREAD

**Issue by cgbin24** [Tencent/wujie#489]
**描述bug**
1、子应用中使用了wangeditor富文本编辑器
2、子应用已开启降级模式`【degrade: true】`
3、子应用中的`wangeditor`编辑器无法复制、粘贴文本，且在输入、删除内容时光标始终处于输入框头部显示

目前已提供未降级修复方案【地址如下】，但降级后应该如何处理呢
[wangeditor QuillEditor富文本无法正常使用 #479](https://github.com/Tencent/wujie/issues/479#issue-1643390273)

**错误截图**
![error](https://user-images.githubusercontent.com/46283404/229042527-498ee08d-3a3f-466c-bea4-17a07aa6984d.gif)

**Comment by cgbin24** [comment]
@yiludege

**Comment by cgbin24** [comment]
#### 问题补充：
4、工具栏无法正常工作，会被频繁禁用，甚至始终处于禁用状态
5、输入的内容无法删除
6、无法通过读取到输入内容【子应用 **保活状态** 下频现】，推测可能与缓存有关系，浏览器无痕模式下可短暂解决

**Comment by yiludege** [comment]
重复 #479  关闭

**Comment by ZhangYC193** [comment]
> #### 问题补充：
> 4、工具栏无法正常工作，会被频繁禁用，甚至始终处于禁用状态 5、输入的内容无法删除 6、无法通过读取到输入内容【子应用 **保活状态** 下频现】，推测可能与缓存有关系，浏览器无痕模式下可短暂解决

有解决吗 @cgbin24
