### ISSUE TITLE
shadow dom兼容性问题

### ISSUE THREAD

**Issue by maorunjie-2019** [Tencent/wujie#490]
在micro-app官网声称：shadowDOM具有更好的隔离性，但一些框架(如React)对shadowDOM的兼容性不好，请谨慎使用。

想请问下大佬，wujie直接采用 shadow dom就没有框架兼容性问题吗？

**Comment by yiludege** [comment]
群里面小伙伴的回答
![image](https://user-images.githubusercontent.com/19788268/229083495-b0443913-1cd8-4802-a763-a1d71cd5e42c.png)
