### ISSUE TITLE
子应用使用 Vue3 + Naive UI，出现【内容左移】现象

### ISSUE THREAD

**Issue by cgbin24** [Tencent/wujie#497]
**描述bug**
1、子应用使用 `Vue3 + Naive UI` 
2、控制台调试 或者 窗口大小较小时，使用 `Naive UI` 的模态框【Modal】出现内容左移现象
3、据排查后，发现子应用的 `html` 标签上被添加了 `margin-right` 值

**复现**
> 错误复现详见仓库代码

1、`npm run wujie:install`
2、 `npm run dev`
3、参照下方演示视频复现错误

**错误展示**

https://user-images.githubusercontent.com/46283404/229682792-c44ad5c3-8f81-4a63-9787-2ee83887967b.mp4

![image](https://user-images.githubusercontent.com/46283404/229684461-f74b08d0-9f8a-4c4c-b9e2-cf01ed6b4021.png)

**复现仓库**
[复现仓库](https://github.com/cgbin24/wujie-demo)

**Comment by yiludege** [comment]
这个不是wujie框架做的，目前可以将body 的marign-rignt 写死 important ？

**Comment by cgbin24** [comment]
直接写死是可以的，刚刚又看了 Naive UI 官网演示，确实UI库自己加的😅
