### ISSUE TITLE
antd-vue 下拉框弹窗位置异常，程序崩溃

### ISSUE THREAD

**Issue by Wenbile** [Tencent/wujie#499]
![image](https://user-images.githubusercontent.com/42694062/230253998-17e90a0c-20ab-4411-a511-bccfb20a439c.png)

**Comment by Wenbile** [comment]
不作为子应用打开时，下拉框在最底部能够正常向上显示，而作为子应用时
![image](https://user-images.githubusercontent.com/42694062/230254171-f027ddf7-b35d-4cfc-94ac-93f1bf99ca63.png)
，下拉框会向下导致滚动条拉长了，然后程序崩溃了。下拉框表现不一致

**Comment by Wenbile** [comment]
是因为在无界中，antd vue的下拉框定位无法识别到浏览器边缘导致的吗？

**Comment by 5265liu** [comment]
这个貌似有两种模式下拉框，你不要选用 在body下面加载dom试试

**Comment by mengxianghan** [comment]
> 不作为子应用打开时，下拉框在最底部能够正常向上显示，而作为子应用时 ![image](https://user-images.githubusercontent.com/42694062/230254171-f027ddf7-b35d-4cfc-94ac-93f1bf99ca63.png) ，下拉框会向下导致滚动条拉长了，然后程序崩溃了。下拉框表现不一致

你好，你那的这个问题解决了吗？

**Comment by Wenbile** [comment]
> 

![image](https://user-images.githubusercontent.com/42694062/233817314-ace2cac4-8a90-4908-b84c-5ad6afde57e5.png)
我目前使用的是这个解决方案

**Comment by Wenbile** [comment]
个人觉得出现问题的原因是：比如导航栏是100px，子应用高度是900px。而弹窗计算位置的时候，相对定位的父元素是视窗的最顶部，所以在距顶部超过900px的位置打开弹窗的时候，弹窗计算出的位置相当于已经超出了屏幕范围，导致异常。

**Comment by mengxianghan** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/42694062/233817314-ace2cac4-8a90-4908-b84c-5ad6afde57e5.png) 我目前使用的是这个解决方案

谢谢，我暂时也先使用这个方案
