### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by JC-Guy** [Tencent/wujie#502]
**描述bug**
主项目： vue3+vite4+ wujie-vue3@1.0.14
子项目:  vue2+webpack4+ wujie-vue2@1.0.14
本地调试都是127.0.0.1 是没有跨域问题的，但是上了测试环境，域名不同后，就会报跨域问题
子项目webpack配置如下
![image](https://user-images.githubusercontent.com/40263378/230330606-8646c87d-0a78-45db-97a6-fdb7828ba123.png)

![image](https://user-images.githubusercontent.com/40263378/230330732-5fe8d73b-3373-47be-a1df-74db28a2bb4f.png)

期望： 不报错
 应当如何配置，如何解决这个问题？

**Comment by JC-Guy** [comment]
ok ，确实是nginx配置问题，添加配置后跨域问题就没有了

**Comment by 13407864574** [comment]
你好，我的情况和你类似，访问本地项目没问题，放到服务器上,服务器配置开启了跨域处理'Access-Control-Allow-Origin'：‘*’ 访问服务器，静态资源还是报跨域 请问你解决了吗

**Comment by 5265liu** [comment]
我也nginx配置了还是不行

**Comment by 5265liu** [comment]
> ok ，确实是nginx配置问题，添加配置后跨域问题就没有了

麻烦问下你的nginx怎么配的我也是配了nginx还不行

**Comment by LeonIsACoder** [comment]
你好，我的本地环境也报跨域请求，该配的都配了，也不知道是什么原因

**Comment by Crazysanlang** [comment]
> > ok ，确实是nginx配置问题，添加配置后跨域问题就没有了
> 
> 麻烦问下你的nginx怎么配的我也是配了nginx还不行

解决了吗

**Comment by shihaobo** [comment]
解决了么

**Comment by kkkkkkkkkw** [comment]
> 
请问解决了吗

**Comment by qzo123** [comment]
> 你好，我的本地环境也报跨域请求，该配的都配了，也不知道是什么原因

你的解决了吗？怎么解决的啊？

**Comment by xiaozhou-amazing** [comment]
> ok ，确实是nginx配置问题，添加配置后跨域问题就没有了

老板 你nginx怎么配置的？可否截个图看看

**Comment by wen403** [comment]
麻了nginx配置还跨域

**Comment by Hopyns** [comment]
> ok ，确实是nginx配置问题，添加配置后跨域问题就没有了

请问，nginx要如何配置，加了下面的配置依然会报XMLHttpRequest的跨域问题
add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
    add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
