### ISSUE TITLE
如果不开启路由同步，会出现什么问题？

### ISSUE THREAD

**Issue by SericXu** [Tencent/wujie#51]
我搭建了一个demo，开启路由同步后，路由后面始终会携带参数。当关闭路由同步后，demo中的效果暂时没发现有什么问题。所以想请教一下，如果关闭后会有什么问题？

主应用和子应用均为vite + vue3。

**Comment by yiludege** [comment]
点击菜单栏到子应用，这个时候子应用假如在页面 a，然后在子应用里面跳转路由到页面 b

如果 sync = false，此时刷新浏览器或者将 url 分享给别人，会发现子应用停留在页面 a 而不是页面 b

如果 sync = true

1、刷新浏览器依然可以停留在路由 b（从浏览器参数读回）
2、将浏览器 url 分享给别人，别人打开后子应用的路由也会在 b

**Comment by SericXu** [comment]
懂了，谢谢
