### ISSUE TITLE
子应用中发出的api请求域名会是子应用的url吗？如果想和主应用域名一致该怎么做

### ISSUE THREAD

**Issue by ChesterBu** [Tencent/wujie#52]

**Comment by yiludege** [comment]
这是一个奇怪的问题，这个分情况讨论吧

1、子应用如果发起的api是绝对地址：“http:xxxx.com/api/xxxx”，那么不管是子应用单独运行还是内嵌在主应用都是这个绝对地址

2、子应用如果发起的api是相对地址：“/api/xxxx”，那么子应用单独运行请求域名是子应用的，内嵌在无界微前端中，host 还是子应用的（子应用运行在 iframe 内，无界在 iframe 内设置了 base 标签来修正相对地址）

如果是情况 2 ，又想子应用内嵌在无界微前端中请求域名是主应用的，那么可以这样做：

a、子应用的 api 请求是 fetch ，可以自定义子应用的 [fetch](https://wujie-micro.github.io/doc/api/startApp.html#fetch)，强制修改 url = host 主应用 + url

b、子应用的 api 请求是 xhr ，那就只能修改子应用的代码，将 url = window.__POWERED_BY_WUJIE__ ?  host 主应用 + url : url 这样可以走主应用的域名
