### ISSUE TITLE
getElementById失效

### ISSUE THREAD

**Issue by geeeger** [Tencent/wujie#523]
**描述bug**
wujie-core代理getElementById直接转成了querySelector，这是不合理的。
同理，其他老api也不应转成querySelector,querySelectorAll。
使用者并不希望本身使用的dom api有变化，除非两个不同级别的api完全兼容。
在我们的使用环境中，dom.id被赋值为一个不合理的字符串（url）,此时getElementById可用，但querySelector无法查询到此id对应dom并报错。

**如何复现**
1. 子应用document.getEelementById('https://www.baidu.com')
2. 主应用代理为iframe.document.querySelector('#https://www.baidu.com')
3. 报DOMException错误

**错误截图**
如果有可以将截图带上

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by dengBox** [comment]
我们使用antv/x6也遇到了类似的问题

**Comment by yiludege** [comment]
https://github.com/Tencent/wujie/pull/547

**Comment by iamzuijiasunyou** [comment]
> #547

大佬，更新到1.0.18，还是有这个问题。 请问修复了吗？
