### ISSUE TITLE
子应用angular，使用service-worker,主应用内报: Failed to register a ServiceWorker

### ISSUE THREAD

**Issue by jeffzing** [Tencent/wujie#527]
**描述bug**
子应用angular，使用service-worker,主应用内报: Failed to register a ServiceWorker
主应用版本：react 16.5.1
子应用版本：angular 14
```
<WujieReact
  name='wujie'
  url='angular子应用地址'
/>
```
**如何复现**
给出详细的复现步骤
1、安装无界v1.0.14,在主应用内使用

2、 访问主应用地址并激活子应用，子应用只加载出部分资源，由子应用service-worker加载的资源报跨域

**错误截图**
![image](https://user-images.githubusercontent.com/12021460/233839978-bb698d33-693a-463d-b42a-e52805dcedc0.png)

**最小复现仓库或者地址**
https://wujie-micro.github.io/doc/wujie/
在输入框输入使用service-worker的angular已允许跨域访问的子应用地址

**Comment by renwofei423** [comment]
@yiludege

**Comment by jeffzing** [comment]
在iframe内加载这个angular应用不会出现这个问题

**Comment by yiludege** [comment]
https://github.com/Tencent/wujie/issues/851#issuecomment-2154711528
