### ISSUE TITLE
主应用菜单点击路由变化问题

### ISSUE THREAD

**Issue by SericXu** [Tencent/wujie#53]
主应用通过点击菜单跳转子应用页面，路由同步开启。
当我再次点击主应用同样的菜单时，会改变路由，后面的参数丢了。

主应用、子应用均为vite+vue3。使用element plus， 菜单组件，开起路由模式

**Comment by SericXu** [comment]
这种情况是不是只有通过控制主应用的菜单点击事件来处理了？

**Comment by yiludege** [comment]
> 当我再次点击主应用同样的菜单时，会改变路由，后面的参数丢了。
1、这个地方有点不明白是什么意思，再次点击主应用同样的菜单指的是之前的子应用对应的菜单吗？
2、子应用是否保活、是否做生命周期适配？

**Comment by SericXu** [comment]
上面描述的不太准确。

![image](https://user-images.githubusercontent.com/50159079/184280646-28bc6eab-4cdd-4577-9e2d-430a3719fc83.png)

第一次点击后如图。

然后f5刷新一下。再次点击（刷新后的页面路由还是上图中的路由）：
![image](https://user-images.githubusercontent.com/50159079/184280927-465c25b2-c84d-438e-a1f9-3ece17898ecf.png)

**Comment by yiludege** [comment]
明白了，demo也是这个现象

这个地方没有关系的，不管是刷新还是分享 url 主应用的路由 /collect 打开都是子应用的这个页面，除了这个默认页面，子应用发生跳转其他路由一定会同步上的

这个地方的行为确实不一致，我后续看一下怎么改进哈

**Comment by GreatAuk** [comment]
@yiludege  这个问题能怎么解决？如果主应用是多标签页的，这种情况就会打开两个同样的标签页（url 不一样，所以认为是不同的标签页）。
