### ISSUE TITLE
 子应用中调用 await navigator!.clipboard.writeText(value) 报错

### ISSUE THREAD

**Issue by gavin-hao** [Tencent/wujie#535]
**描述bug**
子应用中 使用剪切板 api 报错 DOMException: Document is not focused.

建议 将 子应用的 window.navigator 代理到主应用的window；

**Comment by yiludege** [comment]
navigator似乎没办法代理？可以采用 ```window.parent.navigator!.clipboard.writeText(value)```

**Comment by DoubleXm** [comment]
那如果类似这些方法是子应用调用的第三方库中的呢，是不是意味着这个子应用就应该废弃这个第三方库了。

**Comment by gavin-hao** [comment]
> 那如果类似这些方法是子应用调用的第三方库中的呢，是不是意味着这个子应用就应该废弃这个第三方库了。

那估计只能 hack 三方库中的相关方法
