### ISSUE TITLE
官网在线体验模块，部分网站展示效果有问题

### ISSUE THREAD

**Issue by kcfuler** [Tencent/wujie#540]
**描述bug**
官网展示在线体验模块在vuetify 、webpack、vercel、naviui几个展示项目中有显示的问题

**如何复现**
给出详细的复现步骤
环境：
- Microsoft Edge 112.0.1722.68 (正式版本) (64 位)
- Chrome 版本 112.0.5615.138（正式版本） （64 位）
复现步骤
1. 进入https://wujie-micro.github.io/doc/wujie/文档
2. 点击在线体验无界
3. 点击上述网站的对应选项，就会出现显示上的问题。

**错误截图**
如果有可以将截图带上
1. Navie UI
![image](https://user-images.githubusercontent.com/87866012/236195215-fde3ba78-bf67-44a1-8991-241013988f51.png)
2. Vercel
![image](https://user-images.githubusercontent.com/87866012/236195294-2f254bba-3884-496f-9f80-4ad7f7575389.png)
3. Webpack
![image](https://user-images.githubusercontent.com/87866012/236195451-ab01881d-ab0c-4ebb-a322-d24a287d6fb0.png)
4. Vuetify
![image](https://user-images.githubusercontent.com/87866012/236195595-b831a882-dd9a-413a-8baf-af1deab095e9.png)

**最小复现仓库或者地址**
无，是官网的展示问题。

**Comment by ErKeLost** [comment]
这是正常现象 https://github.com/Tencent/wujie/issues/356
