### ISSUE TITLE
子应用页面刷新后，通过浏览器返回按钮返回上一页失败

### ISSUE THREAD

**Issue by sauron0914** [Tencent/wujie#544]
**描述bug**
子应用（spa）页面内跳转几次，刷新后，通过浏览器返回按钮返回上一页，发现title变更，页面未返回

**如何复现**
给出详细的复现步骤
1、第一步  主应用页面A，跳转到子应用页面B，
2、第二步 子应用页面B 跳转到子应用页面C
3、第三步 子应用页面C 内刷新
4、第四步 使用浏览器返回按钮返回上一页，返回失败，未报错

**Comment by lumengling** [comment]
咋决解的
