### ISSUE TITLE
将electron内的vue2作为主应用，子应用为vue2构建的网页时，无界在开发模式可以正常展示，打包后会抛异常

### ISSUE THREAD

**Issue by stack-Yaffel** [Tencent/wujie#548]
**描述bug**
将electron内的vue2作为主应用，子应用为vue2构建的网页时，无界在开发模式可以正常展示，打包后会抛异常，异常如下图，为了排除iframe的影响，我将应用设置强制降级，无效，报错依旧，而通过iframe标签直接加载对应地址，可以成功加载无报错

**如何复现**
给出详细的复现步骤
1、第一步 主应用为electron+vue2,在main.js注册应用，做预加载。
2、 第二步 子应用做生命周期改造
![微信截图_20230516175301](https://github.com/Tencent/wujie/assets/26702164/41f90b8a-04ae-4797-9ba6-25ed3e130f55)

**错误截图**

![image](https://github.com/Tencent/wujie/assets/26702164/a4327f14-da45-4e06-ac74-f0606a416941)

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by yiludege** [comment]
wujie 是不支持 electron 的，采用的是 file://协议，在构造同域沙箱时会出现问题

**Comment by stack-Yaffel** [comment]
> wujie 是不支持 electron 的，采用的是 file://协议，在构造同域沙箱时会出现问题

我采用的是自定义协议，构建参数是标准协议，我采用iframe直接引入是可以正常展示的，不管是同域还是异域。 wujie是否考虑在代码层面支持自定义协议的沙箱？

**Comment by zer0e** [comment]
@stack-Yaffel 遇到了一样的问题，请问题主解决了吗

**Comment by stack-Yaffel** [comment]
@zer0e 没，临时采用iframe+postMessage来处理了，

**Comment by yzend** [comment]
这边遇到了问题，自动一协议去访问其他接口，主要问题还是在于 iframe 的跨域限制导致的不允许访问window的 session 这些属性，只要重新设置下 iframe的src，让他和你主页的地址一样就可以了
例如 主页的 `launcher://production/index.html` 那只要将 iframe 设置成 launcher://production/index.html就可以
```html
<WujieVue
          width="100%"
          height="100%"
          :attrs="{
            src: 'launcher://production/index.html'
          }"
      ...
        />
```

**Comment by yhtt2020** [comment]
同样使在electron自定义协议下开发。遇到的问题是主应用http://协议，子应用ttapp://协议，开发环境下，正常运行。
正式环境下，主应用tsbapp://，子应用ttapp://，主应用和子应用是两个协议。
此时，控制台无报错。但是发现js未被请求。加载应用白屏。

感觉wujie.js很适合被用在electron里面，就差一点了。

**Comment by yhtt2020** [comment]
协议

> 同样使在electron自定义协议下开发。遇到的问题是主应用[http://协议，子应用ttapp://协议，开发环境下，正常运行。](http://%E5%8D%8F%E8%AE%AE%EF%BC%8C%E5%AD%90%E5%BA%94%E7%94%A8ttapp://%E5%8D%8F%E8%AE%AE%EF%BC%8C%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E4%B8%8B%EF%BC%8C%E6%AD%A3%E5%B8%B8%E8%BF%90%E8%A1%8C%E3%80%82) 正式环境下，主应用tsbapp://，子应用ttapp://，主应用和子应用是两个协议。 此时，控制台无报错。但是发现js未被请求。加载应用白屏。
> 
> 感觉wujie.js很适合被用在electron里面，就差一点了。

自定义协议均为标准协议，可以正常执行js，只是做了路径的映射，映射到了本地。也都关闭了跨域。
