### ISSUE TITLE
子应用window.addEventListener失效

### ISSUE THREAD

**Issue by UmbraCi** [Tencent/wujie#549]
子应用原本是iframe潜在主应用中的，使用的postmessage传递消息，现在子应用想改造成wujie的子应用嵌入到父应用中，不想改动业务代码，发现原本在子应用监听postmessage消息的事件监听器全部失效
![image](https://github.com/Tencent/wujie/assets/49011112/abe9dab8-7de4-4656-9e43-c4d793f73c9c)
![image](https://github.com/Tencent/wujie/assets/49011112/7a791a88-e07b-4fb2-8fa7-0f78e62d712d)
子应用是用window.addEventListener('message'绑定事件的，现在所有事件都绑定到父应用去了，window.__WUJIE_RAW_WINDOW__.addEventListener('message', 也是一样：
![image](https://github.com/Tencent/wujie/assets/49011112/c22f61f5-8873-4aab-be57-cfc9421098f0)

![image](https://github.com/Tencent/wujie/assets/49011112/bc9b2cc6-f521-44ef-b665-4ee7834e8d7b)
这种情况难道要全部修改子应用和父应用的交互吗，不想改动postmessage的老代码

**Comment by bigyifeng** [comment]
要监听window.parent  ，子应用的window是被封装过的，你要是用parent获取到主应用的window，然后再监听

**Comment by UmbraCi** [comment]
> 要监听window.parent ，子应用的window是被封装过的，你要是用parent获取到主应用的window，然后再监听

iframe应用原本的父子通讯的方式是postmessage，父应用给子应用发postmessage，子应用监听自己的message事件，怎么能直接监听主应用的window呢

**Comment by taoguili** [comment]
大佬，有解决吗

**Comment by UmbraCi** [comment]
> 大佬，有解决吗

没有

**Comment by yiludege** [comment]
这个地方加一个message？欢迎提一个pr

<img width="578" alt="image" src="https://github.com/Tencent/wujie/assets/19788268/d7072341-8891-4124-80b1-b881b0a89010">

**Comment by UmbraCi** [comment]
> 这个地方加一个message？欢迎提一个pr
> 
> <img alt="image" width="578" src="https://user-images.githubusercontent.com/19788268/239729268-d7072341-8891-4124-80b1-b881b0a89010.png">

这里可以提一个pr，但是担心影响您其他地方的设计，我现在提一个pr试试

**Comment by yiludege** [comment]
> 这里可以提一个pr，但是担心影响您其他地方的设计，我现在提一个pr试试

这个没有影响，你可以本地拉一下代码，然后加上message，改一下demo看看postmessage是否生效，如果OK把代码推过来就好了

**Comment by UmbraCi** [comment]
> > 这里可以提一个pr，但是担心影响您其他地方的设计，我现在提一个pr试试
> 
> 这个没有影响，你可以本地拉一下代码，然后加上message，改一下demo看看postmessage是否生效，如果OK把代码推过来就好了

用example自带的例子试过了，没问题，并且新增了个可选参数用于指定targetWindow，麻烦看下这个PR，第一次提PR不知道合不合规:https://github.com/Tencent/wujie/pull/555

**Comment by UmbraCi** [comment]
> > 这里可以提一个pr，但是担心影响您其他地方的设计，我现在提一个pr试试
> 
> 这个没有影响，你可以本地拉一下代码，然后加上message，改一下demo看看postmessage是否生效，如果OK把代码推过来就好了

今天可以看下PR嘛，有点着急用，3KS

**Comment by UmbraCi** [comment]
> > 这里可以提一个pr，但是担心影响您其他地方的设计，我现在提一个pr试试
> 
> 这个没有影响，你可以本地拉一下代码，然后加上message，改一下demo看看postmessage是否生效，如果OK把代码推过来就好了

我看到Pr被合并了但是我当时没有更新package的version版本，这里发版npm怎么做呢，是否需要我再提个pr更新下版本号

**Comment by yiludege** [comment]
今天发出来哈

**Comment by UmbraCi** [comment]
> 今天发出来哈

不好意思，第一次提pr和这种monorepo的发布形式，请问是让我修改一次版本号嘛，发出来之前需要我再改点东西吗

**Comment by yiludege** [comment]
不用的，我这边统一更新版本

**Comment by UmbraCi** [comment]
> 不用的，我这边统一更新版本

再多问一句，这种monorepo的仓库是packages内的版本号都统一跟根路径的一致嘛，因为我也想把自己其他项目的改为monorepo的仓库，是多个应用嵌套子应用，用pnpm+workspace+wujie的思路

**Comment by yiludege** [comment]
是的，版本我用 lerna-lite 做管理，因为这个支持 pnpm

**Comment by IceEnd** [comment]
@yiludege 大佬，请问这个版本发布了么？目前仍是1.0.16版本。我遇到的差不多，是子应用里嵌入了一个iframe，双方通信全被拦截了。
![image](https://github.com/Tencent/wujie/assets/11556339/c891a4ea-3dc4-4d09-86b7-f1067eadca44)

**Comment by UmbraCi** [comment]
> @yiludege 大佬，请问这个版本发布了么？目前仍是1.0.16版本。我遇到的差不多，是子应用里嵌入了一个iframe，双方通信全被拦截了。 ![image](https://user-images.githubusercontent.com/11556339/241842998-c891a4ea-3dc4-4d09-86b7-f1067eadca44.png)
用pnpm的override覆盖一下，我修复的包：
"pnpm": {
    "overrides": {
      "wujie": "npm:@umbraci/wujie@1.0.17"
    }
  },
  
![image](https://github.com/Tencent/wujie/assets/49011112/66b4de38-31eb-485e-a1c9-43b8d526ac5a)

**Comment by loycoder** [comment]
> > > 这里你可以提一个pr，但是担心影响其他地方的设计，我现在提一个pr尝试
> > 
> > 
> > 这个没有影响，你可以在本地拉一下代码，然后加上message，改一下demo看看postmessage是否生效，如果OK把代码推过来就好了
> 
> 用例子自带的例子试过了，没问题，并且新增了一个用于指定targetWindow的可选参数，麻烦看下这个PR，第一次提PR不知道合不合规：#555

这里引发了其他问题： https://github.com/Tencent/wujie/issues/773

**Comment by Keekuun** [comment]
https://wujie-micro.github.io/demo-main-react/?react17=%2Fdemo-react17%2Fcommunication#/react17 我看了demo里面并没有生效呢

**Comment by promiseMIMI** [comment]
wujie-vue3的模板22版本还没生效呢

**Comment by Tiramisupxl** [comment]
> 要监听window.parent ，子应用的window是被封装过的，你要是用parent获取到主应用的window，然后再监听

这个可以解决，但是用了这个方法后，子应用和主应用都监听到
