### ISSUE TITLE
每次首次加载子应用的背景url链接拼接错误，再次刷新就没事了

### ISSUE THREAD

**Issue by yongdong1997** [Tencent/wujie#551]
![image](https://github.com/Tencent/wujie/assets/54296372/0b6dce89-c922-4439-831a-36d66aacf97c)
正常url是
![image](https://github.com/Tencent/wujie/assets/54296372/a4be3973-8ab4-48b7-a608-01793fbb6d34)

**Comment by yiludege** [comment]
无界并不会修改这个 url 的，如果必现可以提供一个demo出来

**Comment by yongdong1997** [comment]
> 无界并不会修改这个 url 的，如果必现可以提供一个demo出来

现在已经不会了，之前因为是有一处远程脚本修改了document.domain,引起奇奇怪怪的问题，目前已经做了兼容
![image](https://github.com/Tencent/wujie/assets/54296372/ec9d208b-1e1d-403b-b8c9-32b3c7c45076)
