### ISSUE TITLE
wujie error 异常处理

### ISSUE THREAD

**Issue by fandywen** [Tencent/wujie#553]
当报wujie  error的时候，没法捕获异常来做一些额外的操作，请大佬提供一个处理wujie  error异常api给用户调用 [wujie error]: SecurityError
<img width="1349" alt="image" src="https://github.com/Tencent/wujie/assets/22906355/471aa20b-2d23-4a7d-b6df-93cbee9fd84f">

**Comment by yiludege** [comment]
试试这个呢https://wujie-micro.github.io/doc/guide/lifecycle.html#loaderror

<img width="652" alt="image" src="https://github.com/Tencent/wujie/assets/19788268/29aee979-3a85-4a55-9ba0-4d340021e67f">

**Comment by fandywen** [comment]
loaderror&nbsp;这个api不能捕获wujie error，报这个错的时候，子应用还没有加载完成，所以这个api不能满足要求，大佬能不能提供一个在这之前就能捕获异常的API啊










------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月21日(星期天) 下午4:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/wujie] wujie error 异常处理 (Issue #553)





 
试试这个呢https://wujie-micro.github.io/doc/guide/lifecycle.html#loaderror

**Comment by fandywen** [comment]
> 试试这个呢https://wujie-micro.github.io/doc/guide/lifecycle.html#loaderror
> 
> <img alt="image" width="652" src="https://user-images.githubusercontent.com/19788268/239728720-29aee979-3a85-4a55-9ba0-4d340021e67f.png">



> 试试这个呢https://wujie-micro.github.io/doc/guide/lifecycle.html#loaderror
> 
> <img alt="image" width="652" src="https://user-images.githubusercontent.com/19788268/239728720-29aee979-3a85-4a55-9ba0-4d340021e67f.png">

这个api不能捕获wujie error，报这个错的时候，子应用还没有加载完成，所以这个api不能满足要求，大佬能不能提供一个在这之前就能捕获异常的API

![image](https://github.com/Tencent/wujie/assets/22906355/1fabdebf-1b20-4efc-a635-6d55e79be6ec)
![image](https://github.com/Tencent/wujie/assets/22906355/1ac69a87-76f3-4956-8207-048c1942efcf)
