### ISSUE TITLE
父子应用都使用axios，单独运行时请求都没问题，使用无界后子应用的请求无法携带cookie，请问是为什么

### ISSUE THREAD

**Issue by candy7zZ** [Tencent/wujie#559]
父子应用都使用axios，单独运行时请求都没问题，使用无界后子应用的请求无法携带cookie，并且使用iframe方式嵌套子应用的方式时子应用也能正常携带cookie

配置都是最简单的配置，没有跨域的问题

**Comment by yiludege** [comment]
跨域浏览器不会自动携带cookie，需要设置一下 withCredentials: true
