### ISSUE TITLE
子应用使用arco.design组件库打开弹窗问题

### ISSUE THREAD

**Issue by boboiu** [Tencent/wujie#56]
子应用使用arco.design组件库打开弹窗会默认往body插入样式，导致我需要在子应用处理相关问题。在子应用中使用svg就会因为这个问题不出现。

**Comment by yiludege** [comment]
需要描述清楚具体是什么问题，相比子应用单独运行，内嵌在无界中有什么差异？

**Comment by zhangzhenfei** [comment]
无法全屏显示
