### ISSUE TITLE
主应用element ui ，子应用element-plus ，接入后子应用的样式问题

### ISSUE THREAD

**Issue by Crazysanlang** [Tencent/wujie#582]
主应用element ui ，子应用element-plus ，接入后子应用的 样式变量 使用主应用：root的样式，导致颜色变量丢失，有遇到的小伙伴们可以一块讨论下， 怎么解决
![image](https://github.com/Tencent/wujie/assets/26653625/a2f7534e-6bd3-4004-81fd-b2d467cb24a4)

**Comment by Crazysanlang** [comment]
该问题已解决

**Comment by Jason-linjiayu** [comment]
怎么解决的呢

**Comment by ZGH0717** [comment]
同问，这个怎么解决的啊。

**Comment by yiludege** [comment]
这个地方子应用样式应该是不会采用主应用 root 的，因为子应用的变量会以host挂载到子应用容器上，优先级更高啊

**Comment by ZGH0717** [comment]
@yiludege 



> 这个地方子应用样式应该是不会采用主应用 root 的，因为子应用的变量会以host挂载到子应用容器上，优先级更高啊， wujie getPatchStyleElements 函数处理了这个事情

子应用单独访问是有root的，但是作为子应用后就没有加载自己子应用的root了

**Comment by ZGH0717** [comment]
我手动的将element-plus的 css var变量，copy放index.html文件中先临时解决了，但是感觉这是子应用加载样式过程中root加载问题。
