### ISSUE TITLE
弹框内的时间下拉框组件定位异常

### ISSUE THREAD

**Issue by aibayanyu20** [Tencent/wujie#586]
**描述bug**
已经增加了body{position:relative;}也按照#73添加了插件，但是仍然定位是不准确的

**如何复现**
给出详细的复现步骤
1、拉取 https://github.com/mist-design/wujie-demo 代码
2、 使用pnpm i 安装依赖
3 、 启动工程

**错误截图**
<img width="1152" alt="image" src="https://github.com/Tencent/wujie/assets/45655660/69f03ffc-822b-4622-a0a4-1285879f5a27">

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by Zyunchao** [comment]
我遇到了同样的问题，经排查，这个不是定位原因，是因为无界标签的宽高不足，导致内部的 absolute 元素超出部分隐藏。

你这个案例里，我把子应用 body 标签上的 el-popup-parent--hidden 这个类名的 overflow: hidden 去掉后，就可以正常显示了

其他见：https://blog.csdn.net/Wind_waving/article/details/123473622

**Comment by aibayanyu20** [comment]
目前换成了京东的micro-app框架，已经没有这个问题了。但是京东的iframe模式就没有类似这样的问题，稍微有点儿不理解。

**Comment by quqingfei** [comment]
我这个帖子内回复了使用最小成本实现elemet-ui在popper.js内通过代替源码方式实现弹框偏移解决方案，你可以看看。
https://github.com/Tencent/wujie/issues/682#issuecomment-1696111047
