### ISSUE TITLE
preloadApp 和 startApp 重复配置项问题

### ISSUE THREAD

**Issue by 868618** [Tencent/wujie#59]
1、在入口preloadApp的时候写一遍子应用路由

2、在子组件里又要写一遍子应用路由

3、添加和修改的时候容易遗忘，漏改

入口
<img width="536" alt="image" src="https://user-images.githubusercontent.com/23164429/184521869-2876cd8c-8459-48fc-b1ac-9375ab236d59.png">

子组件
<img width="433" alt="image" src="https://user-images.githubusercontent.com/23164429/184521901-02a8d9e7-8b42-4b37-8445-deae0922e565.png">

**Comment by yiludege** [comment]
非常好的问题，这个问题我也很早就注意到了

我考虑一下是不是出一个createApp( option ) api

然后 preloadApp(name)、startApp(name) 就好了，option 统一在 createApp 中填一遍

当然原来的 preloadApp(option)、startApp(option) 用法也支持，只不过是覆盖 createApp( option ) 中的 option

**Comment by yiludege** [comment]
已经实现 createApp api 能力
