### ISSUE TITLE
子应用切换到vite4.0之后，单例模式下main.js中引入的样式丢失

### ISSUE THREAD

**Issue by chenglu4343** [Tencent/wujie#607]
**描述bug**
清晰准确的描述bug

**如何复现**
https://github.com/chenglu4343/wujie/tree/bug-vite

给出详细的复现步骤
pnpm i                  // 安装包依赖，务必使用pnpm
npm run start           // 启动所有应用

进入无界vue-demo展示，选择vite选项卡

如果是刷新时直接进入vite选项卡
![image](https://github.com/Tencent/wujie/assets/48679486/64dd49b9-cafc-4810-9057-1f29705b61b0)

如果是单例模式下再次进入vite选项卡
![image](https://github.com/Tencent/wujie/assets/48679486/81f08559-f360-4b22-8aa5-0474731df149)

**错误截图**
如果有可以将截图带上

**最小复现仓库或者地址**
https://github.com/chenglu4343/wujie/tree/bug-vite

**Comment by baiwusanyu-c** [comment]
同样的问题

**Comment by Ttou** [comment]
目前只支持到 vite 2.9，[issue](https://github.com/Tencent/wujie/issues/434)
