### ISSUE TITLE
子应用使用了ant design,在http请求后执行了message.success(),并执行了弹窗,在同一个子应用下切换页面或者切换不同的子应用下,再次http请求后message.success()弹窗没有弹出,但是console.log打印了message

### ISSUE THREAD

**Issue by JCqiu** [Tencent/wujie#610]
**描述bug**
子应用使用了ant design,在http请求后执行了message.success(),并执行了弹窗,在同一个子应用下切换页面或者切换不同的子应用下,再次http请求后message.success()弹窗没有弹出,但是console.log打印了message

**如何复现**
给出详细的复现步骤
1、第一步 在一个子应用页面下,在http请求后执行了message.success()
![1E62E73F-5ED7-4eac-8F93-647371B04539](https://github.com/Tencent/wujie/assets/16211027/dc5c367b-b164-4aba-9dd6-882301df9e04)

2、 第二步 在同一个子应用下切换页面或者切换不同的子应用下页面,再次http请求后message.success()弹窗无效,但是console.log打印了message的对象信息
![959eeb6922e86b90fe08a2d8b9f2fbab](https://github.com/Tencent/wujie/assets/16211027/bc29ff91-2d89-4ac5-93bc-d3438fcf74c9)

**错误截图**
如果有可以将截图带上

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by yiludege** [comment]
<img width="369" alt="image" src="https://github.com/Tencent/wujie/assets/19788268/c1965732-30a0-482f-a379-31adaf85e709">
在将子应用切换走的时候，将$message销毁掉

**Comment by JCqiu** [comment]
@yiludege 试了一下貌似还是不行

**Comment by JCqiu** [comment]
@yiludege 
![image](https://github.com/Tencent/wujie/assets/16211027/512c9cf0-65e0-464b-b0ee-ac2f59e4c354)

**Comment by JCqiu** [comment]
@yiludege 
![image](https://github.com/Tencent/wujie/assets/16211027/3e80076d-62da-4dfb-b941-2ddff2622ea0)
打印处理是空的

**Comment by JCqiu** [comment]
![2de0456389cd338c9e74960c669c82cf](https://github.com/Tencent/wujie/assets/16211027/22663486-0b34-4173-966a-81e4ed708f96)
这样就可以了
