### ISSUE TITLE
增加bus通信子应用的颗粒度

### ISSUE THREAD

**Issue by pengshengjie** [Tencent/wujie#622]
有如下场景，在每一个子应用中有同样的监听事件，但是我只想某一个子应用接受。
类似于postMessage
```js
// appName默认为*
bus.$emit(event, args, appName)
```

**Comment by yiludege** [comment]
这个能力其实是可以加的，但是为什么没有做呢，第一这个bus是公共线，单独往一个子应用emit事件感觉和这个理念有所背离，第二只需要eventname加一个子应用前缀就可以了

**Comment by namesfang** [comment]
> 这个能力其实是可以加的，但是为什么没有做呢，第一这个bus是公共线，单独往一个子应用emit事件感觉和这个理念有所背离，第二只需要eventname加一个子应用前缀就可以了

自己实现了
