### ISSUE TITLE
子应用在运行后location发生变化 会由shadow root自动降级为iframe，但是sandbox的degrade属性还是false

### ISSUE THREAD

**Issue by vinceao** [Tencent/wujie#623]
**描述bug**
清晰准确的描述bug
<img width="1173" alt="image" src="https://github.com/Tencent/wujie/assets/25076265/97fb8c0a-f8b6-422a-a638-6dcf30e80905">

<img width="1148" alt="image" src="https://github.com/Tencent/wujie/assets/25076265/e8258d22-afc7-4a85-af34-072290df2fd2">

<img width="703" alt="image" src="https://github.com/Tencent/wujie/assets/25076265/a3a00807-6768-48b7-b0a1-a12f7dd52d2e">

**如何复现**
给出详细的复现步骤
1、子应用添加setTimeout(() => {
    console.log("vue3 already change href");
    window.location.href = "https://www.google.com/";
  }, 5000);
2、这个时候如果降级的iframe的url不允许被嵌入iframe 发生error了，框架也没有error事件
**错误截图**
如果有可以将截图带上

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by yiludege** [comment]
在子应用中进行 window.locaiton.href ，子应用不是被降级了

而是用一个新的 iframe 承载了你这个新的链接，原来的无界实例并没有销毁。
