### ISSUE TITLE
【疑问】请问为什么子应用的location要删掉reload呢

### ISSUE THREAD

**Issue by TheYuuu** [Tencent/wujie#633]
<img width="693" alt="image" src="https://github.com/Tencent/wujie/assets/31104528/b6bec25b-548e-40de-9115-3821efaf915e">

子应用的reload行为直接由父应用的location.reload 执行有问题吗

**Comment by baiwusanyu-c** [comment]
我也遇到这个问题了…luoyu，最后咋解决的？

**Comment by TheYuuu** [comment]
> 我也遇到这个问题了…luoy瑜，最后咋解决的？

我这边是自己fork qiankun在团队技术栈下维护的，遇到一些问题借鉴(缝)wujie的实现，内部包直接改了就行，看源码的时候发现这个问题，官方微信二维码也过期了，提个issue几天没人回

**Comment by yiludege** [comment]
这个问题很简单，子应用在 iframe 沙箱内运行，iframe 沙箱做了很多代理来保证子应用正常工作，如果 window.location.reload的话，iframe沙箱都会被销毁，变成一个普通的iframe了，要解决这个问题也很简单，调用基座的window.parent.location.reload 就好了

**Comment by baiwusanyu-c** [comment]
> 调用基座的window.parent.location.reload
这样会导致基座 reload 会导致基座也刷新吗？如果这样的话有没有一个方法可以重新reload一个子应用呢？@yiludege

**Comment by yiludege** [comment]
你的子应用是运行什么模式呢

> > 调用基座的window.parent.location.reload
> 
> 这样会导致基座 也reload刷新吗？如果这样的话有没有一个方法可以重新reload一个子应用呢？@yiludege

**Comment by baiwusanyu-c** [comment]
单例模式的，现在有个场景是基座在不切走不刷新的情况下想要reload子应用

**Comment by yiludege** [comment]
这个地方可以先destoryApp，然后再startApp，我考虑一下是否把这个能力做到 reload 这个场景去

**Comment by baiwusanyu-c** [comment]
那樣的話就太棒了！感谢 🙏

**Comment by TheYuuu** [comment]
> 这个问题很简单，子应用在 iframe 沙箱内运行，iframe 沙箱做了很多代理来保证子应用正常工作，如果 window.location.reload的话，iframe沙箱都会被销毁，变成一个普通的iframe了，要解决这个问题也很简单，调用基座的window.parent.location.reload 就好了

感谢回复，能确认在iframe沙箱里的reload改成执行基座的reload没有问题就OK了
