### ISSUE TITLE
子应用vite, el-button icon 不显示

### ISSUE THREAD

**Issue by faner11** [Tencent/wujie#636]
**描述bug**
子应用vite, el-button icon 不显示

**如何复现**
`  <el-button icon="el-icon-search">搜索</el-button>`
![image](https://github.com/Tencent/wujie/assets/26560612/aa09c41d-9c3b-4183-bc43-d086a59f074c)

**错误截图**
如果有可以将截图带上

**最小复现仓库或者地址**
官方demo 添加`<el-button icon="el-icon-search">搜索</el-button> `即可

**Comment by jokey-boring** [comment]
我也遇到了,你有解决这个问题吗？

**Comment by faner11** [comment]
@jokey-boring vite 和 wujie 都升级到最新
