### ISSUE TITLE
Uncaught DOMException: Blocked a frame with origin "****" from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by JanusSpark** [Tencent/wujie#646]
如该常见问题所说
https://wujie-micro.github.io/doc/question/#_10%E3%80%81domexception-blocked-a-frame-with-origin-from-accessing-a-cross-origin-frame-%E6%8A%A5%E9%94%99
由于需要使用该302页面登录，所以不能换其他地址

目前产生302的原因，是因为主应用与子应用是不同子域名下的系统，登录态没有办法共享
子应用想要再登录的时候只能使用公司内的sso登录，会导致产生302；
目前公司内的sso登录不支持后台系统之间打通，一定要跳转去到SSO系统的页面调用他们的接口，他们再跳转到我们的后端的一个POST登录接口，该POST接口会种cookie并将页面302回到首页

本来尝试在子应用SSO登录之前抛出一个事件，主应用监听到之后通过v-if的方式将之前的wujievue组件销毁，换成新的，但是还是不行
`<WujieVue v-if="xxx" width="100%" height="100%" name="vue2" :url="'loginUrl'" :sync="false" :alive="true"></WujieVue>
<WujieVue v-else width="100%" height="100%" name="vue2" :url="'homeUrl'" :sync="false" :alive="true"></WujieVue>`

请问有什么其他解决方案吗？

**错误截图**
![image](https://github.com/Tencent/wujie/assets/12661048/37c4db21-dd54-4a07-83a7-200df9f32f6d)

**Comment by robertyclin** [comment]
我也遇到了，我重新刷新页面就报这个错了

**Comment by JanusSpark** [comment]
换了一种思路，先用一个隐藏的iframe同步登录态，然后再创建wujie即可
@robertyclin 可以试试

**Comment by robertyclin** [comment]
我的主子应用是同域名的，子应用在其中一个子目录上，第一次打开没问题，子应用正常加载，直接点击刷新按钮之后，就报这个错了，子应用一直在loading

**Comment by JanusSpark** [comment]
> 我的主子应用是同域名的，子应用在其中一个子目录上，第一次打开没问题，子应用正常加载，直接点击刷新按钮之后，就报这个错了，子应用一直在loading

[看下常见问题？](https://wujie-micro.github.io/doc/question/#_10%E3%80%81domexception-blocked-a-frame-with-origin-from-accessing-a-cross-origin-frame-%E6%8A%A5%E9%94%99)
如果没在常见问题里的话我也不晓得了
