### ISSUE TITLE
iOS15 safari下子应用index.html内联script导致加载失败

### ISSUE THREAD

**Issue by IceEnd** [Tencent/wujie#648]
**描述bug**

在iOS 15.2 版本左右，如果子应用中使用了内联的 script 标签，wujie处理的时候会报错：TypeError: Attempting to change the getter of an unconfigurable property.

**如何复现**

1. 子应用中使用了内联的script标签，比如
```html
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'xxxxx');
  </script>
```

2. 在挂载子应用时，wujie会处理这一段代码，具体定位到 https://github.dev/Tencent/wujie/blob/17179fbca76b23ee9b05eeec88818b65cc1e7daa/packages/wujie-core/src/iframe.ts#L728-L729

```ts
// 解决 webpack publicPath 为 auto 无法加载资源的问题
Object.defineProperty(scriptElement, "src", { get: () => src || "" });
```

而在这个版本的safari下 src 是不可配置的：
```
{get: function, set: function, enumerable: false, configurable: false}
```

导致报错：TypeError: Attempting to change the getter of an unconfigurable property.

这里有办法进行解决吗？

**Comment by yiludege** [comment]
可以提一个pr 过来，判断一下scriptElement的configurable，再进行这个逻辑处理

**Comment by IceEnd** [comment]
> 可以提一个pr 过来，判断一下scriptElement的configurable，再进行这个逻辑处理

麻烦帮忙CR下

**Comment by IceEnd** [comment]
@yiludege 大佬，帮忙cr一下

**Comment by RaHsu** [comment]
同遇到这个问题，求快速pr解决一下呢 @yiludege
