### ISSUE TITLE
ElementPlus的日期组件，日期选择器超出子应用范围导致显示不全

### ISSUE THREAD

**Issue by EF1874** [Tencent/wujie#658]
**描述bug**
在子应用边缘放置的日期组件，点击展示日期范围选择器（单个日期未测试）的时候，日期选择器的popper会超出子应用范围

**错误截图**
![image](https://github.com/Tencent/wujie/assets/57347272/e51f2767-9316-4043-93a6-959c983105f8)

**Comment by lovexp1** [comment]
可以设置popperjs的溢出边界
<img width="632" alt="image" src="https://github.com/Tencent/wujie/assets/44965220/0c535096-c79b-4e76-8d70-447a255e5e44">
<img width="646" alt="image" src="https://github.com/Tencent/wujie/assets/44965220/b9205adb-bf89-4139-8a6a-f5416ca079b5">

**Comment by EF1874** [comment]
> 可以设置popperjs的溢出边界 <img alt="图像" width="632" src="https://user-images.githubusercontent.com/44965220/259032548-0c535096-c79b-4e76-8d70-447a255e5e44.png"> <img alt="图像" width="646" src="https://user-images.githubusercontent.com/44965220/259032615-b9205adb-bf89-4139-8a6a-f5416ca079b5.png">

感谢提供的方法
不过如果子应用是作为主应用的子路由加载的时候，popper的边界如果只能出现在子路由里面，样式会有点怪，特别是子应用高度不够的话，还是会溢出，或者子应用有全屏弹窗，弹窗里面也有poppper，而子应用的html非全屏
还有除了popper,如果涉及到可拖拽的el-dialog，弹窗会漂移无法修改
我现在为了解决这些问题用不优雅的方案，直接将html和body定位提高层级展示，html设置全屏，body获取子路由内容的大小位置来定位
不知道有没有更好的方案，还是无界将子应用的html和body处理的不够好？

**Comment by quqingfei** [comment]
我这个帖子内回复了使用最小成本实现elemet-ui在popper.js内通过代替源码方式实现弹框偏移解决方案，你可以看看。
https://github.com/Tencent/wujie/issues/682#issuecomment-1696111047
可以看看我这个方案。不过element-plus我自己还没实验。你先看看加了管不管用。

**Comment by wu529778790** [comment]
> 可以设置popperjs的溢出边界 <img alt="image" width="632" src="https://user-images.githubusercontent.com/44965220/259032548-0c535096-c79b-4e76-8d70-447a255e5e44.png"> <img alt="image" width="646" src="https://user-images.githubusercontent.com/44965220/259032615-b9205adb-bf89-4139-8a6a-f5416ca079b5.png">

这个需要子应用自己处理，最好是都放到主应用上处理，子应用不管这些
