### ISSUE TITLE
子应用的navigator.mediaDevices为undefined

### ISSUE THREAD

**Issue by qljjun666** [Tencent/wujie#677]
子应用的navigator.mediaDevices为undefined

navigator.mediaDevices // undefined
window.parent.navigator.mediaDevices // undefined
window.__WUJIE_RAW_WINDOW__.navigator.mediaDevices // undefined

**Comment by yiludege** [comment]
window.parent.navigator.mediaDevices // undefined 为什么也是undefined

**Comment by qljjun666** [comment]
在主应用控制台打印window.navigator，确实没有mediaDevices属性

**Comment by yiludege** [comment]
微前端并没有修改主应用的属性，感觉和wujie没有关系？

**Comment by qljjun666** [comment]
官方demo中也是一样的情况 0.0
