### ISSUE TITLE
DEMO本地运行报错

### ISSUE THREAD

**Issue by 605666069** [Tencent/wujie#68]
![image](https://user-images.githubusercontent.com/19677659/184795183-8eba4609-f474-4921-8e08-6a8809faf117.png)

**Comment by yiludege** [comment]
我本地重新 clone 运行没有问题，注意运行 demo 的脚本

```bash
npm i                   // 安装包依赖
npx husky install       // Enable Git hooks
npm i -g lerna          // 安装 lerna
lerna bootstrap         // 安装所有子应用包依赖
npm run start           // 启动子应用
```
node版本 14~16都没问题

**Comment by 605666069** [comment]
是需要在主应用下执行吧 我是把main-vue 单独拉出来执行了

**Comment by yiludege** [comment]
这些命令是直接在 wujie  目录下运行，不用单独到 example 内去运行

**Comment by 605666069** [comment]
![image](https://user-images.githubusercontent.com/19677659/184797966-6a463ebe-dc89-4206-9ee3-0f6a3fe02c39.png)
我的lerna 版本是 5.3.0 请问您的版本是多少

**Comment by yiludege** [comment]
和 lerna 的版本无关，安装 vue2 的依赖报错了，看看是什么错误，node的版本是什么呢？

**Comment by 605666069** [comment]
node 版本v14.17.0

**Comment by Xchen1995** [comment]
node版本升级一下 需要16以上.. 14装一些angular2报错了
