### ISSUE TITLE
element-plus中table中使用tooltip，显示位置有问题

### ISSUE THREAD

**Issue by NewNameArk** [Tencent/wujie#680]
最新版本的"element-plus": "^2.3.7",已经是absolute了，但是依旧有问题

_Originally posted by @wu529778790 in https://github.com/Tencent/wujie/issues/214#issuecomment-1630207905_
            
```[tasklist]
### Tasks
```

**Comment by NewNameArk** [comment]
![tooltip](https://github.com/Tencent/wujie/assets/32755115/fc90a84c-146f-4cbc-b3dd-7f87d2586457)

**Comment by TheYuuu** [comment]
https://github.com/Tencent/wujie/issues/682 看下我这边的方案能否使用呢

**Comment by quqingfei** [comment]
我这个帖子内回复了使用最小成本实现elemet-ui在popper.js内通过代替源码方式实现弹框偏移解决方案，你可以看看。
https://github.com/Tencent/wujie/issues/682#issuecomment-1696111047
可能对你这个问题有所帮助，因为底层都用的是popper.js，你可以试试我这个方案。

**Comment by NewNameArk** [comment]
> #682 看下我这边的方案能否使用呢

收到，谢谢 ~ 看了一下，挺好的。我是修改table组件，使用自定义的tooltip实现的

**Comment by NewNameArk** [comment]
> 我这个帖子内回复了使用最小成本实现elemet-ui在popper.js内通过代替源码方式实现弹框偏移解决方案，你可以看看。 [#682 (comment)](https://github.com/Tencent/wujie/issues/682#issuecomment-1696111047) 可能对你这个问题有所帮助，因为底层都用的是popper.js，你可以试试我这个方案。

收到，谢谢 ~ 看了一下，挺好的。我是修改table组件，使用自定义的tooltip实现的
