### ISSUE TITLE
DOMException: Blocked a frame with origin  from accessing a cross-origin frame 报错

### ISSUE THREAD

**Issue by fanqi7** [Tencent/wujie#71]
DOMException: Blocked a frame with origin ***** from accessing a cross-origin frame
at getTargetValue (https://dev.g.alicdn.com/*********/***.js)

**Comment by yiludege** [comment]
这个问题已经好几位同学反馈了，我本地实在是难以复现

假如主应用为 host ，子应用代码会在 iframe 内部运行，而 iframe 的 src 就是设置为主应用的 host，按理来说不应该存在任何跨域的问题

首先排除一下主应用的代码污染问题 #54 ，在主应用的 html 的 head 第一个元素加一段这样的代码 <script>if(window.parent !== window) {window.stop()}</script> 看看还有没有这个问题

在看看看是 getTargetValue 函数报的错误，这个函数的第二个参数是个啥东西呢

方便的话有个最小的 demo 就好了，我可以一点点排查

**Comment by fanqi7** [comment]
加了<script>if(window.parent !== window) {window.stop()}</script>这个脚本，还专门给attrs的src设了一个空页面，还是报这个跨域错误

**Comment by yiludege** [comment]
这就排查了主应用污染的问题，现在就是一个纯前端跨域报错的排查，我没有现场也没有复现的demo最小demo，难排查

**Comment by fanqi7** [comment]
环境依赖PC应用的容器，很难搞出一个在浏览器上的demo

**Comment by yiludege** [comment]
这个问题已经有好几个反馈了，有线上地址也有本地localhost，有点不知道怎么查了，子应用的iframe和主应用都是同源的

**Comment by fanqi7** [comment]
还有cFetch报错，fetch子应用静态资源时报错
![fetch报错](https://user-images.githubusercontent.com/46001043/185090332-c76a8d08-1196-4f7d-90e4-f2e2698f5cd4.jpg)

**Comment by fanqi7** [comment]
使用qiankun可正常加载子应用的静态资源

**Comment by yiludege** [comment]
扎心了，给点信息

**Comment by yiludege** [comment]
在我文章的评论区有位同学似乎找到了一些线索：
<img width="663" alt="image" src="https://user-images.githubusercontent.com/19788268/185170466-84a90453-7202-4f72-a271-b2d5c6845837.png">
![image](https://user-images.githubusercontent.com/19788268/185170533-b97194d3-7821-4e8d-8341-9cadc817d7d0.png)

**Comment by roy-kang** [comment]
有可能是本地环境设置了 attrs 的 src

**Comment by yiludege** [comment]
这个问题已经在[常见问题](https://wujie-micro.github.io/doc/question/#_10%E3%80%81domexception-blocked-a-frame-with-origin-from-accessing-a-cross-origin-frame-%E6%8A%A5%E9%94%99)中列出来了可能性，需要用户去排查一下

**Comment by gadzan** [comment]
> 这个问题已经在[常见问题](https://wujie-micro.github.io/doc/question/#_10%E3%80%81domexception-blocked-a-frame-with-origin-from-accessing-a-cross-origin-frame-%E6%8A%A5%E9%94%99)中列出来了可能性，需要用户去排查一下

@yiludege 也有可能是父应用的 document.domain 被改变了导致的，建议加上这个排查项；

**Comment by yiludege** [comment]
好的

**Comment by gadzan** [comment]
> @gadzan 好的，这个地方父应用的 document.domain 被改变指的改到了其他域名还是只是三级域名改到二级域名也会出现这个问题呢，正常来说主应用的 domain 也不应该改成跨域的

@yiludege 三级域名改到二级域名，准确来说是将 domain 改到父域，因为有时候需要操作父域的 Cookies， 所以会更改主应用 domain

**Comment by swmjj** [comment]
官方例子中vue版主应用，主应用(VUE) 子路由(VUE3)的路由模式同时修改为hash模式，会出现这种问题

具体修改：
examples/main-vue/src/router/index.js

mode: "history"   =》 mode: "hash",

examples/vue3/src/router/index.js

history: createWebHistory(basename)   =》 history: createWebHashHistory(basename)


DOMException: Blocked a frame with origin "http://localhost:8001" from accessing a cross-origin frame.
    at Wujie.mount (webpack-internal:///../../packages/wujie-core/esm/sandbox.js:529:96)
    at eval (webpack-internal:///../../packages/wujie-core/esm/sandbox.js:451:35)

==============

但是vue主应用  vue2子应用同为hash模式，并没有异常

**Comment by X-W-W** [comment]
> > @gadzan 好的，这个地方父应用的 document.domain 被改变指的改到了其他域名还是只是三级域名改到二级域名也会出现这个问题呢，正常来说主应用的 domain 也不应该改成跨域的
> 
> @yiludege 三级域名改到二级域名，准确来说是将 domain 改到父域，因为有时候需要操作父域的 Cookies， 所以会更改主应用 domain

主应用 xxx.example.com
子应用 yyy.example.com
将主应用与子应用的document.domain都设置为example.com会出现当前的问题

**Comment by webLoginjun** [comment]
我这里报错的情况是这样
![image](https://github.com/Tencent/wujie/assets/22684780/8b0ece65-1d46-4936-a97b-648f6a969625)
请问一下这个如何解决呢

**Comment by LJiangA** [comment]
> 这个问题已经好几位同学反馈了，我本地实在是难以复现
> 
> 假如主应用为 host ，子应用代码会在 iframe 内部运行，而 iframe 的 src 就是设置为主应用的 host，按理来说不应该存在这个跨域的问题
> 
> 首先排除一下主应用的代码污染问题 #54 ，在主应用的 html 的 head 第一个元素加一段这样的代码 <script>if(window.parent !== window) {window.stop()}</script> 看看还有没有这个问题
> 
> 在看看看是 getTargetValue 函数报的错误，这个函数的第二个参数是个啥东西呢
> 
> 方便的话有个最小的 demo 就好了，我可以一点点排查

![chrome_Ip5Wezdmmg](https://github.com/Tencent/wujie/assets/64141612/2a9a0e81-5846-4a7e-8765-5002415d96c5)
我这里的报错是这样的，请问一下如何解决呢？

**Comment by Yang1998-jiale** [comment]
> > 这个问题已经好几位同学反馈了，我本地实在是难以复现
> > 假如主应用为 host ，子应用代码会在 iframe 内部运行，而 iframe 的 src 就是设置为主应用的 host，按理来说不应该存在这个跨域的问题
> > 首先排除一下主应用的代码污染问题 #54 ，在主应用的 html 的 head 第一个元素加一段这样的代码 <script>if(window.parent !== window) {window.stop()}</script> 看看还有没有这个问题
> > 在看看看是 getTargetValue 函数报的错误，这个函数的第二个参数是个啥东西呢
> > 方便的话有个最小的 demo 就好了，我可以一点点排查
> 
> ![chrome_Ip5Wezdmmg](https://private-user-images.githubusercontent.com/64141612/335095901-2a9a0e81-5846-4a7e-8765-5002415d96c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NTY0MjUsIm5iZiI6MTcxODk1NjEyNSwicGF0aCI6Ii82NDE0MTYxMi8zMzUwOTU5MDEtMmE5YTBlODEtNTg0Ni00YTdlLTg3NjUtNTAwMjQxNWQ5NmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDA3NDg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZGNhYzU0N2JiMzExMGFiNzcyOTRhNGIzMTliNGE5NWI2NDIwYWM3MWQ5NjU2Y2Y4NjRiMTc2NGZjMDIyM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9gfWkH6RRTKWUu1zrSq0qCJusw0XVjYHCb4tNveSTdI) 我这里的报错是这样的，请问一下如何解决呢？
> 
> 1、在主应用的 html 的 head 第一个元素加一段这样的代码 <script>if(window.parent !== window) {window.stop()}</script>；加这段代码也还存在这个问题； 2、试了[常见问题10](https://wujie-micro.github.io/doc/question/#_10%E3%80%81domexception-blocked-a-frame-with-origin-from-accessing-a-cross-origin-frame-%E6%8A%A5%E9%94%99)中的解决方案1，也还存在这个问题。

我也是这个问题,我主应用里嵌入了两个不同的子应用,A子应用出这个问题,B子应用正常
