### ISSUE TITLE
主应用如何跳转到子应用指定页？

### ISSUE THREAD

**Issue by 18610509683** [Tencent/wujie#72]

**Comment by yiludege** [comment]
查看[文档](https://wujie-micro.github.io/doc/guide/jump.html#%E4%B8%BB%E5%BA%94%E7%94%A8%E4%B8%BA-history-%E6%A8%A1%E5%BC%8F)

**Comment by 18610509683** [comment]
> 查看[文档](https://wujie-micro.github.io/doc/guide/jump.html#%E4%B8%BB%E5%BA%94%E7%94%A8%E4%B8%BA-history-%E6%A8%A1%E5%BC%8F)

不是要从子应用到子应用，具体的：从主应用导航栏到子应用指定页，点击事件在主应用里触发

**Comment by yiludege** [comment]
是demo的效果吗？，每个菜单栏对应子应用的一个指定页面
![image](https://user-images.githubusercontent.com/19788268/185055189-f673f981-54ff-4c8f-abac-baf1283b7047.png)

**Comment by 18610509683** [comment]
> 

是要这效果，电脑太差，demo跑不起来

**Comment by yiludege** [comment]
可以对着 [demo](https://wujie-micro.github.io/demo-main-vue/home)，和 源码 里面 main-vue、main-react项目看看怎么实现，类似 issue #46
