### ISSUE TITLE
下拉框等卡片弹出错位

### ISSUE THREAD

**Issue by 18610509683** [Tencent/wujie#73]
子应用独立运行效果：
![image](https://user-images.githubusercontent.com/62460552/185058808-2f925f66-1955-4cb2-beb6-24ca1ebb85e9.png)
微前端环境，作为子应用：
![image](https://user-images.githubusercontent.com/62460552/185058917-831b1fb0-0676-4701-811c-730c17e54c47.png)

**Comment by yiludege** [comment]
用的无界版本是最新的吗？

**Comment by 18610509683** [comment]
> 用的无界版本是最新的吗？

是的，
![image](https://user-images.githubusercontent.com/62460552/185059675-1bc41f50-d01e-47b9-8fc2-445e8cf381f0.png)
子应用element版本2.15.5，vue：2.6.11

**Comment by imrickywong** [comment]
这还是 font 的问题吧: [子应用的字体没有生效](https://wujie-micro.github.io/doc/question/#_3%E3%80%81%E5%AD%90%E5%BA%94%E7%94%A8%E7%9A%84%E5%AD%97%E4%BD%93%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88)

**Comment by 18610509683** [comment]
> 这还是 font 的问题吧: [子应用的字体没有生效](https://wujie-micro.github.io/doc/question/#_3%E3%80%81%E5%AD%90%E5%BA%94%E7%94%A8%E7%9A%84%E5%AD%97%E4%BD%93%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88)

是没有加载到组件的类样式，.el-***

**Comment by 18610509683** [comment]
> 这还是 font 的问题吧: [子应用的字体没有生效](https://wujie-micro.github.io/doc/question/#_3%E3%80%81%E5%AD%90%E5%BA%94%E7%94%A8%E7%9A%84%E5%AD%97%E4%BD%93%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88)

bug在线效果
主应用入口：  
http://ftp6269377.host101.udouyun.cn/#/    密码 K0yS2015
子应用单独访问：http://ftp6269377.host101.udouyun.cn/ele/

**Comment by yiludege** [comment]
看了一下，字体没有加载成功，应该是没有设置publicpath？

这个弹出卡片漂移的问题需要再看看

**Comment by 18610509683** [comment]
> 看了一下，字体没有加载成功，应该是没有设置publicpath？
> 
> 这个弹出卡片漂移的问题需要再看看

我都没注意到字体的问题，单独运行子应用也没有加载成功的

**Comment by ufec** [comment]
> > 这还是 font 的问题吧: [子应用的字体没有生效](https://wujie-micro.github.io/doc/question/#_3%E3%80%81%E5%AD%90%E5%BA%94%E7%94%A8%E7%9A%84%E5%AD%97%E4%BD%93%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88)
> 
> bug在线效果 主应用入口： http://ftp6269377.host101.udouyun.cn/#/ 密码 K0yS2015 子应用单独访问：http://ftp6269377.host101.udouyun.cn/ele/

你这个写的定位有问题吧，字体不说，别的样式没问题啊
![image](https://user-images.githubusercontent.com/34962267/185730944-35803c7e-c335-4d87-b886-6c6fd233d41a.png)

**Comment by yiludege** [comment]
@ufec 下拉弹出的卡片位置有漂移的，我的都飘到上面去了，这个大多数组件库采用 poppoer.js 来做定位，几个版本我都试过的没啥问题，这个问题还需要排查一下
<img width="691" alt="image" src="https://user-images.githubusercontent.com/19788268/185734994-82cfc798-ad0e-47f0-aa24-cb63d0d1d391.png">

**Comment by ufec** [comment]
我看他是自己写的定位啊，top-200多就是这效果，你把top改成0，没看到他附的第一张图那种样式全部乱的情况

**Comment by ufec** [comment]
> @ufec 下拉弹出的卡片位置有漂移的，我的都飘到上面去了，这个大多数组件库采用 poppoer.js 来做定位，几个版本我都试过的没啥问题，这个问题还需要排查一下 <img alt="image" width="691" src="https://user-images.githubusercontent.com/19788268/185734994-82cfc798-ad0e-47f0-aa24-cb63d0d1d391.png">


我看他是自己写的定位啊，top-200多就是这效果，你把top改成0，没看到他附的第一张图那种样式全部乱的情况

**Comment by yiludege** [comment]
@18610509683 这个是你自己写的定位嘛？我以为是 poppoer.js 在无界里面算错了

**Comment by ufec** [comment]
@yiludege 
它默认单独访问时候的效果
![image](https://user-images.githubusercontent.com/34962267/185735392-c4e71782-abcc-48b3-8e6f-415c752631c7.png)
使用无界进入
![image](https://user-images.githubusercontent.com/34962267/185735439-46cf07e4-9f37-47f4-b2e6-f50260142995.png)
这明显不一致

**Comment by 18610509683** [comment]
> 

![image](https://user-images.githubusercontent.com/62460552/185735573-c780e814-079f-43f7-828c-135ca9c87a26.png)
没有自己写样式，不然我把源码推到github，把地址发过来

**Comment by yiludege** [comment]
看样是还是 poppoer.js 出了问题

**Comment by 18610509683** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/62460552/185735573-c780e814-079f-43f7-828c-135ca9c87a26.png) 没有自己写样式，不然我把源码推到github，把地址发过来

蓝色图是公司项目，样式乱的多，el-xxx等类名有，浏览器加载不到，导致样式丢失

**Comment by handoing** [comment]
解决方案：
如果子应用可控，尝试下在el-date-picker组件添加:append-to-body="false"（element-ui并没有在文档里声明这个属性）。

问题分析：
poppoer.js在实例化时，提供了boundariesElement参数（"window"或"viewport"），element-ui在依赖poppoer时候使用的是默认参数"viewport"，如果使用"window"应该不会出现这个问题，不过element-ui并没有把这个参数抛给开发者。
element-ui在使用vue-popper可传递appendToBody的props，如果不将弹出框插入到body下，而是插入到data-picker节点内，我想不会出现错位的情况，不过会失去一些体验功能（例如在浏览器窗口改变时，popup窗口贴边跟随等）。

**Comment by wxStart** [comment]
这个问题主要是子应用和主应用的 body之间位置，有偏移量，你只要保证两个body位置是重叠的，通过css样式去控制子应用的布局，或者是在生命周期里面去操作子应用的body，设置偏移量.

我的应用是头部，侧边栏菜单，右侧主题主应用。

1. 我保证头部和侧边栏是相对定位的方式。 这样子应用和主应用就是一样大小了。
2. 我在生命值周期中去操作了子应用的dom， 设置了body的内边距，定位了样式（确保子应用的位置正确）
`js


  afterMount: (appWindow) => {
  const header = document.getElementById("header");
  const aside = document.getElementById("aside");
  // 获取元素宽高
  const { width } = aside.getBoundingClientRect();
  const { height } = header.getBoundingClientRect();


  appWindow.document.body.style.paddingLeft = width + 20 + "px"; //
  appWindow.document.body.style.paddingTop = height + 20 + "px"; //
  appWindow.document.body.style.paddingRight = 20 + "px"; //
  appWindow.document.body.style.paddingBottom = 20 + "px"; //
  },

`
