### ISSUE TITLE
vite4+vue3+dev开发环境+:root样式问题

### ISSUE THREAD

**Issue by 0006000** [Tencent/wujie#743]
**描述bug**
开发环境；主应用：vite4+vue3，子应用：vite4+vue3+vant4；生成的style标签，内部是vant定义的样式，:root没有替换为:host，导致变量不生效

**错误截图**

**Comment by webRambler** [comment]
解决了吗，我也遇到了，子应用使用了element-plus，也是:root的css变量没有生效

**Comment by 0006000** [comment]
> 解决了吗，我也遇到了，子应用使用了element-plus，也是:root的css变量没有生效

官网--常见问题--12：vite4 子应用样式切换丢失[issue 434](https://github.com/Tencent/wujie/issues/434#issuecomment-1614089196)
