### ISSUE TITLE
Selenium切换到Shadow DOM后仍然无法定位到元素

### ISSUE THREAD

**Issue by eleanorsubijanodvi62** [Tencent/wujie#748]
**描述bug**
Selenium切换到Shadow DOM后仍然无法定位到元素

**如何复现**
使用Java写自动化用例，使用`getShadowRoot()`方法切换到Shadow DOM中，但后续定位元素报错：`org.openqa.selenium.StaleElementReferenceException: stale element reference: stale element not found`

实现代码：
```Java
openPcBrowser(TestData.BrowserType, "https://wujie-micro.github.io/demo-main-vue/vue2-sub/dialog");
waitElementAppear(By.className("wujie_iframe"), 100);
WebElement shadowHost = DRIVER.findElement(By.className("wujie_iframe"));
SearchContext shadowRoot = shadowHost.getShadowRoot();
WebElement shadowContent = shadowRoot.findElement(By.cssSelector("html"));
System.out.println("Shadow DOM里的元素：" + shadowContent.getText());
```

**错误截图**
![image](https://github.com/Tencent/wujie/assets/116613321/3311a75a-de2a-4e62-8a62-660d1f77aab3)

**Comment by yiludege** [comment]
selenium 采用 chromedriver来获取元素，对于chromedriver中的findElement会走到一个判断函数 [isNodeReachable](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/chrome/test/chromedriver/js/call_function.js#25)，这个函数做了一些判断：顶部 document 和 全局document 来对比看是否是同一个，在webcomonent的shadowdom里面这个条件不成立所以出现了这个问题

解决办法，在获取shadowroot的元素的时候，先运行这段代码：

**Comment by DwlufveX** [comment]
u are my god！by the way, i want to know how you know about this?

**Comment by yiludege** [comment]
> u are my god！by the way, i want to know how you know about this?

my colleague also meet this question,he read the chromedriver source code and find this probleam,so i can find this solution,

**Comment by zhouhoukai** [comment]
I can now retrieve the elements of shadowroot, but there is an error when clicking  ERROR：element click intercepted: Element <div class="chat-list-item-wrapper" data-chatid="13852">...</div> is not clickable at point (201, 655). Other element would receive the click: <wujie-app data-wujie-id="chat" class="wujie_iframe" data-wujie-attach-css-flag="">...</wujie-app>
  (Session info: chrome=139.0.7258.157)   May I ask how to solve this? Thank you   @yiludege @DwlufveX
