### ISSUE TITLE
props 通信数据更新如何通知子应用

### ISSUE THREAD

**Issue by PeterPanY** [Tencent/wujie#75]

**Comment by yiludege** [comment]
这是个好问题，如果主应用和子应用都是vue，数据会是响应式，如果不是这种场景，可能不是很适合用props来通信，props是在框架层面是透传的，可以试试event bus通信

**Comment by PeterPanY** [comment]
我现在主子应用都是使用的vue  但是子应用并没有监听到数据变化

**Comment by yiludege** [comment]
传进来的是对象吗，可以打印一下看看有没有get、set

**Comment by PeterPanY** [comment]
子应用接受到的数据是这样的。![image](https://user-images.githubusercontent.com/28074957/185094177-211c1a4d-70e4-4366-a193-3e5dfb956a3f.png)
主应用isBrowser已经变为true了，但是子应用并没有更新

**Comment by yiludege** [comment]
这个isBrowser看着不像是响应式啊，是响应式就有...

**Comment by yiludege** [comment]
回家试了一下，就算是响应式也不行，后面的 watcher 没有挂载进来，看了一下vue源码的Object.defineProperty
确实不同 vue 应用有各自的 Dep 构造函数，就算子应用的watcher get 跑到了主应用 vue 的 Object.defineProperty的getter，但是Dep.target这个静态属性相互隔离导致依赖没办法收集进去

<img width="489" alt="xxx" src="https://user-images.githubusercontent.com/19788268/185159421-a7bc40b6-0923-45f4-84ba-7652bacead12.png">


这个行不通了，只能采用 event bus通信吧

**Comment by imrickywong** [comment]
如果子应用是 vue3 , 可以自己在用 reactive 包裹一层 props 实现响应式监听

**Comment by EasonMar** [comment]
> 

有 测试成功吗？ 我给 props 包裹了 reactive 也是不行哦。。。

**Comment by EasonMar** [comment]
> 如果子应用是 vue3 , 可以自己在用 reactive 包裹一层 props 实现响应式监听

可以嘛？我亲测不行哦。。。
