### ISSUE TITLE
动态子应用url 如何预加载

### ISSUE THREAD

**Issue by bingzhongqin** [Tencent/wujie#76]
请教一个问题，我子应用的url 类似这样  ${host}/#/external-analysis/${reportId}?token=${token}，reportId和token都是动态的。如果我想preloadApp 预加载 该应用，我的url该怎么写

**Comment by yiludege** [comment]
如果子应用是SPA应用的话，只要给一个有效的路由就可以了，没有必要精准到具体业务路由
