### ISSUE TITLE
主子应用监听的事件无法取消，会重复监听

### ISSUE THREAD

**Issue by felixzhou555** [Tencent/wujie#766]
**描述bug**
主子应用监听的事件，子应用发送事件； 子应用切回主应用后，会重复监听，且无法取消监听

**如何复现**
给出详细的复现步骤
子应用发送事件：
![image](https://github.com/Tencent/wujie/assets/95023395/f167917d-9c7c-44a4-a063-962faec8c09d)
主应用某一个页面监听事件：
![image](https://github.com/Tencent/wujie/assets/95023395/29d412a5-3959-4fe8-bbda-cfcf3f7850aa)

![image](https://github.com/Tencent/wujie/assets/95023395/04fe9eac-91f5-424d-a343-d40dbf0e1a0e)

**Comment by yiludege** [comment]
不是你这样用的，addeventlistener removeeventlistener 是怎么做的无界就是怎么处理的
