### ISSUE TITLE
子应用使用CKEditor5富文本编辑器，改变url的query参数重新加载后光标异常

### ISSUE THREAD

**Issue by rickx81** [Tencent/wujie#768]
**描述bug**
子应用使用了 CKEditor5 富文本编辑器，url 中的 query 参数更改后子应用会重新加载，此时编辑器内部的光标在 Chrome/Edge 下有问题，无法更改到点击位置，在 FireFox 下正常，在 Safari 下只有第一次点击会异常

**如何复现**
给出详细的复现步骤
1、第一次进入的时候光标是没问题的，可以任意点击或者选中都正常
2、点击左上角按钮更改 url 的 query，再次加载后就有问题了

定位到应该是 getSelection() 获取的内容有问题，CKEditor5 对应代码在 \ckeditor5-engine\src\view\observer\selectionobserver.ts 中有监听 selectionChange

**错误截图**
Chorme/Edge：
![image](https://github.com/Tencent/wujie/assets/51046506/2021675f-a02e-40d7-b63e-41632db99edd)

Firefox中获取的是正常：
![image](https://github.com/Tencent/wujie/assets/51046506/d2c51ee6-de5d-46f9-81e9-49e65a50a5a5)

https://github.com/Tencent/wujie/assets/51046506/bf224143-5f00-42d3-89de-ec985f7f3b09

**最小复现仓库或者地址**
https://github.com/rickx81/vite-vue3-wujie-ckeditor

重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by rickx81** [comment]
子应用中的 getSelection() 指向好像有问题，都指向了第一个 shadowRoot ?

![image](https://github.com/Tencent/wujie/assets/51046506/aeaad55c-d77b-44d0-9d46-5d677217966f)

![image](https://github.com/Tencent/wujie/assets/51046506/32b9464f-946d-4717-8ab6-82fb50b09a87)

**Comment by zonemeen** [comment]
@rickx81  你好，你是怎么解决这个问题的，我也遇到了

**Comment by rickx81** [comment]
> @rickx81 你好，你是怎么解决这个问题的，我也遇到了

其实是另外一个问题导致的 #770
我自己 fork 代码改了，然后自己发包使用了

**Comment by zonemeen** [comment]
行吧，估计只有这种方法解决了，你是咋改写缓存了，请问一下

**Comment by zonemeen** [comment]
可以，我试试，谢谢了

**Comment by rickx81** [comment]
> 可以，我试试，谢谢了

没问题的话可以提个 pr 给他们

**Comment by AttackXiaoJinJin** [comment]
兄弟赶紧提，不止是你这个编辑器，我用的slate也遇到这个问题了，感觉只要是子应用里用了编辑器都会出现这个bug

**Comment by rickx81** [comment]
> 兄弟赶紧提，不止是你这个编辑器，我用的slate也遇到这个问题了，感觉只要是子应用里用了编辑器都会出现这个bug

最近很忙，你也可以提一个pr看看
这个 getSelection 其实还有个问题，shadowRoot 上的 isCollapsed 始终都是 true 还是 false 来着，有些编辑器内部会自己根据选中的前后位置判断

**Comment by loser-or-no** [comment]
好像还是不行啊

**Comment by rickx81** [comment]
> 好像还是不行啊

可以自己改一下源码发包，或者用 pnpm patch 的方式改一下源码打补丁

**Comment by loser-or-no** [comment]
> > 好像还是不行啊
> 
> 可以自己改一下源码发包，或者用 pnpm patch 的方式改一下源码打补丁

改 wangeditor吗

**Comment by rickx81** [comment]
> > > 好像还是不行啊
> > 
> > 
> > 可以自己改一下源码发包，或者用 pnpm patch 的方式改一下源码打补丁
> 
> 改 wangeditor吗 @rickx81

wangeditor 的话你搜一下 issue 应该有解决方案吧，我这个问题是 CKEditor 的光标异常问题，主要是子应用里面的 getSelection 都指向了第一个子应用，改了 wujie 的代码
