### ISSUE TITLE
子应用的全局变量没有被处理，导致其他脚本中读取全局变量报变量未定义的错误

### ISSUE THREAD

**Issue by AlanLee97** [Tencent/wujie#769]
# 问题描述
子应用脚本：
```html
  <script>
    var hello = 'hello wujie'
  </script>
  <script>
    console.log(hello)
  </script>
```

主应用中报错，变量未定义
![image](https://github.com/Tencent/wujie/assets/42601044/2545fe73-5ff4-4f7b-b99e-0e4e23bd8c38)

主要是子应用中的单个脚本被wujie包裹到一个立即执行函数里去执行，导致原先定义的变量的作用域改变了
![image](https://github.com/Tencent/wujie/assets/42601044/8cd33695-a1cb-44e5-bfce-e091ef5313e4)

# 临时解决方案
1. 手动改写脚本，定义全局变量时把全局变量都带上window。（这个方式需要手动改造子应用，并且不能保证引入其他三方脚本会不会有这种情况出现）

那么，官方能不能针对这种问题处理一下呢？

# 复现相关问题仓库
https://github.com/AlanLee97/wujie-demo

**Comment by yiludege** [comment]
https://wujie-micro.github.io/doc/question/#_2%E3%80%81%E7%AC%AC%E4%B8%89%E6%96%B9%E5%8C%85%E5%B7%B2%E7%BB%8F%E5%BC%95%E5%85%A5-%E4%BD%BF%E7%94%A8%E6%97%B6%E6%8A%A5%E9%94%99

**Comment by AlanLee97** [comment]
> https://wujie-micro.github.io/doc/question/#_2%E3%80%81%E7%AC%AC%E4%B8%89%E6%96%B9%E5%8C%85%E5%B7%B2%E7%BB%8F%E5%BC%95%E5%85%A5-%E4%BD%BF%E7%94%A8%E6%97%B6%E6%8A%A5%E9%94%99

好的，谢谢。（抱歉啦，之前没有看到这块内容）
