### ISSUE TITLE
子应用嵌套iframe ，iframe内部的 window.parent 指向到了主应用，并非子应用。

### ISSUE THREAD

**Issue by loycoder** [Tencent/wujie#773]
**描述bug**
子应用嵌套iframe ，iframe内部的 window.parent 指向到了主应用，并非子应用。子应用无法监听到 iframe发出的message.

**如何复现**

 
```js
// 子应用：
window.addEventListener('message', receiveMessage);
  }, '*');

```

```js
// 子应用下的iframe :
 window.parent.postMessage({
    eventName,
    data
```

wujie版本： 1.0.22
react版本： 18.0.0

**错误截图**
无错误.

**最小复现仓库或者地址**
在官方的examples 就能复现

**Comment by loycoder** [comment]
已修复，着急使用的同学可以参考下代码： https://github.com/Tencent/wujie/pull/775

**Comment by yumanman88** [comment]
请问这个修复发版本了嘛

**Comment by yiludege** [comment]
可以看看示例：https://wujie-micro.github.io/demo-main-vue/postmessage?vue2=%2Fdemo-vue2%2F%23%2Fpostmessage

**Comment by wenkeShi** [comment]
> 可以看看示例：https://wujie-micro.github.io/demo-main-vue/postmessage?vue2=%2Fdemo-vue2%2F%23%2Fpostmessage

@yiludege 一定要在父应用转发子应用的iframe message给子应用吗？为啥子应用里的iframe的window.parent不是子应用而是父应用？感觉不合理。

**Comment by yongdong1997** [comment]
> > 可以看看示例：https://wujie-micro.github.io/demo-main-vue/postmessage?vue2=%2Fdemo-vue2%2F%23%2Fpostmessage
> 
> @yiludege 一定要在父应用转发子应用的iframe message给子应用吗？为啥子应用里的iframe的window.parent不是子应用而是父应用？感觉不合理。

确实，我在兼容老项目的时候有个子应用里面用到了弹窗通过iframe渲染一个公共选择器，原来选择器是通过window.parent调用父窗口的方法来返回结果的，现在postMessage只能在主应用接收，假如我渲染了很多个子应用我根本不知道转发给哪个子应用。也不清楚是哪个子应用打开的弹窗？
