### ISSUE TITLE
子应用图片路径解析错误

### ISSUE THREAD

**Issue by felixzhou555** [Tencent/wujie#779]
**描述bug**
主、子应用均为vite4+vue3，子应用图片超过4张，地址解析就会出错

**如何复现**
给出详细的复现步骤：

4张图片及以下时，解析正确：
![image](https://github.com/Tencent/wujie/assets/95023395/a80aa63e-b11b-46b9-83bb-98a55f297425)

当增加一张图片时，地址就全部变成了相对路径：
![image](https://github.com/Tencent/wujie/assets/95023395/203380de-cb60-43d4-872d-5a18d52c1e3f)

反复测试过背景和图片的混合组合，均存在这种问题，当子应用图片大于4张时，就会出现地址解析的问题

代码如下：
![image](https://github.com/Tencent/wujie/assets/95023395/498985a2-2cde-41dc-a859-20819f115b7c)

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by 2019process** [comment]
怎么解决的

**Comment by xieanwen** [comment]
怎么解决的

**Comment by 2019process** [comment]
> 怎么解决的

使用 import icon from '/xxx/xxx/icon.png'方法可以解决
