### ISSUE TITLE
TypeError: Cannot redefine property: xxx

### ISSUE THREAD

**Issue by yiludege** [Tencent/wujie#78]
**描述bug**
patchStylesheetElement中对每次插入进来的样式元素进行了Object.defineProperties，但是可能重复插入相同元素导致反复Object.defineProperties，页面就报错

**错误截图**
![image](https://user-images.githubusercontent.com/19788268/185350903-abba1c1d-7d44-45ef-9ea4-8e77e992196d.png)

**Comment by Xchen1995** [comment]
<img width="474" alt="image" src="https://user-images.githubusercontent.com/22890443/185583665-fdd5c9bb-1552-410b-82d1-d5e3c0aafc5e.png">

好像没报错诶
