### ISSUE TITLE
部署子应用时加载错误

### ISSUE THREAD

**Issue by felixzhou555** [Tencent/wujie#785]
**描述bug**
dev环境一切加载正常，如图：
![image](https://github.com/Tencent/wujie/assets/95023395/0ff03055-5ac8-44ab-a268-c98dc24f656a)

上产环境，在一个端口下，通过不同的路径去区分子应用加载：

nginx配置如下：
![image](https://github.com/Tencent/wujie/assets/95023395/cfae3b65-f253-4372-bc55-164c26e7afbb)

界面如下：
![image](https://github.com/Tencent/wujie/assets/95023395/e5a8b2ab-ea99-4c15-a8af-c5fcd46b0a0a)

 请问，部署时是否有额外的配置，感谢~

**Comment by thinkiveWJ** [comment]
老哥，你的问题解决了吗？我也遇到了这个问题
