### ISSUE TITLE
第三方包动态创建的jsonp请求被主应用的fetch劫持，导致CORS报错。

### ISSUE THREAD

**Issue by OldDream** [Tencent/wujie#79]
**描述bug**
在子应用中引入google Map，即可复现本bug

**错误截图**
![image](https://user-images.githubusercontent.com/18358438/185578620-df1b3705-ee3c-4a51-8fb3-2e38e276179c.png)

**Comment by yiludege** [comment]
是不是对跨域理解有问题呢

不管是子应用单独跑还是内嵌，访问https://maps.googleapis.com/maps/api/is?callbacke这个接口应该都是跨域的

此时不就是要劫持fetch然后采用mode: 'cors'去跨域请求这个api吗

**Comment by OldDream** [comment]
> 是不是对跨域理解有问题呢
> 
> 不管是子应用单独跑还是内嵌，访问[https://maps.googleapis.com/maps/api/is?callbacke这个接口应该都是跨域的](https://maps.googleapis.com/maps/api/is?callbacke%E8%BF%99%E4%B8%AA%E6%8E%A5%E5%8F%A3%E5%BA%94%E8%AF%A5%E9%83%BD%E6%98%AF%E8%B7%A8%E5%9F%9F%E7%9A%84)
> 
> 此时不就是要劫持fetch然后采用mode: 'cors'去跨域请求这个api吗

呃。。我描述得不完整。下图是这个 jsonp 请求的响应头，我们可以看到，它并不是一个允许跨域请求的响应头，没有`Access-Control-Allow-Origin`字段。毕竟 jsonp 这种形式无需考虑跨域问题。如果不被劫持，它显然能正常工作，劫持后使用fetch请求，就会被浏览器拦下。

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/18358438/185585277-49c24f54-0902-4db3-b034-ad2ae0a11181.png">

**Comment by yiludege** [comment]
get 你的意思了

## 我来复述一下问题：

1、正常情况，子应用的 template 都会通过正则匹配拿到所有的内联、外联的  js 文件、 css 文件，为了让 js 的代码运行在闭包内（原因 #63 ）

2、子应用需要通过 fetch 将外联的 js 文件请求下来然后通过内联 script 的方式在闭包内执行

3、外联 js 文件浏览器支持跨域且不会有跨域问题，但是通过 fetch 请求会导致跨域问题，这个就是当前 issue 的问题

## 解决办法：

1、框架提供 js-ignores 能力（todo-list），让所有外联 js 都通过外联的方式在 iframe 内加载

2、这个地方确实是框架没有提供这个能力，当前可以这样设置 plugins

```javascript
plugins: [
  {
    // 排除子应用的这个脚本不加载，防止报错
    { jsExcludes: ["https://maps.googleapis.com/maps/api/is?callback=_googleMapCallback" ] },
    // 在子应用所有的js之前插入一个外联脚本
    jsBeforeLoaders: [
      { src: "https://maps.googleapis.com/maps/api/is?callback=_googleMapCallback" },
    ],
  },
],
};
```
## 框架的优点

子应用代码由于运行在 iframe 这个天然的沙箱，就算外联 js 加载子应用代码也不怕污染到主应用了

**Comment by Mr-GaoYu** [comment]
主应用 加载的资源  会重复加载

**Comment by 5265liu** [comment]
> 主应用 加载的资源 会重复加载

是的我也遇到了
