### ISSUE TITLE
【请教】如何在主应用中引用子应用的某些内容呢？

### ISSUE THREAD

**Issue by lwm98** [Tencent/wujie#800]
一、举例：
现有子应用A、B、C，内分别有弹窗a，弹窗b，弹窗c。
请问在主应用中，如何调用弹窗a/弹窗b/弹窗c呢（可能没有切入子应用ABC的情况下）。

二、问题出现应用场景：
旧系统使用wujie拆分成各个业务系统了，需要在主应用做到集成各个业务系统的单据待办审批，但是拆分后wujie貌似没法引用到各个业务系统的表单单据详情了。

请大佬们看到可以抬手指点指点，万分感谢！

**Comment by lwm98** [comment]
@yiludege 大佬有空瞧瞧么

**Comment by yiludege** [comment]
在子应用不渲染的情况下只调用子应用的弹窗目前不支持这种操作，也没有想到有什么办法可以做到。目前主应用和子应用作用域都是通的，子应用通过window.parent 可以直接到父应用的作用域，父应用通过 iframe可以拿到子应用的window，所以如果有什么需要共享的可以直接通过作用域获取

**Comment by lwm98** [comment]
> 这个需求也蛮常见的,但是我看了文档没有找到子应用共享组件给主应用,qiankun的解决方案里面有,但是qiankun也没那么智能,组件的 CSS 有可能不能完全加载到主应用 共享组件的思路: 子应用提供共享组件列表给到主应用,主应用进行注册,这就能实现上面的需求

是这个意思了，但是就没有找到好的解决方法

**Comment by lwm98** [comment]
换了种方式，也算解决了。
使用dialog包裹wujie子应用，打开子应用对应的单据页面，配合bus通信，完成审批。
