### ISSUE TITLE
在开发环境主应用访问子应用正常，上测试环境后访问子应用无界里报错 Uncaught SyntaxError: Unexpected token '<'     at t.Node.appendChild

### ISSUE THREAD

**Issue by JayYang-666** [Tencent/wujie#811]
大佬们救救孩子吧。在开发环境主应用访问子应用正常，上测试环境后访问子应用无界里报错
Uncaught SyntaxError: Unexpected token '<' 
 at t.Node.appendChild
![微信截图_20240312114442](https://github.com/Tencent/wujie/assets/93505256/1e45e7ca-4637-4417-9ef3-a9262eec1d11)

**Comment by ouzexi** [comment]
> 大佬们救救孩子吧。在开发环境主应用访问子应用正常，上测试环境后访问子应用无界里报错 Uncaught SyntaxError: Unexpected token '<' at t.Node.appendChild ![微信截图_20240312114442](https://private-user-images.githubusercontent.com/93505256/311933510-1e45e7ca-4637-4417-9ef3-a9262eec1d11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MDY5NzEsIm5iZiI6MTcyOTkwNjY3MSwicGF0aCI6Ii85MzUwNTI1Ni8zMTE5MzM1MTAtMWU0NWU3Y2EtNDYzNy00NDE3LTllZjMtYTkyNjJlZWMxZDExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDAxMzc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZTU1YjJkMTEzZGFkNmUwYmZjZjk5OTIxNDZhYTIxYmRjOWVkYmRjMmYwYjA5YTY5ZTI4YTJjMjk2Njk3NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u-g3mClkP1nzkR1s2w8euRtfqnW65JLcXKRZltGmFZg)

请问大佬如何解决的？

**Comment by ImKZhu** [comment]
我猜是子应用构建时没有填写publicPath，所以其js资源文件的访问路径是相对路径，导致了主应用加载它们时搞错了地址

**Comment by ouzexi** [comment]
> 我猜是子应用构建时没有填写publicPath，所以其js资源文件的访问路径是相对路径，导致了主应用加载它们时搞错了地址

不是这个原因，资源加载路径不正确，应该会导致所有浏览器都无法渲染才对，但是现在是针对火狐浏览器无法渲染，具体可看仓库地址的运行截图。
