### ISSUE TITLE
当子应用和主应用不同源时，子应用中发起的axios请求的域名如何变成主应用的location.host？

### ISSUE THREAD

**Issue by Steven-Rogers27** [Tencent/wujie#814]
**描述问题**
本地启动wujie主应用（vite+vue3），和子应用（vite），主应用和子应用分别启动在localhost的不同端口上，子应用中使用axios发起restful接口调用时就会报请求跨域。而子应用若使用window.fetch，则调用成功。请问如何配置能让子应用的axios请求域名变成主应用的location.host，这样就不跨域了 

**错误截图**
![image](https://github.com/Tencent/wujie/assets/55077630/5200cc24-93c0-407c-aa26-e79b3b7f258a)

**Comment by WXperia** [comment]
判断应用在无界环境用绝对地址就行

**Comment by yiludege** [comment]
跨域就解决跨域的问题，如果是主应用代理，就采用楼上的方法

**Comment by 1659494258** [comment]
> 判断应用在无界环境用绝对地址就行

这个是什么意思能解释下嘛？
