### ISSUE TITLE
IOS中使用braft-editor编辑器报错：InvalidStateError: extend() requires a Range to be added to the Selection

### ISSUE THREAD

**Issue by mafx1024** [Tencent/wujie#818]
**描述bug**
初始化加载是正常的，当输入文字的时候报错：InvalidStateError: extend() requires a Range to be added to the Selection
只有在 IOS 的 safari 浏览器中有这个问题

**如何复现**
1. 加载编辑器
2. 输入文字
3. 报错

**错误截图**
![image](https://github.com/Tencent/wujie/assets/93925944/da92219f-47ae-46b1-9819-1883898d5995)

**最小复现仓库或者地址**
暂无

**Comment by mafx1024** [comment]
我尝试注释了
![image](https://github.com/Tencent/wujie/assets/93925944/e1108d06-bcc1-447f-98c3-29c62925fe66)
页面是没有报错了，但是对于编辑的输入相关的动作是有影响的。

**Comment by mafx1024** [comment]
问题原因：根本原因是 safari浏览器不支持 shadowDOM.getSelection，
解决方案：在 safari 环境中主动降级

**Comment by homestylew** [comment]
我也遇到这个问题了，大哥你解决了吗
