### ISSUE TITLE
子应用为vite+vue3，路由使用懒加载的模式，打包后，在主应用里面加载时懒加载的路由对应的js文件被重复加载，wujie管网上的vue主应用的示例就可以重现

### ISSUE THREAD

**Issue by Vein-Yan** [Tencent/wujie#821]
子应用为vite+vue3，路由使用懒加载的模式，打包后，在主应用里面加载时懒加载的路由对应的js文件被重复加载，wujie管网上的vue主应用的示例就可以重现：
1. 打开https://wujie-micro.github.io/demo-main-vue/vite?vite=%2Fdemo-vite
2. 打开f12
3. 切换至弹窗页面

结果：在控制台的网络标签会发现弹窗页面对应的js文件Dialog.xxx.js被加载了两次

**Comment by yiludege** [comment]
可以看看浏览器的协商缓存原理哈
