### ISSUE TITLE
动态script问题

### ISSUE THREAD

**Issue by GordonLee-112** [Tencent/wujie#826]
![image](https://github.com/Tencent/wujie/assets/48719784/eccb52b9-d1e4-4a4e-99aa-6a93b236686a)
这种方式会使得后续动态加载的脚本被挂载在主应用下
![image](https://github.com/Tencent/wujie/assets/48719784/3d56f37f-7a4e-45d3-a60c-6b368b169416)

**Comment by News777** [comment]
![image](https://github.com/Tencent/wujie/assets/57581602/03ef2770-1df7-41e4-bc90-db3378b47b76)
通过插件也许可以解决

**Comment by yiludege** [comment]
并不会出现这种情况，在子应用里面采用 document.body.append的时候，append函数被劫持，如果发现需要append的是iframe，那么会移入子应用的iframe的沙箱中运行
