### ISSUE TITLE
直接访问Angular子应用二级路由响应404

### ISSUE THREAD

**Issue by OSpoon** [Tencent/wujie#827]
**描述bug**

在官方示例的基础上对 angular 子应用进行多模块的路由改造，主应用和子应用的导航均正常工作，但直接访问 angular 子应用的二级路由会提示 404，无法访问，目的是同其他子项目一样可以访问（http://localhost:8000/angular12-sub/home）

**如何复现**
通过浏览器直接访问 http://localhost:8000/angular12-sub/home 会遭到拒绝（404）html请求出现错误

**错误截图**
![aa7d58b435184399b46f2758a31e2d9](https://github.com/Tencent/wujie/assets/10126623/7698342d-4bcb-49db-9b5c-156d38275bd6)

**最小复现仓库或者地址**

```
git clone https://github.com/OSpoon/wujie.git

git checkout upstream/feat/angular-router
```

**Comment by eminoda** [comment]
在开发环境通过 devServer 起的项目，主应用发起的 fetch 不含 accept（text/html）才导致 404. 

目前没看到哪里能设置 fetch 请求头，或者在子应用的脚手架服务中设置

**Comment by eminoda** [comment]
@OSpoon 找到方法了，官网有提供 html，它不是连接，可以是个 function 函数。在开发环境可以自定义 fetch 方法：

`
        startApp({
          name,
          url,
          el: document.querySelector('#micro-app-container'),
          sync: false,
          html: fetch(url, {
            headers: {
              Accept: 'text/html',
            },
          })
            .then((response) => {
              if (response.status >= 400) {
                throw new Error('加载异常' + response.status)
              }
              return response.text()
            })
            .catch((e) => {
              return Promise.reject(e)
            }),
        })
`

**Comment by OSpoon** [comment]
@eminoda 感谢你的帮助，我找回了 `feat/angular-router` 分支的代码并尝试了你提供的方案，这看起来确实可行，但我已经不再使用 `wujie` 作为我的第一选择了。

**Comment by OSpoon** [comment]
> > [@eminoda](https://github.com/eminoda) 感谢你的帮助，我找回了 `feat/angular-router` 分支的代码并尝试了你提供的方案，这看起来确实可行，但我已经不再使用 `wujie` 作为我的第一选择了。
> 
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/10126623?u=cb3d04441d51f20c731510d0f758ceca913f5eb8&amp;v=4&amp;size=80">@OSpoon](https://github.com/OSpoon) 请问老哥现在的第一选择是什么

时间太久，已经不负责前端的改造了，如果常见的几种微前端框架你都尝试过后，iframe 也可以作为最终的备选，也建议你的主应用可以支持多种的接入方式。
