### ISSUE TITLE
wujievue2 为什么不导出startApp

### ISSUE THREAD

**Issue by fx159** [Tencent/wujie#834]
**描述bug**
wujievue2不导出startApp

**如何复现**
给出详细的复现步骤
1、第一步 xxx
2、 第二步 xxx

**错误截图**
![wujie](https://github.com/Tencent/wujie/assets/52268929/8afe2f98-a9a8-42d9-a758-4fd75b8f95ea)

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by yiludege** [comment]
可以这样使用哈：

```javascript
import WujieVue from "wujie-vue2";
const { setupApp, preloadApp, bus } = WujieVue;
```
