### ISSUE TITLE
微信h5使用wujie后，在子应用展示二维码，ios长按二维码无响应，无法实现保存，分享，转发等操作，安卓正常

### ISSUE THREAD

**Issue by vscoderwhy** [Tencent/wujie#837]

**Comment by yiludege** [comment]
https://developers.weixin.qq.com/community/develop/doc/0008eebe57c988d7ff7e747bf56800

微信的问题哦

**Comment by vscoderwhy** [comment]
好的，感谢你的帮助，我已经解决了此问题
可以在子应用需要长按识别的图片添加touchstart.prevent将地址传到主应用，主应用再动态创建img，赋值src并脱离文档流进行全屏展示，此时能够触发长按识别二维码等图片，松手后，再通过touchcancel.prevent和touchend.prevent，触发删除此前在主应用创建的img标签即可
