### ISSUE TITLE
无界 保活模式 一段时间不操作页面  #子应用出现边框且页面卡死，而且WujieVue.bus.$emit也无法触达子应用。

### ISSUE THREAD

**Issue by loser-or-no** [Tencent/wujie#842]
无界 保活模式 一段时间不操作页面  #子应用出现边框且页面卡死，而且WujieVue.bus.$emit也无法触达子应用。切换到主应用的tab再切回子应用就会报错如下
![1713769350814](https://github.com/Tencent/wujie/assets/38649449/3057e846-96e6-4b9e-8522-85a20af7c851)

```[tasklist]
### Tasks
```

**Comment by TianJianJun0727** [comment]
同样的问题，卡死

**Comment by loser-or-no** [comment]
@

> 同样的问题，卡死

嗯， 我这边是一段时间不访问就会复现

**Comment by loser-or-no** [comment]
![775bfa040cab36c1edf1dbe0b96df3d](https://github.com/Tencent/wujie/assets/38649449/42186113-1e66-4811-b644-9bbbe7b77d3f)
上面是没问题的沙箱打印
![2111a487fe9ad2fbac9cfbcfd08dbad](https://github.com/Tencent/wujie/assets/38649449/ac9a42d3-c439-4555-8751-ddb0e7cedf87)
看着好像是$wujie丢失了。
![fc8c68e3aaaa66d55473d91a893a870](https://github.com/Tencent/wujie/assets/38649449/f15a67d8-3a79-4257-a47b-e1759b3963a6)

**Comment by loser-or-no** [comment]
@yiludege 大佬有空看看吧

**Comment by TianJianJun0727** [comment]
我发现我这边出问题时，iframe指向的url发生了变化

**Comment by loser-or-no** [comment]
> 我发现我这边出问题时，iframe指向的url发生了变化

留个微信，具体交流下

**Comment by yiludege** [comment]
个人猜测：
1、发生这种现象的时候子应用的沙箱iframe发生了跳转，导致正常的沙箱被销毁了，iframe沙箱变成了一个正常的iframe
2、子应用的dom依然存在主应用上，所以可以正常看到子应用，但是点击的时候，绑定的事件回调都在iframe沙箱里面，而iframe沙箱已经被销毁了，所以表现为子应用怎么点击都没有反应
3、验证我这个猜测可以通过当子应用卡死后，查看一下子应用的iframe沙箱，如果这个iframe沙箱既有正常的dom也有js，也就是沙箱被摧毁了

解决的办法：
如果上面的猜测是正确的，那么发生这种现象一般是vite打包框架引起的，代码或者工具里面有window.locaiton.href的操作导致子应用iframe的被跳走了，需要找出来是哪里引起的iframe跳走了

**Comment by yiludege** [comment]
官网的demo已经挂了一整天了，还没有出现这种现象，应该是后续的业务代码或者vite的工具、插件引入的问题？

**Comment by loser-or-no** [comment]
> 个人猜测： 1、发生这种现象的时候子应用的沙箱iframe发生了跳转，导致正常的沙箱被销毁了，iframe沙箱变成了一个正常的iframe 2、子应用的dom依然存在主应用上，所以可以正常看到子应用，但是点击的时候，绑定的事件回调都在iframe沙箱里面，而iframe沙箱已经被销毁了，所以表现为子应用怎么点击都没有反应 3、验证我这个猜测可以通过当子应用卡死后，查看一下子应用的iframe沙箱，如果这个iframe沙箱既有正常的dom也有js，也就是沙箱被摧毁了
> 
> 解决的办法： 如果上面的猜测是正确的，那么发生这种现象一般是vite打包框架引起的，代码或者工具里面有window.locaiton.href的操作导致子应用iframe的被跳走了，需要找出来是哪里引起的iframe跳走了

我中午在复现一下。看下iframe的结构

**Comment by loser-or-no** [comment]
> 个人猜测： 1、发生这种现象的时候子应用的沙箱iframe发生了跳转，导致正常的沙箱被销毁了，iframe沙箱变成了一个正常的iframe 2、子应用的dom依然存在主应用上，所以可以正常看到子应用，但是点击的时候，绑定的事件回调都在iframe沙箱里面，而iframe沙箱已经被销毁了，所以表现为子应用怎么点击都没有反应 3、验证我这个猜测可以通过当子应用卡死后，查看一下子应用的iframe沙箱，如果这个iframe沙箱既有正常的dom也有js，也就是沙箱被摧毁了
> 
> 解决的办法： 如果上面的猜测是正确的，那么发生这种现象一般是vite打包框架引起的，代码或者工具里面有window.locaiton.href的操作导致子应用iframe的被跳走了，需要找出来是哪里引起的iframe跳走了

![9e3659c11a28b35c03279e4a44c50e8](https://github.com/Tencent/wujie/assets/38649449/478d3ef1-a86d-4ceb-80f9-810cba732d22)
上面是正确的iframe
![e5c7a536f3beb42a451d828c7fa622e](https://github.com/Tencent/wujie/assets/38649449/15aa84d5-77ee-4980-a805-19907122833f)
这个是出问题之后的

**Comment by yiludege** [comment]
这个问题大概率是电脑息屏或者长时间页面不动导致websocket 断联，vite发现websocket断联会触发子应用刷新，导致子应用iframe被 window.location.href = xxxx 跳转走了，子应用沙箱随即被销毁了

目前没有很好的办法解决，除非能保证长时间websocket不被断开，但是一般发生这样的情况都是在dev环境，线上是没有vite的websocket的，所以如果dev发生这样的问题可能只能刷新一下页面了

**Comment by yiludege** [comment]
后续如果有新的问题打开
