### ISSUE TITLE
window.$wujie.location.href 跳转问题

### ISSUE THREAD

**Issue by rowjayluo** [Tencent/wujie#847]
子应用中使用 window.$wujie.location.href = 'https://www.tencent.com/' 遇到两个问题：
1. 跳转到外部页面，wujie 会通过 iframe 渲染这个外部页面导致页面不符合预期
2. wujie 并没有将主应用地址修改为外部页面地址，而是作为路由参数拼接到主应用地址后面，会导致刷新网页后回到首页而不是停留在外部页面

**Comment by yiludege** [comment]
可以看看采用window.parent.location.href =  xxxx 呢
