### ISSUE TITLE
wujie中无法正常是用worker

### ISSUE THREAD

**Issue by Yang1998-jiale** [Tencent/wujie#851]
**描述bug**
再子应用中创建woker多线程时引入worker.js文件,这个操作在主应用嵌入子应用是报错

**错误截图**
![1715320203752](https://github.com/Tencent/wujie/assets/58675419/1ef00982-b19d-4647-b8b4-e7a2e33934da)

**Comment by wuxc** [comment]
同样的问题。 @Yang1998-jiale 请问有解决么？

**Comment by Yang1998-jiale** [comment]
> 同样的问题。 @Yang1998-jiale 请问有解决么？

没得呢 分析原因可能是请求的worker的资源在子应用 但是因为无界导致去主应用里找了

**Comment by myhighland** [comment]
最简单的方案是 父子应用使用nginx代理在同一域名下 直接解决跨域问题 另外一种方案是通过webpack或者window添加环境便令等对worker运行环境进行修改 但需要对子应用环境进行区分

**Comment by HowGraceU** [comment]
importScripts 不是在 worker 内部使用的吗
