### ISSUE TITLE
子应用中鼠标事件获取offset的值是基于wujie-app，不是基于指定元素

### ISSUE THREAD

**Issue by xult2471** [Tencent/wujie#852]
**描述bug**
Vue3子应用中，监听鼠标事件获取event的offset，它们的计算是基于wujie-app容器上的坐标，不是基于指定元素

**如何复现**
在Vue3子应用中，写一个div元素，监听点击事件，获取event中的offset

**错误截图**
![image](https://github.com/Tencent/wujie/assets/20784068/b16da800-721c-4692-a950-a50066cd34aa)

**最小复现仓库或者地址**
![image](https://github.com/Tencent/wujie/assets/20784068/67df5599-ccc3-4ccf-840b-4f4b9fd78bd4)

**Comment by Greasen** [comment]
咋解决的？
