### ISSUE TITLE
vue3什么时候可以作为基座

### ISSUE THREAD

**Issue by 163Coder** [Tencent/wujie#854]
**描述bug**
请问什么时候更新vue3 vite@5版本的基座呢？有计划嘛？

**如何复现**
—

**错误截图**
![1715580309015](https://github.com/Tencent/wujie/assets/169631984/9f47e7c2-47e8-4958-99e7-fe2e46553fe8)

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by yiludege** [comment]
你好这个只是模板，无界本身是支持vue3作为基座的
