### ISSUE TITLE
OffScreenCanvas无法使用自定义字体，Canvas和HTML可以应用自定义字体。

### ISSUE THREAD

**Issue by x007xyz** [Tencent/wujie#857]
如题

**Comment by yiludege** [comment]
这个问题和无界关系不大，但是因为子应用的dom是渲染在webcomponent 的 shadow dom中，所以可能会导致这样的问题，可以查一下是否是shadow dom 的问题呢

**Comment by WXperia** [comment]
只能把需要自定义字体的部分拆出来在主应用写，然后用事件去调用了
