### ISSUE TITLE
3层嵌套的情况下，不同UI框架，字体图标不显示问题

### ISSUE THREAD

**Issue by zhuangyinyin** [Tencent/wujie#859]
**描述bug**
主应用A（antdesignVue）嵌套子应用B（antdesignVue）、子应用B嵌套子应用C（element-UI），这种情况下，子应用C的字体图标不显示，如果单独打开子应用B，嵌套的内容是子应用C，嵌套2层，字体图标能正常显示

**如何复现**
给出详细的复现步骤
1、主应用使用AntdesignVue，内嵌子应用B AntdesignVue某个页面B1，
2、 在子应用B1页面里面，点击加载子应用C elementUI 的弹窗页面，字体图标不显示

**错误截图**
没有报错误，这种情况下，子应用C的字体图标文件没有初始化加载请求

**Comment by yiludege** [comment]
目前无界不打算支持到很深层的嵌套，因为问题会非常复杂，不过无界有一个能力，在主应用A 预执行子应用B和子应用C之后，子应用B嵌套子应用C的时候，会复用已经渲染好的子应用C（保持C的name相同），相当子应用B和子应用C本来是同级关系，但是dom部分是嵌套关系，可以参考一下来解决这个问题
