### ISSUE TITLE
路由后退无反应问题

### ISSUE THREAD

**Issue by zhangHongEn** [Tencent/wujie#864]
**描述bug**
官网demo路由问题

**如何复现**
给出详细的复现步骤
1、第一步 克隆wujie仓库
2、 第二步 访问http://localhost:7700/#/react16-sub/location
3. 第三步 切换内页tab到弹框
4. 刷新页面
5. 后退, 到弹框, **再次后退, 无反应**

**错误截图**
![image](https://github.com/Tencent/wujie/assets/26006485/9a35dfc8-569f-40b6-b784-54a17a01bf2c)

问题:
1. 不用sync模式, 这个路由问题就一定会存在吗, demo问题还是确实存在的问题? 现在没有已经存在的解决方案吗
2. 子应用拦截history不做跳转, 拦截后到顶层应做history跳转, 再传入假的location给子应用的router触发更新, 是否可行
  我想知道我现在用wujie是否需要自己额外的处理路由

**Comment by zhangHongEn** [comment]
@yiludege help

**Comment by zhangHongEn** [comment]
> **描述bug** 官网demo路由问题
> 
> **如何复现** 给出详细的复现步骤 1、第一步 克隆wujie仓库 2、 第二步 访问http://localhost:7700/#/react16-sub/location 3. 第三步 切换内页tab到弹框 4. 刷新页面 5. 后退, 到弹框, **再次后退, 无反应**
> 
> **错误截图** ![image](https://private-user-images.githubusercontent.com/26006485/337094432-9a35dfc8-569f-40b6-b784-54a17a01bf2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NzUwOTUsIm5iZiI6MTcxNzY3NDc5NSwicGF0aCI6Ii8yNjAwNjQ4NS8zMzcwOTQ0MzItOWEzNWRmYzgtNTY5Zi00MGI2LWI3ODQtNTRhMTdhMDFiZjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDExNTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkODIxODYyZTBmNTU2MDRjZTUxNmRhYzhkYjZkNmY5OGY3OTlmOTk0OGJmMDI2M2Q3ZjBlMGJhOTllZmVkNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZO3O1Zrw6WCh8d0WaVhuFkHb7fU9EWfE50doasbIOj8)
> 
> 问题:
> 
> 1. 不用sync模式, 这个路由问题就一定会存在吗, demo问题还是确实存在的问题? 现在没有已经存在的解决方案吗
> 2. 子应用拦截history不做跳转, 拦截后到顶层应做history跳转, 再传入假的location给子应用的router触发更新, 是否可行
>    我想知道我现在用wujie是否需要自己额外的处理路由

路由问题验证过了可以解决:
```js
// packages/wujie-core/src/iframe.ts 170行
// 子应用iframe不做路由动作, 会导致浏览器后退出问题
// 所有路由动作只在顶层应用执行
 history.constructor.prototype.pushState = function (data: any, title:
 string, url?: string): void {
    top.history.pushState(data, title, url)
}
// 浏览器后退通知子应用router更新组件
top.window.addEventListener('popstate', function(event) {
  top.frames[0].window.dispatchEvent(new CustomEvent(event.type, {...
event}))
})

// 736行
export function insertScriptToIframe(
   window.__WUJIE.proxy,
   window.__WUJIE.proxy,
   window.__WUJIE.proxy,
   top.location,
 );
```

``` js
// wujie/packages/wujie-core/src/proxy.ts
// location进行劫持
if (p === "location") {
  return top.location;
}
```

**Comment by yiludege** [comment]
目前采用iframe的沙箱方式，这样子应用的路由就完全和主应用的路由解耦了，你这种解决方式意味着又要让主应用负责所有子应用路由分发，这个和设计理念不符

**Comment by yiludege** [comment]
在无界的方案中，子应用iframe跳转路由会往 top的history里面push一条该iframe的记录，后退的时候会通知iframe回退一条路由，但是刷新之后原来的iframe被销毁了，后退的时候就没办法告诉子应用去做后退功能，这个问题有点无解了

**Comment by zhangHongEn** [comment]
> 在无界的方案中，子应用iframe跳转路由会往 top的history里面push一条该iframe的记录，后退的时候会通知iframe回退一条路由，但是刷新之后原来的iframe被销毁了，后退的时候就没办法告诉子应用去做后退功能，这个问题有点无解了

是啊原生行为决定子应用只要调history就会出问题, 多个应用在统一的路由里用path区分应该符合挺多人的需求的, 不过这个与wujie现在的设计理念差别较大, 子应用的base也用不上了, 感觉可以考虑出个模式或者如果有人需要自行采取吧

**Comment by yiludege** [comment]
无界后续准备将沙箱以及路由同步剥离出来，让用户自己可以实现自己的同步逻辑和沙箱
