### ISSUE TITLE
wujie嵌入两个子应用 ag grid，ag grid拖拽功能失效

### ISSUE THREAD

**Issue by mrprince** [Tencent/wujie#884]
**描述bug**
主应用，加载两个子应用
![image](https://github.com/user-attachments/assets/6ddfb81e-0b53-412b-87b9-8c384dfa7c2b)
https://github.com/mrprince/micro-frontend/blob/master/src/App.tsx

子应用使用ag grid
![image](https://github.com/user-attachments/assets/60f8535d-f807-4193-a032-46b51650cb06)
https://github.com/mrprince/sub-app/blob/master/src/App.tsx

**如何复现**
给出详细的复现步骤
随机会出现其中一个子应用拖拽功能失效，期望结果两个子应用拖拽功能都正常。

**错误截图**
能推拽
![image](https://github.com/user-attachments/assets/8da12752-c6e3-4e2a-938b-aab57e7d7422)
不能拖拽
![image](https://github.com/user-attachments/assets/f20a2385-ff2d-4ccc-81c7-91cc751a1c81)

**最小复现仓库或者地址**
主应用：https://github.com/mrprince/micro-frontend/
子应用：https://github.com/mrprince/sub-app/

**Comment by edward492626** [comment]
别找了，自己写个patch  package修复吧

**Comment by edward492626** [comment]
![image](https://github.com/user-attachments/assets/18c6ba10-ee6b-4218-b2d9-6284b0a1a9f1)
