### ISSUE TITLE
有没有可能，一个子应用的两个页面，在主应用的同一屏中显示，并且使用一个 iframe?

### ISSUE THREAD

**Issue by Allenice** [Tencent/wujie#885]
比如子应用有两个页面，A, B,  我需要在主应用的左边和右边显示这两个页面(中间是另一个应用的页面)。目前可以设置不同的名字可以让这两个页面同屏显示，但是这样会创建两个 iframe。

**Comment by yiludege** [comment]
没有可能，因为一个vue实例一次只能渲染一个页面，哪怕vue改成多实例，路由也只有一条，多个vue实例最后也是渲染成多多个相同的页面，如果搞一个虚拟路由，似乎可以做但是这样一来已经完成了一个微前端大半的工作量了
