### ISSUE TITLE
在主应用中点击子应用任意菜单后，主应用资源一直重复加载

### ISSUE THREAD

**Issue by ztaom** [Tencent/wujie#90]
所有的配置都跟demo一样，点击子应用菜单之后，主应用资源一直重复加载

按照“子应用iframe初始化时加载、执行了主应用的资源”这个里面提供的方案配置之后未解决问题，不知道大家有没有遇到过同样的问题

**Comment by imrickywong** [comment]
有最小可复现 demo 么？

**Comment by ztaom** [comment]
已解决

**Comment by yiludege** [comment]
具体是啥问题呢？
