### ISSUE TITLE
react-beautiful-dnd在wujie页面中，拖拽时，onDragStart没有正常触发，是否因为wujie的什么限制

### ISSUE THREAD

**Issue by JeremyChenn** [Tencent/wujie#918]
**描述bug**
react-beautiful-dnd在wujie页面中，拖拽时，onDragStart没有正常触发，是否因为wujie的什么限制

**如何复现**
页面中引入
`import { DragDropContext, Droppable, Draggable } from 'react-beautiful-dnd';

const onDragStart = () => {
  console.log('query-111111:', 111111);
};
const onDragEnd = () => {
  console.log('query-111112:', 111111);
};

const items = [
    { id: '1', content: 'Item 1' },
    { id: '2', content: 'Item 2' },
    { id: '3', content: 'Item 3' },
  ];
  
  <DragDropContext onDragStart={onDragStart} onDragEnd={onDragEnd}>
            <Droppable droppableId="droppable">
              {(provided: any) => (
                <div {...provided.droppableProps} ref={provided.innerRef}>
                  {items.map((item, index) => (
                    <Draggable key={item.id} draggableId={item.id} index={index}>
                      {(provided: any) => (
                        <div
                          ref={provided.innerRef}
                          {...provided.draggableProps}
                          {...provided.dragHandleProps}
                        >
                          {item.content}
                        </div>
                      )}
                    </Draggable>
                  ))}
                  {provided.placeholder}
                </div>
              )}
            </Droppable>
          </DragDropContext>
`
元素可以正常加载出来，但没办法拖动

**Comment by JeremyChenn** [comment]
可以用这个文件，当作一个路由放到子应用中直接调试

`import React, { useEffect } from 'react';
import { DragDropContext, Droppable, Draggable } from 'react-beautiful-dnd';

const onDragStart = () => {
  // console.log('query-11:', 111111);
};

const onDragEnd = () => {
  // console.log('query-12:', 111111);
};

const Home = () => {

  useEffect(() => {
    document.getElementById('myElement').addEventListener('click', function(event) {
      const path = event.path || (event.composedPath && event.composedPath());
      if (path) {
        path.forEach(element => {
          console.log('query-element', element);
        });
      }
    });
  }, []);


  const items = [
    { id: '1', content: 'Item 1' },
    { id: '2', content: 'Item 2' },
    { id: '3', content: 'Item 3' },
  ];


  return (
    <div id="myElement" style={{padding: '100px 600px'}}>

      <DragDropContext onDragStart={onDragStart} onDragEnd={onDragEnd}>
            <Droppable droppableId="droppable">
              {(provided: any) => (
                <div {...provided.droppableProps} ref={provided.innerRef}>
                  {items.map((item, index) => (
                    <Draggable key={item.id} draggableId={item.id} index={index}>
                      {(provided: any) => (
                        <div
                          ref={provided.innerRef}
                          {...provided.draggableProps}
                          {...provided.dragHandleProps}
                        >
                          {item.content}
                        </div>
                      )}
                    </Draggable>
                  ))}
                  {provided.placeholder}
                </div>
              )}
            </Droppable>
          </DragDropContext>
    </div>
  );
};

export default Home;
`

**Comment by JoeWrights** [comment]
> 可以用这个文件，当作一个路由放到子应用中直接调试
> 
> `import React, { useEffect } from 'react'; import { DragDropContext, Droppable, Draggable } from 'react-beautiful-dnd';
> 
> const onDragStart = () => { // console.log('query-11:', 111111); };
> 
> const onDragEnd = () => { // console.log('query-12:', 111111); };
> 
> const Home = () => {
> 
> useEffect(() => { document.getElementById('myElement').addEventListener('click', function(event) { const path = event.path || (event.composedPath && event.composedPath()); if (path) { path.forEach(element => { console.log('query-element', element); }); } }); }, []);
> 
> const items = [ { id: '1', content: 'Item 1' }, { id: '2', content: 'Item 2' }, { id: '3', content: 'Item 3' }, ];
> 
> return ( <div id="myElement" style={{padding: '100px 600px'}}>
> 
> ```
>   <DragDropContext onDragStart={onDragStart} onDragEnd={onDragEnd}>
>         <Droppable droppableId="droppable">
>           {(provided: any) => (
>             <div {...provided.droppableProps} ref={provided.innerRef}>
>               {items.map((item, index) => (
>                 <Draggable key={item.id} draggableId={item.id} index={index}>
>                   {(provided: any) => (
>                     <div
>                       ref={provided.innerRef}
>                       {...provided.draggableProps}
>                       {...provided.dragHandleProps}
>                     >
>                       {item.content}
>                     </div>
>                   )}
>                 </Draggable>
>               ))}
>               {provided.placeholder}
>             </div>
>           )}
>         </Droppable>
>       </DragDropContext>
> </div>
> ```
> 
> ); };
> 
> export default Home; `

同样遇到这个问题，请问解决了吗，还是直接弃用beautiful-dnd了呢

**Comment by JoeWrights** [comment]
应该是因为beautiful-dnd不支持shadow root

**Comment by JeremyChenn** [comment]
> > 可以用这个文件，当作一个路由放到子应用中直接调试
> > `import React, { useEffect } from 'react'; import { DragDropContext, Droppable, Draggable } from 'react-beautiful-dnd';
> > const onDragStart = () => { // console.log('query-11:', 111111); };
> > const onDragEnd = () => { // console.log('query-12:', 111111); };
> > const Home = () => {
> > useEffect(() => { document.getElementById('myElement').addEventListener('click', function(event) { const path = event.path || (event.composedPath && event.composedPath()); if (path) { path.forEach(element => { console.log('query-element', element); }); } }); }, []);
> > const items = [ { id: '1', content: 'Item 1' }, { id: '2', content: 'Item 2' }, { id: '3', content: 'Item 3' }, ];
> > return ( <div id="myElement" style={{padding: '100px 600px'}}>
> > ```
> >   <DragDropContext onDragStart={onDragStart} onDragEnd={onDragEnd}>
> >         <Droppable droppableId="droppable">
> >           {(provided: any) => (
> >             <div {...provided.droppableProps} ref={provided.innerRef}>
> >               {items.map((item, index) => (
> >                 <Draggable key={item.id} draggableId={item.id} index={index}>
> >                   {(provided: any) => (
> >                     <div
> >                       ref={provided.innerRef}
> >                       {...provided.draggableProps}
> >                       {...provided.dragHandleProps}
> >                     >
> >                       {item.content}
> >                     </div>
> >                   )}
> >                 </Draggable>
> >               ))}
> >               {provided.placeholder}
> >             </div>
> >           )}
> >         </Droppable>
> >       </DragDropContext>
> > </div>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ); };
> > export default Home; `
> 
> 同样遇到这个问题，请问解决了吗，还是直接弃用beautiful-dnd了呢
