### ISSUE TITLE
wujie微前端性能

### ISSUE THREAD

**Issue by zhuzhuman978** [Tencent/wujie#92]
wujie与其他微前端以及ifame相比，性能如何？
有相关性能测试数据么？

**Comment by yiludege** [comment]
因为微前端场景非常复杂，不同的场景下测试性能差别很大，所以很难给到客观的数据

## 需要理解微前端框架的性能损耗的原因：

纯粹原生执行：js 没有损耗

乾坤执行：proxy带来的执行损耗、with 语句执行带来的全局作用域查找带来的损耗

micro-app：proxy带来的执行损耗、通过[globalKeyToBeCached](https://github.com/micro-zoe/micro-app/blob/b00b62dab9e747de46fc9b63c113ff848780d11b/src/source/scripts.ts#L639)避免了全局作用域查找问题

wujie：proxy带来的执行损耗

## 举个例子
在乾坤的这个 [issue](https://github.com/umijs/qiankun/issues/1555) 中性能问题主要是 with 语句执行带来，但是在micro-app 和 wujie 中测试就没有这个问题
