### ISSUE TITLE
无界新版本1.0.23之后，elementPlus下拉框定位问题用之前的方法不能兼容了 position: relative;

### ISSUE THREAD

**Issue by guoyanyan-gyy** [Tencent/wujie#921]
无界新版本1.0.23之后，elementPlus下拉框定位问题用之前的方法不能兼容了 position: relative;
现在锁定了1.0.22版本了可以解决

**Comment by yiludege** [comment]
好的，不知道哪个改动点导致的

**Comment by dizuncainiao** [comment]
![image](https://github.com/user-attachments/assets/7175e6b1-92fe-48d7-94f4-29a2613ed5dc)

我也遇到这个问题了，应该是所有的 **`.el-popper`** 相关的组件都受到了影响
目前回退了 `wujie` 版本解决了，期待在新版本中被解决

![image](https://github.com/user-attachments/assets/bda0475c-1cc4-404d-b934-fcbfc9ff2acb)

**Comment by ssyx8866** [comment]
牛逼牛逼，比wujie还靠谱

**Comment by yiludege** [comment]
elementPlus 是什么版本呢，我复现一下看看是什么问题

**Comment by guoyanyan-gyy** [comment]
2.7.6 版本的elementPlus

**Comment by guoyanyan-gyy** [comment]
> elementPlus 是什么版本呢，我复现一下看看是什么问题

2.7.6 版本的elementPlus

**Comment by 2733711860** [comment]
我这最新的element-plus@2.8.8，无界升级到1.0.23后也有这个问题。期待官方解决~~

**Comment by yiludege** [comment]
这周我把这个问题看一下，这个pr看起来是解决了这个问题，但是我还是不太清楚是啥原因

**Comment by Blade-gen** [comment]
@yiludege 这个问题显示已修复，但是使用 wujie@1.0.25 + element-plus@2.9.0 依旧存在该问题。
