### ISSUE TITLE
可否提供图片相对地址转化为绝对地址的plugin

### ISSUE THREAD

**Issue by s-boaz** [Tencent/wujie#93]
**描述bug**
清晰准确的描述bug

**如何复现**
给出详细的复现步骤
1、第一步 xxx
2、 第二步 xxx

**错误截图**
如果有可以将截图带上

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by yiludege** [comment]
框架已经做了这个事情了

**Comment by s-boaz** [comment]
> 框架已经做了这件事了

通过require到data里的svg图片并没有转换为绝对路径

**Comment by s-boaz** [comment]
![image](https://user-images.githubusercontent.com/34855763/186301473-f3b2adbb-67e6-4410-a7a6-f72512f1fdcd.png)

**Comment by yiludege** [comment]
require到data里的svg？这个代码看一下呢

**Comment by s-boaz** [comment]
> require到data里的svg？这个代码看一下呢

![image](https://user-images.githubusercontent.com/34855763/186310779-8c94b392-2cec-420b-94b5-96a43e81b336.png)

**Comment by ErKeLost** [comment]
> ![image](https://user-images.githubusercontent.com/34855763/186301473-f3b2adbb-67e6-4410-a7a6-f72512f1fdcd.png)

你这个地址是已经打包了的吧 你的图片指向是不是就是img

**Comment by yiludege** [comment]
@ErKeLost 这个地方就是webpack 的 url-loader处理 require 把相对地址赋值给到 data.img.xxx

框架在 patchRelativeUrlEffect 函数中已经劫持了 img 元素的 setAttribute 和 img.src = xxx 这样的set操作全部转为绝对地址

除非是采用innerHTML 这样的方式插入元素，这个地方我复现一下看看到底是什么问题

**Comment by s-boaz** [comment]
> @ErKeLost 这个地方就是webpack 的 url-loader处理 require 把相对地址赋值给到 data.img.xxx
> 
> 框架在 patchRelativeUrlEffect 函数中已经劫持了 img 元素的 setAttribute 和 img.src = xxx 这样的set操作全部转为绝对地址
> 
> 除非是采用innerHTML 这样的方式插入元素，这个地方我复现一下看看到底是什么问题

v-html

**Comment by yiludege** [comment]
v-html 框架无法做到，这个地方可否指定一下 publicPath

https://v4.webpack.js.org/loaders/file-loader/
