### ISSUE TITLE
wujie-vue3 npm无法下载

### ISSUE THREAD

**Issue by 18753278812** [Tencent/wujie#937]
**描述bug**
npm无法下载

**如何复现**
给出详细的复现步骤
npm views wujie-vue3

**错误截图**
如果有可以将截图带上
![image](https://github.com/user-attachments/assets/1ca6ef45-9daf-4a43-ac53-fc8e1ab4f82c)

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by yiludege** [comment]
我刚试了一下是可以正常安装的，如果使用的是淘宝之类的源，建议换一个呢

**Comment by 18753278812** [comment]
> 我刚试了一下是可以正常安装的，如果使用的是淘宝之类的源，建议换一个呢

刚刚试了一下，可以了
