### ISSUE TITLE
Subapplication modify system color invalid

### ISSUE THREAD

**Issue by shinenone** [Tencent/wujie#94]
ant design pro作为子应用修改系统色失效

尝试手动设置也不行
```
   ConfigProvider.config({
      theme: {
        primaryColor: obj.primaryColor,
      },
    });
```

**错误截图**
<img width="616" alt="image" src="https://user-images.githubusercontent.com/49889441/186638276-63c430b3-745f-40b3-b9cf-fbe7cfef9471.png">

**Comment by yiludege** [comment]
这个设置主题色的原理是什么？

**Comment by shinenone** [comment]
> 这个设置主题色的原理是什么？

基于ant design pro框架的内置主题。原理有个链接说的比较详细https://zhuanlan.zhihu.com/p/281773115

**Comment by ErKeLost** [comment]
https://github.com/ErKeLost/wujie/tree/bugfix/shadow-root-change-host

**Comment by shinenone** [comment]
> https://github.com/ErKeLost/wujie/tree/bugfix/shadow-root-change-host

未能解决。

**Comment by ErKeLost** [comment]
@shinenone 已经找到原因，shadow 处理 css3变量的bug，导致没有覆盖掉`--ant`变量，其实它新的css变量已经生成

**Comment by yiludege** [comment]
这个问题就是这样的，ant默认的css3全局变量挂载在 html 标签下面，每次修改主题，会在：host选择器下挂载新变量覆盖 html 中的变量

但是在无界中，：root中的变量是不生效的，框架会自动将：root选择器转变为：host选择器，但是：host的 css 变量优先级低于 html ，导致一直是默认的主题色生效，这个问题暂时没有很好的办法解决，可能需要对 ant-design-vue  的 ConfigProvider 做一下更改，将新的 css 变量挂载到 body 下优先级应该最高可以生效

所以说起来是第三方组件库没有适配 shadow dom，框架层面没办法适配哈

**Comment by huangyungeng** [comment]
> 这个问题就是这样的，ant默认的css3全局变量挂载在 html 标签下面，每次修改主题，会在：host选择器下挂载新变量覆盖 html 中的变量
> 
> 但是在无界中，：root中的变量是不生效的，框架会自动将：root选择器转变为：host选择器，但是：host的 css 变量优先级低于 html ，导致一直是默认的主题色生效，这个问题暂时没有很好的办法解决，可能需要对 ant-design-vue 的 ConfigProvider 做一下更改，将新的 css 变量挂载到 body 下优先级应该最高可以生效
> 
> 所以说起来是第三方组件库没有适配 shadow dom，框架层面没办法适配哈

可以有两种方案：
1、自己设置root颜色变量，覆盖html，模拟antd的颜色算法
2、`import 'ant-design-vue/dist/antd.variable.min.css';
ConfigProvider.config({
        theme,
      });`  
      把antd.variable.min.css里面的hmtl变量删掉，自然就用host的

**Comment by JCqiu** [comment]
> > 这个问题就是这样的，ant默认的css3全局变量挂载在 html 标签下面，每次修改主题，会在：host选择器下挂载新变量覆盖 html 中的变量
> > 但是在无界中，：root中的变量是不生效的，框架会自动将：root选择器转变为：host选择器，但是：host的 css 变量优先级低于 html ，导致一直是默认的主题色生效，这个问题暂时没有很好的办法解决，可能需要对 ant-design-vue 的 ConfigProvider 做一下更改，将新的 css 变量挂载到 body 下优先级应该最高可以生效
> > 所以说起来是第三方组件库没有适配 shadow dom，框架层面没办法适配哈
> 
> 可以有两种方案： 1、自己设置root颜色变量，覆盖html，模拟antd的颜色算法 2、`import 'ant-design-vue/dist/antd.variable.min.css'; ConfigProvider.config({ theme, });` 把antd.variable.min.css里面的hmtl变量删掉，自然就用host的

如果是服务器build,无法删掉html怎么处理
