### ISSUE TITLE
在iframe中嵌入微前端应用，如果不做任何操作，微前端中的子应用不会显示

### ISSUE THREAD

**Issue by hcs1995fiery** [Tencent/wujie#940]
代码很简单，如下，嵌入的地址是无界官方的地址。
现象：打开页面或者刷新页面，如果不做任何操作子应用不显示，只要鼠标移动一下，或者对页面有任何操作，子应用就显示出来了。
浏览器：谷歌

https://github.com/user-attachments/assets/c4947def-48b1-42a2-b82a-0c7a80487af3

Uploading -522036216353314042.mp4…

```[tasklist]
### Tasks
```

**Comment by hcs1995fiery** [comment]
![mmexport1734060319844](https://github.com/user-attachments/assets/b07a9169-5193-4dd3-afec-17ea7f1dba2a)

**Comment by intelligenceFY** [comment]
<img width="789" alt="image" src="https://github.com/user-attachments/assets/acb4e9b1-4c91-4997-bde1-11dd8581696e" />

**Comment by hcs1995fiery** [comment]
> <img alt="image" width="789" src="https://private-user-images.githubusercontent.com/34928410/396853817-acb4e9b1-4c91-4997-bde1-11dd8581696e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1OTE1MDEsIm5iZiI6MTczNDU5MTIwMSwicGF0aCI6Ii8zNDkyODQxMC8zOTY4NTM4MTctYWNiNGU5YjEtNGM5MS00OTk3LWJkZTEtMTFkZDg1ODE2OTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDA2NTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMjhjOTczZDhjZGRhZTJhMGRjZjM3NTZiODMyMGZjZGEyYjA3ZGI3OTU3NWY4OWZiNjI1NDg5MjljNTQzMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xgHoM2BM3e0P_a6gWfW6MuiUXC2WRPRXL05846k_4-A">

一开始我也以为是这个原因，可是认真分析一下，就发现没有这么简单了。
首先在iframe中主应用是正常加载出来的，主应用加载出来之后，可以在控制台通过获取dom元素，获取在主应用中本该存在的子应用的iframe，可是发现没有，这就说明加载子应用的iframe元素压根就没有被插入进来，所以这里也就不存在上面说的这个优化。
而后我去阅读源码并进行调试，发现在sandbox.js中start方法中，使用了requestIdleCallback方法，经过调试，发现是这个方法没有执行。
后来我去查阅资料，发现有些浏览器会对iframe中的空闲任务执行进行限制，不知道是不是这个原因。
![image](https://github.com/user-attachments/assets/7d72b9c7-775d-4336-9377-7982c9122980)

**Comment by hcs1995fiery** [comment]
补充：发现上面的代码是因为requestIdleCallback在iframe中没有生效。那是不是可以让三元走后面的逻辑执行，那就需要让this.fiber为false即可，所以追溯这个this.fiber的来源即可，发现这个值是可配置的就是，就是fiber参数。所以在代码中进行判断，是否是在iframe中打开，是的话就关闭fiber，否的话就开启。
![image](https://github.com/user-attachments/assets/36193301-3dac-495d-abaa-115db1a8694e)
