### ISSUE TITLE
sub application backgroud image not correct, use main application url prefix

### ISSUE THREAD

**Issue by way-jm** [Tencent/wujie#99]
**描述bug**
1.子应用中的backgroud image 的路径是使用了主应用的路径，没有被转换。

**如何复现**
给出详细的复现步骤
https://github.com/way-jm/wujie-demo
1、第一步 git clone https://github.com/way-jm/wujie-demo
2、 第二步 cd wujie-demo / yarn / yarn start
3、 第三步 为了简单起见，把子应用也写在了主应用内  cd son /    yarn / yarn start
4、 第四步 

**错误截图**
子应用单独运行，OK
![image](https://user-images.githubusercontent.com/18083432/187019015-b28f93d4-5064-441f-bb6a-7a58cdd58b67.png)
在wujie中运行
![image](https://user-images.githubusercontent.com/18083432/187019034-68893fcc-253e-4aed-9114-3b957961609f.png)

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度
https://github.com/way-jm/wujie-demo

**Comment by yiludege** [comment]
这个 动态的 background 不会经过 plugin，所以默认将相对路径的plugin没有发挥作用

对于webpack应用，具体可以在应用main文件最上方添加 import './config'

``` javascript
// config.js
if (window.__POWERED_BY_WUJIE__) {
  // eslint-disable-next-line
  __webpack_public_path__ = window.__WUJIE_PUBLIC_PATH__;
}
```

对于vite应用，可以试试这样的方式
[vite-plugin-dynamic-publicpath](https://github.com/jy0529/vite-plugin-dynamic-publicpath)
